# -*- coding: utf-8 -*-
"""Anatomy of a Limit Order Book.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from collections import defaultdict, deque
from dataclasses import dataclass, field
from typing import Dict, Deque, Optional
import time

@dataclass
class Order:
  order_id: int
  side: str
  price: float
  quantity: int
  timestamp: float = field(default_factory=time.time)
  is_hidden: bool = False

class PriceLevel:
  def __init__(self, price: float):
    self.price = price
    self.orders: Deque[Order] = deque()
    self.total_volume: int = 0

  def add_order(self, order: Order):
    self.orders.append(order)
    self.total_volume += order.quantity

  def cancel_order(self, order_id: int) -> Optional[Order]:
    for i, o in enumerate(self.orders):
      if o.order_id == order_id:
        self.total_volume -= o.quantity
        del self.orders[i]
        return o
    return None

  def fill(self, qty: int) -> int:
    filled = 0
    while qty > 0 and self.orders:
      front = self.orders[0]
      available = front.quantity
      if available <= qty:
        qty -= available
        filled += available
        self.orders.popleft()
      else:
        front.quantity -= qty
        filled += qty
        qty = 0
    self.total_volumes -= filled
    return filled

class LimitOrderBook:
  def __init__(self, instrument: str, tick_size: float = 0.01):
    self.instrument =  instrument
    self.tick_size = tick_size

    self.bids: Dict[float, PriceLevel] = {}
    self.asks: Dict[float, PriceLevel] = {}

    self._order_map: Dict[int, Order] = {}

    self._next_id: int = 1

  @property
  def best_bid(self) -> Optional[float]:
    return max(self.bids.keys()) if self.bids else None

  @property
  def best_ask(self) -> Optional[float]:
    return min(self.asks.keys()) if self.asks else None

  @property
  def spread(self) -> Optional[float]:
    if self.best_bid and self.best_ask:
      return self.best_ask - self.best_bid
    return None

  @property
  def mid_price(self) -> Optional[float]:
    if self.best_bid and self.best_ask:
      return (self.best_bid + self.best_ask) / 2
    return None

  @property
  def microprice(self) -> Optional[float]:
    if not (self.best_bid and self.best_ask):
       return None
    vb = self.bids[self.best_bid].total_volume
    va = self.asks[self.best_ask].total_volume
    return (self.best_ask * vb + self.best_bid * va) / (vb + va)

  def snapshot(self, levels: int = 5) -> dict:
    bids_sorted = sorted(self.bids.keys(), reverse=True)[:levels]
    asks_sorted = sorted(self.asks.keys())[:levels]
    return{
        'bids': [(p, self.bids[p].total_volume) for p in bids_sorted],
        'asks': [(p, self.asks[p].total_volume) for p in asks_sorted],
        'mid': self.mid_price,
        'microprice': self.microprice,
        'spread': self.spread,
    }