# -*- coding: utf-8 -*-
"""Bid and Ask Queues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np

def compute_queue_imbalance(lob_snapshot: dict) -> float:
  if not lob_snapshot['bids'] or not lob_snapshot['asks']:
    return 0.0
  bid_vol = lob_snapshot['bids'][0][1]
  asks_vol = lob_snapshot['asks'][0][1]
  return (bid_vol - asks_vol) / (bid_vol + asks_vol + 1e-12)

def compute_weighted_imbalance(lob_snapshot: dict, levels: int = 5, decay: float = 0.5) -> float:
  weights = np.array([decay**k for k in range(levels)])
  weights /= weights.sum()

  bids = lob_snapshot['bids'][:levels]
  asks = lob_snapshot['asks'][:levels]
  imbalances = []

  for k in range(min(levels, len(bids), len(asks))):
    d_b, d_a = bids[k][1], asks[k][1]
    imbalances.append((d_b - d_a) / (d_b + d_a + 1e-12))

  if not imbalances:
    return 0.0
  w = weights[:len(imbalances)]
  w /= w.sum()
  return float(np.dot(w, imbalances))

def compute_order_flow_imbalance(trade_df: pd.DataFrame, window: int = 100) -> pd.Series:
  def sign_trade(row):
    if row['price'] > row['mod_price']:
      return row['quantity']
    elif row['price'] < row['mid_price']:
      return -row['quantity']
    else:
      return np.sign(row.get('prev_price_change', 0)) * row['quantity']

    trades_df['signed'] = trades_df.apply(sign_trade, axis=1)
    ofi = trades_df['signed_Vol'].rolling(window).sum()
    return ofi

if __name__ == '__main__':
  snap = {
      'bids': [(99.98, 350), (99.96, 220), (99.94, 180)],
      'asks': [(100.00, 280), (100.02, 310), (100.04, 150)],
  }
  print(f"Top-of-book imbalance: {compute_queue_imbalance(snap):.4f}")
  print(f"Weighted imbalance(3-levels): "f"{compute_weighted_imbalance(snap, levels=3):.4f}")