# -*- coding: utf-8 -*-
"""Order Types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

from enum import Enum
from dataclasses import dataclass, field
from typing import Optional, List
import time

class OrderType(Enum):
  MARKET = "market"
  LIMIT = "limit"
  STOP = "stop"
  STOP_LIMIT = "stop_limit"
  FOK = "fok"
  IOC = "ioc"
  GTC = "gtc"

class Side(Enum):
  BUY = "buy"
  SELL = "sell"

class TimeInForce(Enum):
  GTC = "gtc"
  IOC = "ioc"
  FOK = "fok"
  DAY = "day"
  GTD = "gtd"

@dataclass
class OrderSpec:
  instrument: str
  side: Side
  order_type: OrderType
  quantity: int
  price: Optional[float] = None
  stop_price: Optional[float] = None
  time_in_force: TimeInForce = TimeInForce.GTC
  is_post_only: bool = False
  display_quantity: Optional[int] = None
  order_id: int = field(default_factory=lambda: int(time.time_ns()))

  def __post_init__(self):
    if self.order_type == OrderType.LIMIT and self.price is None:
      raise ValueError("Limit Order requires a Price.")
    if self.order_type == OrderType.STOP and self.stop_price is None:
      raise ValueError("Stop order requires a stop_price.")

def process_order(order: OrderSpec, lob: 'LimitOrderBook') -> dict:
  report = {
      'order_id': order.order_id,
      'status': "PENDING",
      'fills': [],
      'remaining_qty': order.quantity
  }

  if order.order_type == OrderType.MARKET:
    fills = execute_market_order(order, lob)
    report['fills'] = fills
    report['status'] = 'FILLED' if sum(f['qty'] for f in fills) == order.quantity else 'PARTIAL'

  elif order.order_type in (OrderType.LIMIT, OrderType.GTC):
    if order.order_type == OrderType.LIMIT and order.time_in_force == TimeInForce.IOC:
      fills = attempt_immediate_fill(order, lob)
      report['fills'] = fills
      report['status'] = 'CANCELLED' if not fills else 'PARTIAL_CANCEL'
    elif order.order_type == OrderType.LIMIT and order.time_in_force == TimeInForce.FOK:
      if check_full_fill_possible(order, lob):
        fils = execute_market_order(order, lob)
        report['fills'] = fills
        report['status'] = 'FILLED'
      else:
        report['status'] = 'CANCELLED'
        report['cancel_reason'] = 'FOK_NO_LIQIUDITY'
    else:
      post_limit_order(order, lob)
      report['status'] = 'RESTING'

  return report

def check_full_fill_possible(order: OrderSpec, lob: LimitOrderBook) -> bool:
  book_side = lob.asks if order.side == Side.SELL else lob.bids
  remaining = order.quantity
  price_limit = order.price or float('inf') if order.side == Side.BUY else (order.price or 0)

  for price in sorted(book_side.keys(), reverse=(order.side == Side.SELL)):
    if order.side == Side == Side.BUY and price > price_limit:
      break
    if order.side == Side.SELL and price < price_limit:
      break
    remaining -= book_side[price].total_volume
    if remaining <= 0:
      return True
  return False