# -*- coding: utf-8 -*-
"""Queue Dynamics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import matplotlib.pyplot as plt
from typing import Tuple

def simulate_queue_cont_larrard(
    n_bid: int,
    n_ask: int,
    lam_lo: float,
    lam_mo: float,
    lam_ca: float,
    dt: float = 0.001,
    T: float = 10.0,
    n_paths: int = 1000) -> Tuple[np.ndarray, np.ndarray]:
    n_steps = int(T/ dt)
    price_changes = []

    for _ in range(n_paths):
      q_bid, q_ask = n_bid, n_ask
      path_bid = [q_bid]
      path_ask = [q_ask]

      for step in range(n_steps):
        arr_bid = np.random.poisson(lam_lo * dt)
        arr_ask = np.random.poisson(lam_lo * dt) # Fixed: Assumed to be arr_ask
        mo_buy = np.random.poisson(lam_mo * dt)
        mo_sell = np.random.poisson(lam_mo * dt)
        can_bid = np.random.poisson(lam_ca * max(q_bid, 0) * dt)
        can_ask = np.random.poisson(lam_ca * max(q_ask, 0) * dt)
        q_bid = max(q_bid + arr_bid - mo_sell - can_bid, 0)
        q_ask = max(q_ask + arr_ask - mo_buy - can_ask, 0) # Fixed: Used arr_ask here

        if q_bid == 0 and q_ask == 0:
          price_changes.append(0)
          q_bid = int(np.random.exponential(n_bid))
          q_ask = int(np.random.exponential(n_ask))
        elif q_ask == 0:
          price_changes.append(-1)
          q_bid = int(np.random.exponential(n_bid))
        elif q_bid == 0:
          price_changes.append(+1)
          q_ask = int(np.random.exponential(n_ask))

        path_bid.append(q_bid)
        path_ask.append(q_ask)

      last_bid_path = np.array(path_bid)
      last_ask_path = np.array(path_ask)

    pc = np.array(price_changes)
    p_up = np.mean(pc == 1) if len(pc) > 0 else np.nan
    p_down = np.mean(pc == -1) if len(pc) > 0 else np.nan

    print(f"Theoretical p_up = {n_ask/(n_bid+n_ask):.4f}")
    print(f"Simulated p_up = {p_up:.4f}")
    print(f"Theoretical p_down = {n_bid/(n_bid+n_ask):.4f}")
    print(f"Simulated p_down = {p_down:.4f}")

    return last_bid_path, last_ask_path

bid_path, ask_path = simulate_queue_cont_larrard(n_bid=150, n_ask=80, lam_lo=3.0, lam_mo=1.0, lam_ca=0.01, dt=0.001, T=5.0, n_paths=5000)