# -*- coding: utf-8 -*-
"""Market Orders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

from dataclasses import dataclass
from typing import List, Tuple
import numpy as np

@dataclass
class Fill:
  price: float
  quantity: int

def execute_market_order_buy(
    lob: 'LimitOrderBook',
    quantity: int,
    check_only: bool = False) -> Tuple[List[Fill], float, float]:
    fills: List[Fill] = []
    remaining = quantity
    total_cost = 0.0
    pre_mid = lob.mid_price() or 0.0

    ask_levels = sorted(lob.asks.keys())

    for price in ask_levels:
      if remaining <= 0:
        break

      level = lob.asks[price]
      fill_qty = min(remaining, level.total_volume)

      fills.append(Fill(price=price, quantity=fill_qty))
      total_cost += price * fill_qty
      remaining -= fill_qty

      if not check_only:
        level.fill(fill_qty)
        if level.total_volume == 0:
          del lob.asks[price]

    total_filled = quantity - remaining
    vwap = total_cost / total_filled if total_filled > 0 else 0.0
    market_impact = vwap - pre_mid

    return fills, vwap, market_impact

def market_impact_model_sqrt(
    order_qty: int,
    daily_volume: int,
    daily_volatitlity: float,
    Y: float = 0.5) -> float:
    participation_rate = order_qty / daily_volume
    return daily_volatitlity * Y * np.sqrt(participation_rate)

if __name__ == '__main__':
  class MockLevel:
    def __init__(self, price, vol):
      self.price = price
      self.total_volume = vol
    def fill(self, qty):
      self.total_volume -= qty

  class MockLOB:
    def __init__(self):
      from collections import OrderedDict
      self.asks = {100.00: MockLevel(100.00, 200),
                   100.02: MockLevel(100.02, 350),
                   100.04: MockLevel(100.04, 150),
                   100.06: MockLevel(100.06, 80)}
      self.bids = {99.98: MockLevel(99.98, 300)}

    def mid_price(self):
      return 99.99

  lob = MockLOB()
  fills, vwap, impact = execute_market_order_buy(lob, 600)
  print(f"Fills: {[(f.price, f.quantity) for f in fills]}")
  print(f"VWAP: ${vwap:.4f}")
  print(f"Market Impact: ${impact:.4f}")
  print(f"Square-Root Impact(Approx): " f"${market_impact_model_sqrt(600, 1_00_000, 0.02):.4f}")

