# -*- coding: utf-8 -*-
"""Limit Orders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from scipy.optimize import minimize_scalar
import matplotlib.pyplot as plt

class AvellanedaStoikovMarketMaker:
  def __init__(self, sigma: float = 2.0, gamma: float = 0.1, kappa: float = 1.5, T: float = 1.0, dt: float = 0.005, q_max: int = 5):
    self.sigma = sigma
    self.gamma = gamma
    self.kappa = kappa
    self.T = T
    self.dt = dt
    self.q_max = q_max

  def reservation_price(self, S: float, q: float, t: float) -> float:
    return S - q * self.gamma * self.sigma**2 * (self.T - t)

  def optimal_spread(self, t: float) -> float:
    time_term = self.gamma * self.sigma**2 * (self.T - t)
    kappa_term = (2/ self.gamma) * np.log(1+self.gamma/self.kappa)
    return time_term + kappa_term

  def optimal_quotes(self, S: float, q: float, t: float):
    r = self.reservation_price(S, q, t)
    s = self.optimal_spread(t)
    bid = r - s / 2
    ask = r + s / 2
    return bid, ask

  def simulate(self, S0: float = 100.0, q0: int = 0, seed: int = 12) -> dict:
    np.random.seed(seed)
    n_steps = int(self.T / self.dt)
    lam = self.kappa

    S = S0
    q = q0
    cash = 0.0
    history = {'t': [], 'S': [], 'q': [], 'cash': [], 'pnl': [], 'bid': [], 'ask': [], 'r': []}

    for i in range(n_steps):
      t = i * self.dt
      bid, ask = self.optimal_quotes(S, q, t)
      r = self.reservation_price(S, q, t)

      dw = np.random.randn() * self.sigma * np.sqrt(self.dt)
      S += dw

      delta_b = S - bid
      delta = ask - S
      lam_b = lam * np.exp(-self.kappa * delta_b)
      lam_a = lam * np.exp(-self.kappa * delta)

      fill_buy = np.random.poisson(lam_b * self.dt)
      fill_sell = np.random.poisson(lam_a * self.dt)

      if fill_buy > 0 and q > -self.q_max:
        q -= 1
        cash += ask
      if fill_sell > 0 and q < self.q_max:
        q += 1
        cash -= bid

      pnl = cash + q * S

      history['t'].append(t)
      history['S'].append(S)
      history['q'].append(q)
      history['cash'].append(cash)
      history['pnl'].append(pnl)
      history['bid'].append(bid)
      history['ask'].append(ask)
      history['r'].append(r)

    return history

mm = AvellanedaStoikovMarketMaker(sigma=2.0, gamma=0.1, kappa=1.5, T=1.0)
hist = mm.simulate(S0=100.0)

print(f"Final PnL: {hist['pnl'][-1]:.4f}")
print(f"Final Inventory: {hist['q'][-1]}")
print(f"Optimal Spread at t=0: {mm.optimal_spread(0):.4f}")
print(f"Quotes at t=0, q=0: {mm.optimal_quotes(100.0, 0, 0)}")