# -*- coding: utf-8 -*-
"""Cancellations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from dataclasses import dataclass
from typing import Optional

@dataclass
class CancellationSignal:
  inventory: int
  inventory_limit: int
  ofi: float
  microprice_vs_quote: float
  time_since_placement: float
  fill_toxicity: float

class CancellationPolicy:
  def __init__(self, max_inventory: int = 5, ofi_threshold: float = 0.6, toxicity_threshold: float = 0.3, max_quotes_lag: float = 0.5, microprice_tol: float = 0.005):
    self.max_inventory = max_inventory
    self.ofi_threshold = ofi_threshold
    self.toxicity_threshold = toxicity_threshold
    self.max_quotes_lag = max_quotes_lag
    self.microprice_tol = microprice_tol

  def should_cancel_bid(self, sig: CancellationSignal) -> tuple:
    if sig.inventory <= -self.max_inventory:
      return True, "INVENTORY_LIMIT_SHORT"

    if sig.ofi < -self.ofi_threshold:
      return True, "NEGATIVE_OFI_SIGNAL"

    if sig.fill_toxicity > self.toxicity_threshold:
      return True, "HIGH_TOXICITY"

    if sig.microprice_vs_quote < -self.microprice_tol:
      return True, "STALE_BID_QUOTE"

    return False, "NO_CANCEL"

  def should_cancel_ask(self, sig:CancellationSignal) ->tuple:
    if sig.inventory >= self.max_inventory:
      return True, "INVENTORY_LIMIT_LONG"
    if sig.ofi > self.ofi_threshold:
      return True, "POSITIVE_OFI_SIGNAL"
    if sig.fill_toxicity > self.toxicity_threshold:
      return True, "HIGH_TOXICITY"
    if sig.microprice_vs_quote > self.microprice_tol:
      return True, "STALE_ASK_QUOTE"
    return False, "NO_CANCEL"

def compute_vpin(trade_buckets: list, bucket_size: int = 50) -> float:
  if len(trade_buckets) < 2:
    return 0.0
  vpins = []
  for bucket in trade_buckets:
    buys = bucket.get('buy_volume', 0)
    sells = bucket.get('sell_volume', 0)
    total = buys + sells
    if total > 0:
      vpins.append(abs(buys - sells) / total)
  return float(np.mean(vpins))

policy = CancellationPolicy()
signal = CancellationSignal(inventory=2, inventory_limit=5, ofi=-0.75, microprice_vs_quote=-0.002, time_since_placement=0.3, fill_toxicity=0.15)

cancel, reason = policy.should_cancel_bid(signal)
print(f"Cancel Bid? {cancel} | Reason: {reason}")