# -*- coding: utf-8 -*-
"""Hiddden Liquidity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

from pathlib import WindowsPath
import numpy as np
from collections import deque

class IcebergDetector:
  def __init__(self, window: int = 20, threshold: float = 2.5):
    self.window = window
    self.threshold = threshold
    self.depth_history: dict = {}
    self.trade_history: dict = {}

  def update(self, price: float, visible_depth: int, trade_volume: int):
    if price not in self.depth_history:
      self.depth_history[price] = deque(maxlen=self.window)
      self.trade_history[price] = deque(maxlen=self.window)
    self.depth_history[price].append(visible_depth)
    self.trade_history[price].append(trade_volume)

  def is_iceberg(self, price: float) -> tuple:
    if price not in self.depth_history:
      return False, 0.0

    depths = np.array(self.depth_history[price])
    trades = np.array(self.trade_history[price])

    if len(depths) < 5:
      return False, 0.0

    avg_depth = np.mean(depths)
    total_trades = np.sum(trades)

    if avg_depth < 1:
      return False, 0.0

    trade_to_depth_ratio = total_trades / (avg_depth * len(trades))

    depth_std = np.std(depths)
    depth_cv = depth_std / avg_depth if avg_depth > 0 else 0

    iceberg_score = trade_to_depth_ratio / (1 + depth_cv)
    is_ice = iceberg_score > self.threshold

    return is_ice, float(np.clip(iceberg_score / self.threshold, 0, 1))

class IcebergOrder:
  def __init__(self, order_id: int, side: str, price: float, total_qty: int, peak_size: int):
    self.order_id = order_id
    self.price = price
    self.total_qty = total_qty
    self.peak_size = peak_size
    self.remaining_hidden = total_qty - peak_size
    self.reload_count = 0
    self.visible_qty = peak_size

  def consume(self, qty: int) -> int:
    filled = min(qty, self.visible_qty)
    self.visible_qty -= filled
    if self.visible_qty == 0 and self.remaining_hidden > 0:
      reload_qty = min(self.peak_size, self.remaining_hidden)
      self.visible_qty = reload_qty
      self.remaining_hidden -= reload_qty
      self.reload_count += 1
    return filled

  @property
  def is_exhausted(self) -> bool:
    return self.visible_qty == 0 and self.remaining_hidden == 0

  @property
  def total_remaining(self) -> int:
    return self.visible_qty + self.remaining_hidden

detector = IcebergDetector(window=20, threshold=2.0)

for i in range(30):
  trade_vol = np.random.randint(80, 120)
  visible_depth = np.random.randint(90, 110)
  detector.update(100.00, visible_depth, trade_vol)

is_ice, confidence = detector.is_iceberg(100.00)
print(f"Is Iceberg: {is_ice}, Confidence: {confidence}")