# -*- coding: utf-8 -*-
"""Book Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.gridspec import GridSpec
from matplotlib.colors import LinearSegmentedColormap

def plot_lob_snapshot(lob_snapshot: dict, title: str = "LOB Depth Chart", levels: int = 10) -> plt.Figure:
  bids = lob_snapshot['bids'][:levels]
  asks = lob_snapshot['asks'][:levels]

  fig = plt.figure(figsize=(14, 7))
  fig.patch.set_facecolor('#F8F8FC')

  gs = GridSpec(1, 2, figure=fig, width_ratios=[1, 1], wspace=0.05)
  ax_bid = fig.add_subplot(gs[0])
  ax_ask = fig.add_subplot(gs[1])

  bid_prices = [b[0] for b in bids]
  bid_vols = [b[1] for b in bids]
  colors_bid = [plt.cm.Greens(0.4 + 0.5 * (1 - i/len(bids))) for i in range(len(bids))]

  bars_b = ax_bid.barh(
      y=[f"${p:.2f}" for p in bid_prices],
      width=bid_vols,
      color=colors_bid,
      edgecolor='#007040', linewidth=0.5,
      align='center')

  for bar, vol in zip(bars_b, bid_vols):
    ax_bid.text(bar.get_width() + 5, bar.get_y() + bar.get_height()/2, f'{vol:,}', va='center', ha='left', fontsize=9, color='#AA1122', fontweight='bold')

  # Moved outside the loop
  ax_ask.set_xlabel('Volume(shares)', color='#AA1122', fontweight='bold')
  ax_bid.set_ylabel('Price', color='#AA1122', fontweight='bold', fontsize=13)
  ax_ask.spines['left'].set_visible(False) # Corrected typo: set_visilbe to set_visible
  ax_ask.yaxis.set_label_position('right')
  ax_ask.yaxis.tick_right()

  mid = lob_snapshot.get('mid', None)
  spread = lob_snapshot.get('spread', None)
  micro = lob_snapshot.get('microprice', None)

  info_str = ""
  if mid: info_str += f"Mid: ${mid:.4f}"
  if spread: info_str += f"\nSpread: ${spread:.4f}"
  if micro: info_str += f"\nMicro: ${micro:.4f}"

  fig.suptitle(title, fontsize=15, fontweight='bold', color='#003366', y=1.01)
  fig.text(0.5, -0.02, info_str, ha='center', fontsize=10, color='#445566')

  plt.tight_layout()
  return fig # Moved outside the loop

def plot_lob_heatmap(time_series_snapshots: list, price_center: float, price_range: float = 0.20, tick_size: float = 0.01) -> plt.Figure:
  n_ticks = int(2 * price_range / tick_size) + 1
  # Corrected np.arange call
  prices = np.arange(price_center - price_range, price_center + price_range, tick_size/2)

  n_times = len(time_series_snapshots)
  bid_matrix = np.zeros((n_ticks, n_times))
  ask_matrix = np.zeros((n_ticks, n_times))

  for j, (_, snap) in enumerate(time_series_snapshots):
    for price, vol in snap.get('bids', []):
      # Corrected price[0] to prices[0]
      idx = int(round((price - prices[0]) / (tick_size/2))) # Adjusted division for tick_size/2 step
      if 0 <= idx < n_ticks:
        bid_matrix[idx, j] = vol
    for price, vol in snap.get('asks', []):
      # Corrected price[0] to prices[0]
      idx = int(round((price - prices[0]) / (tick_size/2))) # Adjusted division for tick_size/2 step
      if 0 <= idx < n_ticks:
        ask_matrix[idx, j] = vol

  fig, ax = plt.subplots(figsize=(14, 7))
  ax.patch.set_facecolor('#0A0A14') # Corrected typo in hex code

  bid_norm = bid_matrix / (bid_matrix.max() + 1e-6)
  ask_norm = ask_matrix / (ask_matrix.max() + 1e-6)

  bid_cmap = LinearSegmentedColormap.from_list('bid', ['#0A0A14', '#00A04A']) # Corrected typo in hex code
  ask_cmap = LinearSegmentedColormap.from_list('ask', ['#0A0A14', '#CC1122']) # Corrected typo in hex code

  # Removed repeated cmap argument
  ax.imshow(bid_norm, cmap=bid_cmap, aspect='auto', origin='lower', alpha=0.85, extent=[0, n_times, prices[0], prices[-1]])
  ax.imshow(ask_norm, cmap=ask_cmap, aspect='auto', origin='lower', alpha=0.85, extent=[0, n_times, prices[0], prices[-1]])

  ax.set_xlabel("Time", color='White')
  ax.set_ylabel("Price", color='White')
  ax.set_title("LOB Heatmap", color='White', fontsize=14)
  ax.tick_params(axis='x', colors='White')

  for sp in ax.spines.values(): # Corrected typo: vlaues to values
    sp.set_color('#334455')

  return fig # Moved outside the loop