# -*- coding: utf-8 -*-
"""Liquidity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Tuple
from enum import Enum

class OrderSide(Enum):
  BID = -1
  ASK = +1

@dataclass
class QuoteSnapshot:
  timestamp: pd.Timestamp
  bid: float
  ask: float
  bid_size: float
  ask_size: float

  @property
  def mid(self) -> float:
    return (self.bid + self.ask) / 2.0

  @property
  def quoted_spread(self) -> float:
    return self.ask - self.bid

  @property
  def relative_spread(self) -> float:
    return self.quoted_spread / self.mid

  @property
  def quoted_spread_bps(self) -> float:
    return self.relative_spread * 10_000

  @property
  def quoted_depth(self) -> float:
    return self.bid_size + self.ask_size

  @property
  def order_book_imbalance(self) -> float:
    total = self.bid_size + self.ask_size
    if total == 0:
      return 0.0
    return (self.bid_size - self.ask_size) / total

@dataclass
class Trade:
  timestamp: pd.Timestamp
  price: float
  size: float
  size: float
  direction: int
  quote_at_trade: Optional[QuoteSnapshot] = None

  @property
  def notional(self) -> float:
    return self.price * self.size

  def effective_spread(self) -> Optional[float]:
    if self.quote_at_trade is None:
      return None
    return 2.0 * self.direction * (self.price - self.quote_at_trade.mid)

  def effective_spread_bps(self) -> Optional[float]:
    es = self.effective_spread()
    if es is None or self.quote_at_trade is None:
      return None
    return (es / self.quote_at_trade.mid) * 10_000

class LeeReadySigner:
  def __init__(self):
    self._last_direction = 0
    self._last_price = None

  def classify(self, trade_price: float, bid: float, ask: float) -> int:
    mid = (bid + ask) / 2.0

    if trade_price > mid:
      direction = +1
    elif trade_price < mid:
      direction = -1
    else:
        if self._last_price is None:
          direction = 0
        elif trade_price > self._last_price:
          direction = +1
        elif trade_price < self._last_price:
          direction = -1
        else:
          direction = self._last_direction

    self._last_direction = direction
    self._last_price = trade_price
    return direction

class LiquidityAnalyzer:
  def __init__(self, quotes: List[QuoteSnapshot], trades: List[Trade]):
    self.quotes = quotes
    self.trades = trades
    self._quotes_df = self._to_quotes_df()
    self._trades_df = self._to_trades_df()

  def _to_quotes_df(self) -> pd.DataFrame:
    rows = [{
        'timestamp': q.timestamp,
        'bid': q.bid,
        'ask': q.ask,
        'bid_size': q.bid_size,
        'ask_size': q.ask_size,
        'mid': q.mid,
        'spread': q.quoted_spread,
        'relative_spread': q.relative_spread,
        'spread_bps': q.quoted_spread_bps,
        'quoted_depth': q.quoted_depth,
        'obi': q.order_book_imbalance,
    } for q in self.quotes]
    df = pd.DataFrame(rows)
    df.set_index('timestamp', inplace=True)
    return df

  def _to_trades_df(self) -> pd.DataFrame:
    rows = [{
        'timestamp': t.timestamp,
        'price': t.price,
        'size': t.size,
        'notional': t.notional,
        'direction': t.direction,
        'eff_spread': t.effective_spread() if t.quote_at_trade else np.nan,
        'eff_spread_bps': t.effective_spread_bps() if t.quote_at_trade else np.nan,} for t in self.trades]
    df = pd.DataFrame(rows)
    df.set_index('timestamp', inplace=True)
    return df

  def time_weighted_spread(self) -> float:
    df = self._quotes_df.copy()
    df['duration'] = df.index.to_series().diff().shift(-1).dt.total_seconds()
    df.dropna(subset=['duration'], inplace=True)
    df = df[df['duration'] > 0]
    twas = np.average(df['spread_bps'], weights=df['duration'])
    return twas

  def volume_weighted_spread(self) -> float:
    df = self._trades_df.dropna(subset=['eff_spread_bps'])
    if df.empty:
      return np.nan
    return np.average(df['eff_spread_bps'], weights=df['notional'])

  def oredr_flow_imbalance(self, window: str = '1min') -> pd.Series:
    df = self._trades_df.copy()
    df['buy_vol'] = np.where(df['direction'] > 0, df['notional'], 0)
    df['sell_vol'] = np.where(df['direction'] < 0, df['notional'], 0)
    resampled = df[['buy_vol', 'sell_vol']].resample(window).sum()
    total = resampled['buy_vol'] + resampled['sell_vol']
    ofi = (resampled['buy_vol'] - resampled['sell_vol']) / total
    return ofi

  def amihud_illiquidity(self, window: str = '1D') -> pd.Series:
    df = self._trades_df.copy()
    df['ret'] = df['price'].pct_change().abs()
    resampled = df[['ret', 'notional']].resample(window).agg({'ret': 'sum', 'notional': 'sum'})
    illiq = resampled['ret'] / resampled['notional']
    return illiq * 1e6

  def summary_stats(self) -> pd.DataFrame:
    qdf = self._quotes_df
    tdf = self._trades_df

    stats = {
        'Time-Wtd Quoted Spread(bps)':
        self.time_weighted_spread(),
        'Mean Quoted Spread(bps)':
        qdf['spread_bps'].mean(),
        'Median Quoted Spread(bps)':
        qdf['spread_bps'].median(),
        'Std Quoted Spread(bps)':
        qdf['spread_bps'].std(),
        'Mean Quoted Depth (Shares)':
       qdf['quoted_depth'].mean(),
        'Mean Effective Spread (bps)':
        tdf['eff_spread_bps'].mean(),
        'Volume Weighted Eff Spread (bps)':
        self.volume_weighted_spread(),
        'Trade Count': len(tdf),
        'Total Notional ($)': tdf['notional'].sum(),
        'Buy %' : (tdf['direction'] > 0).mean() * 100,
    }
    return pd.Series(stats)

if __name__ == '__main__':
  np.random.seed(12)
  n_quotes = 10000

  dt = 1/6500
  sigma = 0.001
  mid_returns = np.random.normal(0, sigma * np.sqrt(dt), n_quotes)
  mid_prices = 100.0 * np.exp(np.cumsum(mid_returns))

  spread_mean = 0.05
  spread_speed = 5.0
  spread_vol = 0.001
  spread = np.zeros(n_quotes)
  spread[0] = spread_mean
  for i in range(1, n_quotes):
    spread[i] = (spread[i-1] + spread_speed * (spread_mean - spread[i-1]) * dt + spread_vol * np.sqrt(dt) * np.random.normal())
    spread[i] = max(spread[i], 0.005)

  timestamps = pd.date_range('2024-01-15 09:30:00', periods=n_quotes, freq='1s')
  quotes = [QuoteSnapshot(timestamp=timestamps[i],
                          bid=mid_prices[i] - spread[i]/2,
                          ask=mid_prices[i] + spread[i]/2,
                          bid_size=np.random.exponential(500),
                          ask_size=np.random.exponential(500),)
                          for i in range(n_quotes) ]

  n_trades = int(n_quotes * 0.7)
  trade_indices = np.random.choice(n_quotes, n_trades, replace=False)
  trade_indices.sort()

  trades = []
  signer = LeeReadySigner()

  for idx in trade_indices:
    q = quotes[idx]
    if np.random.rand() > 0.5:
      trade_price = q.ask * (1 + np.random.normal(0, 0.0001))
    else:
      trade_price = q.bid * (1 - np.random.normal(0, 0.0001))

    trade_size = np.random.randint(100, 1000)

    direction = signer.classify(trade_price, q.bid, q.ask)

    trades.append(Trade(timestamp=q.timestamp,
                        price=trade_price,
                        size=trade_size,
                        direction=direction,
                        quote_at_trade=q))

  print('Liquidity Infrastructure Setup Complete')
  print(f"Simulated {n_quotes} quote snapshots")
  print(f"Simulated {len(trades)} trades")
  print(f"Mean mid price: ${mid_prices.mean():.2f}")
  print(f"Mean Spread: {np.mean(spread)*100:.4f} cents")
  print(f"Mean spread(bps): {np.mean(spread)/mid_prices.mean()*10000:.4f}")

analyzer = LiquidityAnalyzer(quotes, trades)
summary = analyzer.summary_stats()
print(summary)