# -*- coding: utf-8 -*-
"""Institutional Liquidity Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

@dataclass
class MarketParams:
  sigma: float
  eta: float
  gamma: float
  S0: float = 100.0
  ADV: float = 1e7

@dataclass
class TradeParams:
  X: float
  T: float
  N: int = 20
  risk_aversion: float = 1e-6

class AlmgrenChrissModel:
  def __init__(self, market: MarketParams, trade: TradeParams):
    self.m = market
    self.t = trade
    self.tau = trade.T / trade.N
    self.kappa = self._compute_kappa()

  def _compute_kappa(self) -> float:
    kappa_tilde = np.sqrt(
        self.t.risk_aversion * self.m.sigma ** 2 / self.m.eta
    )
    kappa = (1/self.tau) * np.arccosh(
        0.5 * (kappa_tilde**2 * self.tau**2 + 2) + 1e-15
    ) if kappa_tilde * self.tau < 10 else kappa_tilde
    return kappa

  def optimal_trajectory(self) -> Tuple[np.ndarray, np.ndarray]:
    N = self.t.N
    T = self.t.T
    X = self.t.X
    kappa = self.kappa

    times = np.linspace(0, T, N+1)

    if kappa * T < 1e-6:
      x = X * (1 - times / T)
    else:
      x = X * np.sinh(kappa *(T - times)) / np.sinh(kappa * T)

    return times, x

  def trade_schedule(self) -> pd.DataFrame:
    times, x = self.optimal_trajectory()

    n = np.diff(x)
    n_sell = -n
    v = n_sell / self.tau

    temp_impact = self.m.eta * v**2 * self.tau
    perm_impact = self.m.gamma * x[1:] * v * self.tau

    df = pd.DataFrame({
        'time':times[1:],
        'inventory': x[1:],
        'shares_traded': n_sell,
        'temp_impact_cost': temp_impact,
        'perm_impact_cost': perm_impact,
        'pct_remaining': x[1:] / self.t.X * 100,
    })
    return df

  def expected_cost(self) -> float:
    times, x = self.optimal_trajectory()
    v = -np.diff(x) / self.tau

    temp_cost = self.m.eta * np.sum(v**2) * self.tau
    perm_cost = 0.5 * self.m.gamma * self.t.X**2
    return temp_cost + perm_cost

  def cost_variance(self) -> float:
    times, x = self.optimal_trajectory()
    return self.m.sigma**2 * np.sum(x[:-1]**2) * self.tau

  def risk_adjusted_cost(self) -> float:
    return self.expected_cost() + self.t.risk_aversion * self.cost_variance()

  def efficient_frontier(
      self,
      n_points: int = 50,
      lambda_range: Tuple = (1e-8, 1e-4),) -> pd.DataFrame:
      lambdas = np.logspace(
          np.log10(lambda_range[0]),
          np.log10(lambda_range[1]),
          n_points
      )

      frontier = []
      for lam in lambdas:
        model = AlmgrenChrissModel(
            self.m,
            TradeParams(
                X=self.t.X,
                T=self.t.T,
                N=self.t.N,
                risk_aversion=lam
            )
        )
        e_cost = model.expected_cost()
        std_cost = np.sqrt(model.cost_variance())

        frontier.append({
            'lambda': lam,
            'kappa': model.kappa,
            'E_cost': e_cost,
            'Std_cost': std_cost,
            'E_cost_bps': e_cost / self.m.S0 * 10_000,
            'std_cost_bps': std_cost / self.m.S0 * 10_000
        })
      return pd.DataFrame(frontier).sort_values('E_cost')

  def simulate(
      self,
      n_paths: int = 1000,
      seed: int = 12,) -> pd.DataFrame:
      np.random.seed(seed)
      times, x_opt = self.optimal_trajectory()
      n_trades = -np.diff(x_opt)

      total_costs = []

      for _ in range(n_paths):
        price = self.m.S0
        total_cost = 0.0

        for k in range(self.t.N):
          n_k = n_trades[k]
          v_k = n_k / self.tau

          price += -self.m.gamma * n_k

          price += self.m.sigma * np.sqrt(self.tau) * np.random.randn()

          exec_price = price + self.m.eta * v_k

          total_cost += exec_price * n_k

        is_cost = (total_cost - self.m.S0 * self.t.X) / self.t.X

        total_costs.append(is_cost)

      df = pd.Series(total_costs, name='IS_per_share')
      print(f"\nSimulation Results ({n_paths} paths):")
      print(f" Mean IS: {df.mean():.4f} (${df.mean()/self.m.S0*10000:.2f}bps)")
      print(f" Std IS: {df.std():.4f}")
      print(f" Analytical E: {self.expected_cost()/self.t.X:.4f}")
      return df

  def summary(self):
    ec = self.expected_cost()
    vc = self.cost_variance()
    schedule = self.trade_schedule()

    print("="*60)
    print("ALMGREN-CHRISS OPTIMAL EXECUTION SUMMARY")
    print("="*60)
    print(f"Total shares to execute: {self.t.X:,.0f}")
    print(f"Execution horizon: {self.t.T:.2f}days ({self.t.T*6.5:.1f} hours)")
    print(f"Number of intervals: {self.t.N}")
    print(f"Risk aversion (lambda): {self.t.risk_aversion:.2e}")
    print(f"Urgency paramenter (kappa): {self.kappa:.4f}")
    print(f"kappa*T: {self.kappa*self.t.T:.4f}")
    print(f"\n--- COST METRICS ---")
    print(f"Expected cost: ${ec/self.m.S0*10000:.2f}bps/share")
    print(f"Cost Std dev: {np.sqrt(vc):.2f}")
    print(f"Risk-adjusted cost (U): {self.risk_adjusted_cost():.2f}")
    print(f"\n--- TRADE SCHEDULE ---")
    print(schedule[['time', 'shares_traded', 'inventory', 'pct_remaining']])

market = MarketParams(
    sigma=0.02,
    eta=2.5e-5,
    gamma=2.5e-8,
    S0=50.0,
    ADV = 2e6,
)

trade = TradeParams(
    X=500_000,
    T=2.0,
    N=40,
    risk_aversion=1e-6,
)

model = AlmgrenChrissModel(market, trade)
model.summary()

frontier = model.efficient_frontier()
print(f"\nFrontier computed: {len(frontier)} points")
print(f"Min expected cost: {frontier['E_cost_bps'].min():.2f} bps")
print(f"Max expected cost: {frontier['E_cost_bps'].max():.2f} bps")

