# -*- coding: utf-8 -*-
"""Bid-Ask Spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

def simulate_glosten_milgrom(
    V_H: float = 100.0,
    V_L: float = 90.0,
    delta_0: float = 0.5,
    mu: float = 0.3,
    n_trades: int = 200,
    true_value: str = 'H',
    seed: int = 12) -> pd.DataFrame:
    np.random.seed(seed)
    V = V_H if true_value == 'H' else V_L
    delta = delta_0

    records = []
    for t in range(n_trades):
      # Probabilities of informed traders buying/selling given true value V_H or V_L
      # P(buy | V_H) = (1+mu)/2, P(sell | V_H) = (1-mu)/2
      # P(buy | V_L) = (1-mu)/2, P(sell | V_L) = (1+mu)/2

      prob_buy_given_H = (1 + mu) / 2
      prob_buy_given_L = (1 - mu) / 2

      prob_sell_given_H = (1 - mu) / 2
      prob_sell_given_L = (1 + mu) / 2

      # Unconditional probabilities of observing a buy or sell order
      prob_buy = delta * prob_buy_given_H + (1 - delta) * prob_buy_given_L
      prob_sell = delta * prob_sell_given_H + (1 - delta) * prob_sell_given_L

      # Beliefs after observing a buy or sell order (for bid/ask calculation)
      # P(V_H | buy)
      delta_given_buy = (delta * prob_buy_given_H) / prob_buy
      # P(V_H | sell)
      delta_given_sell = (delta * prob_sell_given_H) / prob_sell

      # Market maker sets bid and ask based on these updated beliefs
      ask = delta_given_buy * V_H + (1 - delta_given_buy) * V_L
      bid = delta_given_sell * V_H + (1 - delta_given_sell) * V_L

      # Mid price based on current belief
      mid = delta * V_H + (1 - delta) * V_L

      # Simulate the actual trade
      is_informed = np.random.rand() < mu
      if is_informed:
        # Informed trader trades based on true value V
        direction = +1 if V == V_H else -1
      else:
        # Uninformed trader (noise trader) trades randomly
        direction = +1 if np.random.rand() < 0.5 else -1

      # The price at which the trade occurs
      price = ask if direction == +1 else bid

      # Update belief (delta_new) after observing the *actual* trade direction
      if direction == +1: # Observed a buy
        delta_new = delta_given_buy
      else: # Observed a sell
        delta_new = delta_given_sell

      # Record the state *before* updating delta for the next trade
      records.append({
          't': t,
          'delta': delta, # Belief at the start of this period 't'
          'bid': bid,
          'ask': ask,
          'mid': mid,
          'spread': ask - bid,
          'direction': direction,
          'is_informed': is_informed,
          'V_true': V,
          'price': price,
      })

      delta = delta_new # Update delta for the next iteration/trade

    return pd.DataFrame(records)

def plot_gm_simulation(df: pd.DataFrame, title: str = ""):
  fig = plt.figure(figsize=(14, 10))
  gs = gridspec.GridSpec(3, 2, figure=fig, hspace=0.4, wspace=0.35)
  ax1 = fig.add_subplot(gs[0, :])
  ax2 = fig.add_subplot(gs[1, 0])
  ax3 = fig.add_subplot(gs[1, 1])
  ax4 = fig.add_subplot(gs[2, :])

  ax1.plot(df['t'], df['mid'], 'b-', linewidth=1.5, label='Miideprice(Belief)')
  ax1.plot(df['t'], df['bid'], 'r-', linewidth=0.8, alpha=0.6, label='Bid')
  ax1.plot(df['t'], df['ask'], 'g-', linewidth=0.8, alpha=0.6, label='Ask')
  ax1.axhline(y=df['V_true'].iloc[0], color='k', linestyle='--', linewidth=2, label=f'True Value V={df['V_true'].iloc[0]:.0f}')

  buys = df[df['direction'] == +1]
  sells = df[df['direction'] == -1]
  ax1.scatter(buys['t'], buys['price'], color='green', s=10, alpha=0.5, zorder=5)
  ax1.scatter(sells['t'], sells['price'], color='red', s=10, alpha=0.5, zorder=5)
  ax1.set_xlabel('Trade Number')
  ax1.set_ylabel('Price')
  ax1.legend(loc='upper left', fontsize=8)
  ax1.set_title(title)
  ax1.grid(True, alpha=0.2998244353)

  ax2.plot(df['t'], df['delta'], 'b-', linewidth=1.5)
  ax2.axhline(y=(1 if df['V_true'].iloc[0] > 100 else 0), color='k', linestyle='--', label='True State')
  ax2.set_xlabel('Trade Number')
  ax2.set_ylabel(r'$\delta_t = \Pr(V_H | \mathcal{F}_t)$')
  ax2.set_ylim(-0.05, 1.05)
  ax2.grid(True, alpha=0.2998244353)

  ax3.plot(df['t'], df['spread'], 'r-', linewidth=1.5)
  ax3.set_xlabel('Trade Number')
  ax3.set_ylabel('Bid-Ask Spread')
  ax3.grid(True, alpha=0.2998244353)

  df['cum_ofi'] = df['direction'].cumsum()
  ax4.fill_between(df['t'], df['cum_ofi'], 0, where=df['cum_ofi'] >=0 , color='green', alpha=0.4, label='Net Buy')
  ax4.fill_between(df['t'], df['cum_ofi'], 0, where=df['cum_ofi'] <=0 , color='red', alpha=0.4, label='Net Sell')
  ax4.plot(df['t'], df['cum_ofi'], 'k-', linewidth=0.8)
  ax4.set_xlabel('Trade Number')
  ax4.set_ylabel('Cumulative Net Order Flow')
  ax4.set_title('Order Flow Imbalance')
  ax4.legend()
  ax4.grid(True, alpha=0.2998244353)

  plt.suptitle(f"Glosten-Kilgrom Model Simulation{""+title if title else ""}", fontsize=14)
  plt.savefig('gm_simulation.png', dpi=150, bbox_inches='tight')
  plt.show()

df_H = simulate_glosten_milgrom(mu=0.3, true_value='H', n_trades=200)
print("=== GM Model: True Value = HIGH ===")
print(f"Initial belief: {df_H['delta'].iloc[0]:.3f}")
print(f"Final belief: {df_H['delta'].iloc[-1]:.3f}")
print(f"Initial Spread: {df_H['spread'].iloc[0]:.4f}")
print(f"Final Spread: {df_H['spread'].iloc[-1]:.4f}")
print(f"Intial Midprice: {df_H['mid'].iloc[0]:.4f}")
print(f"Final Midprice: {df_H['mid'].iloc[-1]:.4f}")
print(f"True Vlaue: {df_H['V_true'].iloc[0]:.4f}")
plot_gm_simulation(df_H, title="True Value = HIGH (V_H=110)")

