# -*- coding: utf-8 -*-
"""Bid-Ask Spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
from scipy import stats

def generate_synthetic_panel(n_stocks: int = 100, n_days: int = 252, seed: int = 12) -> pd.DataFrame:
  np.random.seed(seed)
  records = []
  for s in range(n_stocks):
    base_price = np.exp(np.random.normal(np.log(50), 1))
    base_vol = np.random.uniform(0.15, 0.60)
    base_adv = np.exp(np.random.normal(np.log(1e7), 1))

  for d in range(n_days):
    vol = base_vol * (1 + 0.5 * np.random.randn())
    vol = max(vol, 0.05)

    price = base_price * np.exp(np.random.normal(0, vol/np.sqrt(252)))

    adv = base_adv * (1 + 0.3 * np.random.randn())
    adv = max(adv, 1000)

    log_spread_bps = (0.5 + 2.0 * np.log(vol) - 0.8 * np.log(adv / 1e6) + 0.3 * np.log(1 / price) + 0.15 * np.random.randn())
    spread_bps = np.exp(log_spread_bps)

    records.append({
        'stock': s,
        'day': d,
        'spread_bps': spread_bps,
        'log_spread': log_spread_bps,
        'vol_daily': vol / np.sqrt(252),
        'log_vol': np.log(vol),
        'price': price,
        'log_price': np.log(price),
        'adv_mm': adv / 1e6,
        'log_adv': np.log(adv),
        'vol_per_price': vol / price,
    })

  return pd.DataFrame(records)

def run_spread_regrassion(df: pd.DataFrame) -> None:
  X = df[['log_vol', 'log_adv', 'log_price']].copy()
  X = sm.add_constant(X)
  y = df['log_spread']
  model = sm.OLS(y, X).fit(cov_type='HC3')

  print('=' * 60)
  print("SPREAD DETERMINANTS: LOG-LOG OLS REGRESSION")
  print("=" * 60)
  print(model.summary())

  print("\n--- ECONOMIC INTERPRETATION ---")
  print(f"Volatility elasticity: {model.params['log_vol']:.3f}")
  print(f"  => 10% higher vol => {model.params['log_vol'] * 10:.1f}% Change in Spread")
  print(f"Volume elasticity: {model.params['log_price']:.3f}")

df_panel = generate_synthetic_panel(n_stocks=200, n_days=252)
run_spread_regrassion(df_panel)
print(f"\nPanel dimension: {df_panel.shape}")
print(f"Mean Spread: {df_panel['spread_bps'].mean():.3f} bps")
print(f"Median Spread: {df_panel['spread_bps'].median():.3f} bps")

