# -*- coding: utf-8 -*-
"""Effective Spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass
from typing import Optional

def compute_effective_spread(
    trades: pd.DataFrame,
    quotes: pd.DataFrame,
    pre_trade_lag_ms: float = 100.0,
    post_trade_window_ms: float = 5000.0,) -> pd.DataFrame:

    trades = trades.sort_values(by="timestamp").copy()
    quotes = quotes.sort_values(by="timestamp").copy()
    quotes['mid'] = (quotes['ask'] + quotes['bid']) / 2.0
    quotes['spread'] = quotes['ask'] - quotes['bid']

    results = []

    for _, trade in trades.iterrows():
        t = trade['timestamp']
        p = trade['price']
        Q = trade['direction']
        v = trade['size']

        pre_lag = pd.Timedelta(milliseconds=pre_trade_lag_ms)
        pre_quotes = quotes[quotes['timestamp'] <= t - pre_lag]
        if pre_quotes.empty:
          continue

        mid_pre = pre_quotes['mid'].iloc[-1]
        spread_q = pre_quotes['spread'].iloc[-1]

        post_window = pd.Timedelta(milliseconds=post_trade_window_ms)
        post_quotes = quotes[(quotes['timestamp'] > t
                              ) & (quotes['timestamp'] <= t + post_window)]
        mid_post = post_quotes['mid'].iloc[-1] if not post_quotes.empty else np.nan

        eff_spread = 2.0 * Q * (p - mid_pre)
        eff_spread_bps = eff_spread / mid_pre * 10_000
        eff_spread_pct_q = eff_spread / spread_q if spread_q > 0 else np.nan

        price_impact = 2.0 * Q * (mid_post - mid_pre) if not np.isnan(mid_post) else np.nan
        price_impact_bps = price_impact / mid_pre * 10_000 if not np.isnan(price_impact) else np.nan

        realised_spread = eff_spread - price_impact if not np.isnan(price_impact) else np.nan
        realised_spread_bps = realised_spread / mid_pre * 10_000 if not np.isnan(realised_spread) else np.nan

        half_quoted = spread_q / 2.0
        price_improvement = half_quoted - abs(p - mid_pre)
        price_improvement_bps = price_improvement / mid_pre * 10_000

        results.append({
            'timestamp': t,
            'price': p,
            'direction': Q,
            'size': v,
            'notional': p * v,
            'mid_pre': mid_pre,
            'mid_post': mid_post,
            'quoted_spread': spread_q,
            'quoted_spread_bps': spread_q / mid_pre * 10_000,
            'effective_spread': eff_spread,
            'effective_spread_bps': eff_spread_bps,
            'price_impact': price_impact,
            'price_impact_bps': price_impact_bps,
            'realised_spread': realised_spread,
            'realised_spread_bps': realised_spread_bps,
            'price_improvement': price_improvement,
            'price_improvement_bps': price_improvement_bps,
            'pct_price_imporvement': (price_improvement > 0),
        })

    result_df = pd.DataFrame(results)
    return result_df

def summarize_execution_quality(df: pd.DataFrame) -> pd.DataFrame:
  if df.empty:
    return pd.DataFrame()

  def vwm(series, weights):
    mask = series.notna() & weights.notna()
    if mask.sum() == 0: return np.nan
    return np.average(series[mask], weights=weights[mask])

  v = df['notional']

  report = {
      'Total Trades': len(df),
      'Total Notional ($M)': df['notional'].sum() / 1e6,
      '---- QUOTED SPREAD ----': '',
      'TW Quoted Spread (bps)': df['quoted_spread_bps'].mean(),
      'VW Quoted Spread (bps)': vwm(df['quoted_spread_bps'],v),
      '---- EFFECTIVE SPREAD ----': '',
      'TW Effective Spread (bps)': df['effective_spread_bps'].mean(),
      'VW Effective Spread (bps)': vwm(df['effective_spread_bps'],v),
      '---- DECOMPOSITION ----' : '',
      'VW Price Impact (bps)' : vwm(df['price_impact_bps'], v),
      'vw Realised Spread (bps)': vwm(df['realised_spread_bps'], v),
      '---- PRICE IMPROVEMENT ----': '',
      'PI Rate(%)': df['pct_price_improvement'].mean() * 100,
      'VW PI Amount (bps)': vwm(df['price_improvement_bps'], v),
      '---- SPREAD RATIO': '',
      'Eff/Quoted Ratio': (vwm(df['effective_spread_bps'], v)) / vwm(df['quoted_spread_bps'], v),
  }
  return pd.Series(report)