# -*- coding: utf-8 -*-
"""Realized Spread.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def compute_realized_spread_term_structure(
    trades: pd.DataFrame,
    mids: pd.Series,
    horizon_ms: list = [0, 100, 500, 1000, 5000, 30000, 300000],) -> pd.DataFrame:

    results = {}

    for horizon_ms in horizon_ms:
      tau = pd.Timedelta(milliseconds=horizon_ms)
      eff_spreads = []
      realised_spreads = []
      price_impacts = []
      weights = []

      for _, trade in trades.iterrows():
        t = trade['timestamp']
        P = trade['price']
        Q = trade['direction']
        v = trade['notioinal']

        pre_mids = mids[mids.index <= t]
        if pre_mids.empty: continue
        mid_0 = pre_mids.iloc[-1]

        if horizon_ms == 0:
          mid_tau = mid_0
        else:
          post_mids = mids[(mids.index > t) & (mids.index <= t + tau)]
          if post_mids.empty:
            available = mids[mids.index > t]
            if available.empty: continue
            mid_tau = available.iloc[0]
          else:
            mid_tau = post_mids.iloc[-1]

        es = 2 * Q * (P - mid_0)
        rs = 2 * Q * (P - mid_tau)
        pi = 2 * Q * (mid_tau - mid_0)

        eff_spreads.append(es / mid_0 * 10_000)
        realised_spreads.append(rs / mid_0 * 10_000)
        price_impacts.append(pi / mid_0 * 10_000)
        weights.append(v)

      if not weights:
        continue

      w = np.array(weights)
      w_norm = w / w.sum()

      results[horizon_ms] = {
          'horizon_ms': horizon_ms,
          'horizon_label': f'{horizon_ms}ms' if horizon_ms < 1000 else f'{horizon_ms//1000}s',
          'ES_bps': np.average(eff_spreads, weights=w_norm) if eff_spreads else np.nan,
          'RS_bps': np.average(realised_spreads, weights=w_norm) if realised_spreads else np.nan,
          'PI_bps': np.average(price_impacts, weights=w_norm) if price_impacts else np.nan,
      }

    df = pd.DataFrame(results.values())
    df['adv_Sel_ratio'] = df['PI_bps'] / df['ES_bps']
    df['realliesd_ratio'] = df['RS_bps'] / df['ES_bps']
    return df

def plot_spread_decomposition(term_structure: pd.DataFrame):
  fig, axes = plt.subplots(1, 2, figsize=(14, 5))

  ts = term_structure.reset_index(drop=True)
  x = np.arange(len(ts))
  labels = ts['horizon_label'].tolist()

  ax = axes[0]
  ax.fill_between(x, 0, ts['RS_bps'], alpha=0.6, color='blue', label='Realised Spread (RS)')
  ax.fill_between(x, ts['RS_bps'],ts['ES_bps'], alpha=0.6, color='red', label='Price Impact(PI)')
  ax.axhline(ts['ES_bps'].mean(), color='k', linestyle='--', linewidth=1, label='Effective Spread(ES)')
  ax.set_xticks(x)

  ax.set_xticklabels(labels, rotation=45)
  ax.set_ylabel('Spread (bps)')
  ax.legend()
  ax.set_title('Spread Decomposition: Level')
  ax.grid(True, alpha=0.3)

  ax = axes[1]
  ax.plot(x, ts['adv_sel_ratio'] * 100, 'r-0', linewidth=2, marketsize=6, label='Adverse Selection %')
  ax.plot(x, ts['realised_ratio'] * 100, 'b-0', linewidth=2, marketsize=6, label='Realised Spread %')
  ax.axhline(50, color='k', linestyle=':', linewidth=0.8)
  ax.set_xticks(x)
  ax.set_xtickslabels(labels, rotation=45)
  ax.set_ylabel('Fraction of effective Spread (%)')
  ax.set_title('Information Content: Adverse Selection Ratio')
  ax.legend()
  ax.grid(True, apha=0.3)
  ax.set_ylim(-10, 110)

  plt.suptitle('Realised Spread Term Structure', fontsize=13, fontweight='bold')
  plt.tight_layout()
  plt.savefig('realized_spread_term_structure.png', dpi=150, bbox_inches='tight')
  plt.show()

print('Realized Spread Analysis: Horizon Sensitivity Framework Ready')
print("Key insight: ES =RS(tau) + PI(tau) at every horizon tau")
print("As tau increases: RS decreases, PI increases (information revealed)")