# -*- coding: utf-8 -*-
"""Price Discovery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.tsa.vector_ar.vecm import coint_johansen, VECM

def estimate_kyle_lambda(
    trades: pd.DataFrame,
    frequency: str = '1min',
    price_col: str = 'mid',
    direction_col: str = 'direction',
    size_col: str = 'notional', ) -> dict:

    df = trades.copy()
    df['signed_vol'] = df[direction_col] * df[size_col]

    agg = df.resample(frequency).agg({
        price_col: ['first', 'last'],
        'signed_vol': 'sum',
        size_col: 'sum',
    })
    agg.columns = ['price_open', 'price_close', 'signed_vol', 'total_vol']
    agg['ret_bps'] = (agg['price_close'] / agg['price_open'] - 1) * 10_000
    agg.dropna(inplace=True)

    X1 = sm.add_constant(agg['signed_vol'])
    y1 = agg['ret_bps']
    model1 = sm.OLS(y1, X1).fit(cov_type='HAC', cov_kwds={'maxlags': 5})

    lambda_ols = model1.params['signed_vol']

    agg['lambda_amihud'] = agg['ret_bps'].abs() / (agg['total_vol'] / 1e6)

    dP = agg['price_close'].diff().dropna()
    gamma_hat = dP.autocorr(lag=1)
    lambda_roll = 2 * np.sqrt(max(-gamma_hat * dP.var(), 0)) if not np.isnan(gamma_hat) else np.nan

    results = {
        'lambda_OLS_bps_Mm': lambda_ols,
        'lambda_OLS_tstat': model1.tvalues['signed_vol'],
        'lambda_OLS_rsq': model1.rsquared,
        'lambda_amihud_mean': agg['lambda_amihud'].mean(),
        'lambda_roll': lambda_roll,
        'n_obs': len(agg),
        'model': model1,
    }

    print("=" * 60)
    print("KYLE'S LAMBDA ESTIMATION")
    print("=" * 60)
    print(f"Method 1 (OLS): {lambda_ols:.4f} bps per $M signed flow")
    print(f" t-stat: {model1.tvalues['signed_vol']:.2f}, R = {model1.rsquared:.4f}")
    print(f"Method 2 (Amihud): {agg['lambda_amihud'].mean():.4f} bps per $M")
    print(f"Method 3 (Roll): {lambda_roll:.4f}")
    print(f"Observations: {len(agg)}")

    return results

def estimate_information_share(
    m1: pd.Series,
    m2: pd.Series,
    lags: int = 5,) -> dict:

    from statsmodels.tsa.stattools import coint

    df = pd.DataFrame({'m1': m1, 'm2': m2}).dropna()

    score, pval, crits = coint(df['m1'], df['m2'])
    print(f"\nEngle-Granger Cointegration Test:")
    print(f" Test Statistic: {score:.4f}, p-value: {pval:.4f}")
    print(f" {'     Cointegrated' if pval < 0.05 else ' Not Cointegrated'} at 5% level")

    model = VECM(df, k_ar_diff=lags, coint_rank=1)
    vecm_fit = model.fit()

    alpha = vecm_fit.alpha
    alpha_1, alpha_2 = alpha[0, 0], alpha[1, 0]

    total_alpha = alpha_1 + alpha_2
    cs_1 = alpha_2 / total_alpha if total_alpha != 0 else 0.5
    cs_2 = alpha_1 / total_alpha if total_alpha != 0 else 0.5

    print(f"\nVECM Error Correction:")
    print(f" alpha_1 (venue 1 adjustment): {alpha_1:.6f}")
    print(f" alpha_2 (venue 2 adjustment): {alpha_2:.6f}")

    print(f"\nComponent Shares (Gonzalo-Granger): ")
    print(f" CS_1: {cs_1:.4f} ({cs_1 * 100:.1f}%)")
    print(f" CS_2: {cs_2:.4f} ({cs_2*100:.1f}%)")

    return {
        'alpha_1': alpha_1,
        'alpha_2': alpha_2,
        'component_share_1': cs_1,
        'component_share_2': cs_2,
        'vecm_fit': vecm_fit,
    }

np.random.seed(12)
n = 5000
true_price = np.cumsum(np.random.normal(0, 0.02, n)) + 100

venue1 = true_price + np.random.normal(0, 0.005, n)

venue2 = np.zeros(n)
venue2[0] = venue1[0]

for t in range(1, n):
  venue2[t] = venue2[t-1] + 0.3*(venue1[t-1] - venue2[t-2]) + np.random.normal(0, 0.003)

ts = pd.date_range('2024-01-15 9:30:00', periods=n, freq='1s')
m1 = pd.Series(venue1, index=ts)
m2 = pd.Series(venue2, index=ts)

print("Price Discovery Analysis Setup")
print(f"Simulated {n} observations")
print(f"Venue 1 leads price discovery (true by construction)")
results = estimate_information_share(m1, m2, lags=5)

