# -*- coding: utf-8 -*-
"""Information Incorporation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from scipy.optimize import minimize
from scipy.special import gammaln
import pandas as pd
from typing import Tuple, Optional

class PINModel:

  def __init__(self):
    self.params_ = None
    self.log_likelihood_ = None
    self.pin_ = None

  def log_likelihood(
      self,
      theta: np.ndarray,
      B: np.ndarray,
      S: np.ndarray,) -> float:

      alpha, delta, mu, eps_b, eps_s = theta

      def log_poisson(k, lam):
        return k * np.log(lam + 1e-10) - lam - gammaln(k+1)
      log_b1 = (np.log(1 - alpha + 1e-10) +
                log_poisson(B, eps_b) +
                log_poisson(S, eps_s))

      log_b2 = (np.log(alpha + 1e-10) +
                np.log(delta + 1e-10) +
                log_poisson(B, mu + eps_b) +
                log_poisson(S, eps_s))

      log_b3 = (np.log(alpha + 1e-10) +
                np.log(1 - delta + 1e-10) +
                log_poisson(B, eps_b) +
                log_poisson(S, mu + eps_s))

      log_b_stack = np.column_stack([log_b1, log_b2, log_b3])
      b_max = log_b_stack.max(axis=1, keepdims=True)
      log_b_sum = b_max.squeeze() + np.log(np.exp(log_b_stack - b_max).sum(axis=1))

      return log_b_sum.sum()

  def compute_pin(self, theta: np.ndarray) -> float:
    alpha, delta, mu, eps_b, eps_s = theta
    return alpha * mu / (alpha * mu + eps_b + eps_s)

  def fit(
      self,
      B: np.ndarray,
      S: np.ndarray,
      n_starts: int = 10,
      seed: int = 12,) -> 'PINModel':
      np.random.seed(seed)
      best_ll = -np.inf
      best_params = None
      bounds = [(0.001, 0.999), (0.001, 0.999), (1.0, 10000.0), (1.0, 10000.0), (1.0, 10000.0)]

      for start in range(n_starts):
        theta0 = [np.random.uniform(0.1, 0.9),
                  np.random.uniform(0.1, 0.9),
                  np.random.uniform(10, 1000),
                  np.random.uniform(10, 1000),
                  np.random.uniform(10, 1000),]

        try:
          result = minimize(
              fun=lambda theta: -self.log_likelihood(theta, B, S),
              x0=theta0,
              method='L-BFGS-B',
              bounds=bounds,
              options={'maxiter': 2000, 'ftol': 1e-12},
          )

          if result.success and -result.fun > best_ll:
            best_ll = -result.fun
            best_params = result.x
        except Exception:
          continue

      if best_params is None:
        raise RuntimeError("MLE optimization failed for all starting points.")

      self.params_ = best_params
      self.log_likelihood_ = best_ll
      self.pin_ = self.compute_pin(best_params)
      return self

  def summary(self) -> str:
    if self.params_ is None:
      return "Model not fitted yet."
    alpha, delta, mu, eps_b, eps_s = self.params_
    return (
        f"\n{'='*50}\n"
        f"PIN MODEL RESULTS \n"
        f"{'='*50}\n"
        f" alpha (P( event )): {alpha:.4f}\n"
        f" delta (P( good news )): {delta:.4f}\n"
        f"mu ( informed rate ): {mu:.2f} orders /day\n"
        f" eps_b ( uninf . buy rate ): {eps_b:.2f}orders /day \n"
        f" eps_s ( uninf . sell rate ): {eps_s:.2f}orders /day \n"
        f"{'='*50}\n"
        f" PIN = {self.pin_:.4f} ({self.pin_*100:.2f}%)\n"
        f" Log - Likelihood = {self.log_likelihood_:.4f}\n"
        f"{'='*50}\n"
        f" Interpretation :\n"
        f" {self.pin_*100:.1f}% of order flow is information - driven \n"
        f" {(1 - self.pin_)*100:.1f}% is noise trading \n"
    )

np.random.seed(42)
n_days = 60
alpha_true = 0.4
delta_true = 0.6
mu_true = 150
eps_b_true = 200
eps_s_true = 200
PIN_true = alpha_true * mu_true / ( alpha_true * mu_true +
eps_b_true + eps_s_true )
print ( f" True PIN: {PIN_true:.4f} ({PIN_true*100:.1f}%)")
B_obs = []
S_obs = []
for _ in range ( n_days ) :
  event = np.random.rand() < alpha_true
  if event :
    good = np.random.rand() < delta_true
    if good :
      B_obs . append (np.random.poisson (mu_true + eps_b_true ) )
      S_obs . append (np.random.poisson (eps_s_true ) )
    else:
      B_obs . append (np.random.poisson (eps_b_true ) )
      S_obs . append (np.random.poisson (mu_true + eps_s_true ) )
  else :
    B_obs . append (np.random.poisson (eps_b_true ) )
    S_obs . append (np.random.poisson (eps_s_true ) )

B_obs = np.array (B_obs)
S_obs = np.array (S_obs)

pin_model = PINModel()
pin_model.fit(B_obs, S_obs, n_starts=100)
print(pin_model.summary())

