# -*- coding: utf-8 -*-
"""Liquidity Shocks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass
from typing import List, Optional, Callable
from collections import deque
from enum import Enum

class ShockSeverity(Enum):
  NORMAL = 0
  ELEVATED = 1
  WARNING = 2
  CRITICAL = 3

@dataclass
class LiquidityShockEvent:
  timestamp: pd.Timestamp
  severity: ShockSeverity
  spread_z_score: float
  depth_z_score: float
  impact_z_score: float
  composite_score: float
  trigger_metrics: dict

class AdaptiveLiquidShockDetector:
  def __init__(
      self,
      lookback_window: int = 500,
      spread_threshold: float = 3.0,
      depth_threshold: float = 3.0,
      impact_threshold: float = 3.0,
      composite_threshold: float = 2.5,):
    self.lookback_window = lookback_window
    self.spread_threshold = spread_threshold
    self.depth_threshold = depth_threshold
    self.impact_threshold = impact_threshold
    self.composite_threshold = composite_threshold

    self._spread_history = deque(maxlen=lookback_window)
    self._depth_history = deque(maxlen=lookback_window)
    self._impact_history = deque(maxlen=lookback_window)
    self._ofi_history = deque(maxlen=lookback_window) # Corrected typo: maxlean -> maxlen

    self.events: List[LiquidityShockEvent] = []

  def _rolling_z_score(self, series: deque, current: float) -> float:
    if len(series) < 20:
      return 0.0
    hist = np.array(series)
    mu = hist.mean()
    sigma = hist.std() + 1e-10
    return (current - mu) / sigma

  def update(self,
             timestamp: pd.Timestamp,
             spread_bps: float,
             depth: float,
             ofi: float,
             price_impact: float,) -> Optional[LiquidityShockEvent]: # Corrected return type hint placement
    self._spread_history.append(spread_bps)
    self._depth_history.append(-depth)
    self._impact_history.append(price_impact)
    self._ofi_history.append(abs(ofi))

    z_spread = self._rolling_z_score(self._spread_history, spread_bps)
    z_depth = self._rolling_z_score(self._depth_history, -depth)
    z_impact = self._rolling_z_score(self._impact_history, price_impact)
    z_ofi = self._rolling_z_score(self._ofi_history, abs(ofi))

    composite = 0.35 * z_spread + 0.30 * z_depth + 0.20 * z_impact + 0.15 * z_ofi

    max_z = max(z_spread, z_depth, z_impact)
    if composite > self.composite_threshold * 2.0 or max_z > 5.0:
      severity = ShockSeverity.CRITICAL
    elif composite > self.composite_threshold * 1.5 or max_z > 4.0:
      severity = ShockSeverity.WARNING
    elif composite > self.composite_threshold * 1.0 or max_z > 3.0:
      severity = ShockSeverity.ELEVATED
    else:
      severity = ShockSeverity.NORMAL

    if severity != ShockSeverity.NORMAL: # Corrected typo: sverity -> severity
      event = LiquidityShockEvent(
          timestamp=timestamp,
          severity=severity,
          spread_z_score=z_spread,
          depth_z_score=z_depth,
          impact_z_score=z_impact,
          composite_score=composite,
          trigger_metrics={ # Corrected typo: trigger_mertics -> trigger_metrics
              'spread_bps': spread_bps,
              'depth': depth,
              'ofi': ofi,
              'price_impact': price_impact,
              'z_spread': z_spread,
              'z_depth': z_depth,
              'z_impact': z_impact,
              'z_ofi': z_ofi,
          }
      )
      self.events.append(event)
      return event
    return None # Corrected indentation

  def shock_summary(self) -> pd.DataFrame:
    if not self.events:
      return pd.DataFrame()

    rows = [{
        'timestamp': e.timestamp,
        'severity': e.severity.name,
        'composite_score': e.composite_score,
        'spread_z': e.spread_z_score,
        'depth_z': e.depth_z_score,
        'impact_z': e.impact_z_score,
    } for e in self.events]

    return pd.DataFrame(rows)

np.random.seed(12)
n_normal = 500
n_shock = 50

spread_normal = np.random.lognormal(np.log(3), 0.3, n_normal)
depth_normal = np.random.lognormal(np.log(1e6), 0.4, n_normal) # Corrected typo: lognornal -> lognormal
impacts_normal = np.random.lognormal(np.log(2), 0.5, n_normal) # Corrected typo: np.random_lognormal -> np.random.lognormal

spread_shock = np.random.lognormal(np.log(30), 0.5, n_shock)
depth_shock = np.random.lognormal(np.log(1e4), 0.5, n_shock)
impacts_shock = np.random.lognormal(np.log(50), 0.5, n_shock)

all_spreads = np.concatenate([spread_normal, spread_shock])
all_depths = np.concatenate([depth_normal, depth_shock])
all_impacts = np.concatenate([impacts_normal, impacts_shock])
all_ofi = np.random.uniform(-1, 1, n_normal + n_shock)

ts = pd.date_range('2004-01-15 09:30:00', periods=n_normal+n_shock, freq='1s') # Corrected: Added '='

detector = AdaptiveLiquidShockDetector(lookback_window=200) # Corrected typo: lookboack_window -> lookback_window
shock_events = []

for i, t in enumerate(ts):
  event = detector.update(
      timestamp=t,
      spread_bps=all_spreads[i],
      depth=all_depths[i],
      ofi=all_ofi[i],
      price_impact=all_impacts[i],
  )
  if event:
    shock_events.append(event)

summary = detector.shock_summary()
if not summary.empty:
  print(f"\nDetected {len(summary)} liquidity Shock Observations")
  print(f"CRITICAL EVENTS: {(summary['severity']=='CRITICAL').sum()}")
  print(f"WARNING events: {(summary['severity']=='WARNING').sum()}")
  print(f"First Shock detected at: {summary['timestamp'].iloc[0]}")
  print(f"Expected first shock at: {ts[n_normal]}")

