# -*- coding: utf-8 -*-
"""Market Resiliency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.optimize import curve_fit
from scipy.stats import pearsonr
import warnings

def measure_spread_recovery(
    quotes: pd.DataFrame,
    large_trades: pd.DataFrame,
    large_trade_threshold_pct: float = 95.0,
    recovery_window_ms: int = 60_000,
    n_lags: int = 50
) -> dict:
    quotes = quotes.sort_values('timestamp').copy()
    quotes['spread_bps'] = (quotes['ask'] - quotes['bid']) / quotes['mid'] * 10_000

    threshold = np.percentile(large_trades['notional'].abs(), large_trade_threshold_pct)
    large = large_trades[large_trades['notional'].abs() >= threshold]

    print(f"Large trade threshold: ${threshold/1e6:.2f}M")
    print(f"Number of large trade events: {len(large)}")

    lag_ms = np.linspace(0, recovery_window_ms, n_lags)
    lag_labels = [pd.Timedelta(milliseconds=int(lag_val)) for lag_val in lag_ms]

    recovery_paths = []
    pre_trade_spreads = []

    for _, trade in large.iterrows():
      t = trade['timestamp']

      pre = quotes[quotes['timestamp'] <= t]
      if len(pre) < 5: continue
      spread_pre = pre['spread_bps'].iloc[-5:].mean()
      if spread_pre <= 0: continue

      path = []
      for lag in lag_labels:
        window = quotes[(quotes['timestamp'] > t) & (quotes['timestamp'] <= t + lag)]
        if window.empty:
          spread_at_lag = np.nan
        else:
          spread_at_lag = window['spread_bps'].iloc[-1]

        path.append(spread_at_lag / spread_pre)

      recovery_paths.append(path)
      pre_trade_spreads.append(pre_trade_spreads)

    recovery_paths = np.array(recovery_paths)
    pre_trade_spreads = np.array(pre_trade_spreads)

    if not recovery_paths:
      return {}

    recovery_matrix = np.array(recovery_paths)
    mean_recovery = np.nanmean(recovery_matrix, axis=0)
    std_recovery = np.nanstd(recovery_matrix, axis=0)

    def exp_recovery(t_ms, A, kappa):
      return 1 + A * np.exp(-kappa * t_ms / 1000)

    def power_recovery(t_ms, A, t0_ms, beta):
      return 1 + A * (t0_ms / (t0_ms + t_ms + 1e-3)) ** beta

    valid = ~np.isnan(mean_recovery)
    t_vals = lag_ms[valid]
    y_vals = mean_recovery[valid]

    results = {
        'lag_ms': lag_ms,
        'mean_recovery': mean_recovery,
        'std_recovery': std_recovery,
        'n_events': len(recovery_paths),
        'mean_pre_spread': np.mean(pre_trade_spreads),
    }

    try:
      popt_exp, pcov_exp = curve_fit(
          exp_recovery, t_vals, y_vals,
          p0=[y_vals[0] - 1, 0.5],
          bounds=([0, 0], [10, 100]),
          maxfev=5000,
      )
      A_exp, kappa_exp = popt_exp
      half_life_s = np.log(2) / kappa_exp if kappa_exp > 0 else np.inf
      results['exp_model'] = {
          'A': A_exp,
          'kappa': kappa_exp,
          'half_life_seconds': half_life_s,
      }

      print(f"\nExponential Recovery Model:")
      print(f" Kappa = {kappa_exp:.4f} /s")
      print(f" Half-life = {half_life_s:.2f} seconds")
      print(f" Initial excess spread = {A_exp:.4f}x pre-trade spread")

    except Exception as e:
      print(f"Error fitting exponential model: {e}")

    try:
      popt_p1, _ = curve_fit(
          power_recovery, t_vals[1: ], y_vals[1: ],
          p0=[y_vals[0] - 1, 1000, 0.5],
          bounds=([0, 10, 0.01], [10, 1e6, 2]),
          maxfev=5000,
      )
      A_p1, t0_p1, beta_p1 = popt_p1
      results['power_law_model'] = {'A': A_p1, 't0_ms': t0_p1, 'beta': beta_p1,}

      print(f"\nPower-Law Recovery Models:")
      print(f" Beta (decay exponent) = {beta_p1:.4f}")
      print(f" t0 = {t0_p1:.0f}ms")
    except Exception as e:
      print(f"Power-law fit failed: {e}")

    return results

print("Market Resiliency Framework Ready")
print(f"Key models: Exponential recovery(OU) and power-law recovery")
print(f"Key metric: Resiliency half-life(how fast spread returns to normal")

