# -*- coding: utf-8 -*-
"""Liquidity Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.api as sm
from typing import Optional, Dict, Union

class LiquidityMetricsEngine:
  def __init__(self, symbol: str = ""):
    self.symbol = symbol
    self._metrics_cache = {}


  @staticmethod
  def amihud_illiquidity(
      returns: pd.Series,
      dollar_volume: pd.Series,
      window: Optional[int] = None,) -> Union[pd.Series, float]:
      illiq = returns.abs() / dollar_volume
      if window:
        return illiq.rolling(window).mean() * 1e6
      return illiq.mean() * 1e6

  @staticmethod
  def roll_spread(prices: pd.Series, n_days: int = 60) -> float:
    dP = prices.diff().dropna()
    cov = dP.autocorr(lag=1) * dP.var()

    if cov < 0:
      return 2 * np.sqrt(-cov)
    else:
      return np.nan

  @staticmethod
  def corwin_schultz_spread(high: pd.Series, low: pd.Series) -> pd.Series:
    beta = (np.log(high / low) ** 2).rolling(2).sum()
    h_hl = np.log(pd.concat([high, high.shift(-1)], axis=1).max(axis=1))
    l_hl = np.log(pd.concat([low, low.shift(-1)], axis=1).min(axis=1))
    gamma = (h_hl - l_hl) ** 2

    c1 = np.sqrt(2) - 1
    c2 = 3 - 2 * np.sqrt(2)
    alpha = (np.sqrt(2*beta) - np.sqrt(beta)) / c2 - np.sqrt(gamma / c2)
    spread = 2 * (np.exp(alpha) - 1) / (1 + np.exp(alpha))
    spread = spread.clip(lower=0)
    return spread * 10_000

  @staticmethod
  def pastor_stambugh_gamma(
      returns: pd.Series,
      signed_volume: pd.Series,
      window: int = 60,) -> pd.Series:
      gamma = []
      dates = []
      for i in range(window, len(returns)):
        sub_ret = returns.iloc[i-window:i].values
        sub_vol = signed_volume.iloc[i-window:i].values
        r_t = sub_ret[:-1]
        r_tp1 = sub_ret[:-1]
        sv_t = np.sign(r_t) * np.abs(sub_vol[:-1])

        X = np.column_stack([np.ones(len(r_t)), r_t, sv_t])

        try:
          model = sm.OLS(r_tp1, X).fit()
          gamma.append(model.params[2])
        except Exception:
          gamma.append(np.nan)
        dates.append(returns.index[i])

      return pd.Series(gamma, index=dates, name='PS_gamma')

  @staticmethod
  def order_book_imbalance(
      bid_sizes: np.ndarray,
      ask_sizes: np.ndarray,
      depth_levels: int = 5,) -> float:
      bid = bid_sizes[:depth_levels].sum()
      ask = ask_sizes[:depth_levels].sum()
      total = bid + ask
      if total == 0:
        return 0.0
      return (bid - ask) / total

  @staticmethod
  def xlm(
      bid_prices: np.ndarray,
      bid_sizes: np.ndarray,
      ask_sizes: np.ndarray,
      ask_prices: np.ndarray,
      trade_size_notional: float,
      mid_price: float = 100.0,) -> float:

      def fill_cost(prices, sizes, target_notional, side='buy'):
        filled = 0.0
        cost = 0.0
        for p, q in zip(prices, sizes):
          notional_at_level = p * q
          if filled + notional_at_level >= target_notional:
            remaining = target_notional - filled
            cost += remaining
            filled += remaining
            break
          else:
            cost += notional_at_level
            filled += notional_at_level

        if filled < target_notional:
          return np.nan
        return cost / target_notional

      ask_fill = fill_cost(ask_prices, ask_sizes, trade_size_notional, 'buy')
      bid_fill = fill_cost(bid_prices[::-1], bid_sizes[::-1], trade_size_notional, 'sell')

      if np.isnan(ask_fill) or np.isnan(bid_fill):
        return np.nan

      round_trip_cost_bps = (ask_fill - bid_fill) / mid_price * 10_000
      return round_trip_cost_bps

  def composite_liquidity_score(
      self,
      amihud: float,
      eff_spread_bps: float,
      depth_mm: float,
      turnover: float,
      roll_spread_bps: float,) -> dict:

      scores = {}

      scores['tightness'] = max(0, 100 - eff_spread_bps * 10)
      scores['depth'] = min(100, depth_mm * 10)
      scores['turnover'] = min(100, turnover * 100)

      composite = np.nanmean(list(scores.values()))

      return{
          'composite_score': composite,
          'components': scores,
          'classification': (
              'Very Liquid' if composite > 80 else
              'Liquid' if composite > 60 else
              'Moderate' if composite > 40 else
              'Illiquid' if composite > 20 else
              'Very Illiquid'
          )
      }

engine = LiquidityMetricsEngine("AAPL")

np.random.seed(12)
n_days = 252
returns = pd.Series(np.random.normal(0, 0.015, n_days), index=pd.bdate_range('2024-01-01', periods=n_days, freq='B'))
dollar_vol = pd.Series(np.random.lognormal(np.log(5e8), 0.5, n_days), index=returns.index)

high = pd.Series(100 * np.exp(np.cumsum(returns)) * (1 + np.abs(np.random.normal(0, 0.005, n_days))), index=returns.index)
low = high * (1 - np.abs(np.random.normal(0, 0.008, n_days)))

illiq = LiquidityMetricsEngine.amihud_illiquidity(returns, dollar_vol)
cs_spread = LiquidityMetricsEngine.corwin_schultz_spread(high, low)

print("=" * 50)
print("LIQUIDITY METRICS DEMONSTRATION")
print("=" * 50)
print(f"AMIHUD LIQUIDITY(mean): {illiq:.6f}")
print(f"CORWIN-SCHULTZ SPREAD: {cs_spread.mean():.2f} bps")
print(f"Roll Spread: {LiquidityMetricsEngine.roll_spread(high):.4f}")

comp = engine.composite_liquidity_score(
    amihud=illiq, eff_spread_bps=3.0, depth_mm=2.0,
    turnover=0.01, roll_spread_bps=5.0)

print(f"\nComposite Liquidity Score: {comp['composite_score']:.1f}/100")
print(f"Classification: {comp['classification']}")

