# -*- coding: utf-8 -*-
"""Spread Capture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd

def compute_markouts(trade: pd.DataFrame, mid_price_series: pd.Series, horizon_sec: list) -> pd.DataFrame:
  trades = trade.copy()
  trades['effective_spread'] = 2 * trades['side'] * (trades['mid_at_trade'] - trades['price']) * -1

  for h in horizon_sec:
    future_mids = []
    for ts in trades['timestamp']:
      target_ts = ts + pd.Timedelta(seconds=h)
      idx = mid_price_series.index.asof(target_ts)
      future_mids.append(mid_price_series.loc[idx] if pd.notna(idx) else np.nan)

    trades[f"future_mid_{h}s"] = future_mids
    trades[f"realized_spread_{h}s"] = 2 * trades['side'] * (trades[f"future_mid_{h}s"] - trades['price']) * -1

  return trades

def summarize_markout_curve(trades: pd.DataFrame, horizon_sec: list) -> pd.Series:
  cols = [f"realized_spread_{h}s" for h in horizon_sec]
  return trades[cols].mean()

np.random.seed(12)
n_trades = 5000
timestamps = pd.to_datetime("2025-01-02 09:30:00") + pd.to_timedelta(np.cumsum(np.random.exponential(scale=0.5, size=n_trades)), unit='s')
mid0 = 100.0
mid_path = mid0 + np.cumsum(np.random.normal(0, 0.001, size=200_000))
mid_series = pd.Series(mid_path, index=pd.to_datetime("2025-01-02 09:30:00") + pd.to_timedelta(np.arange(200_000) * 0.05, unit='s'))

side = np.random.choice([1, -1], size=n_trades)
mid_at_trade = mid_series.reindex(timestamps, method='ffill').values
price = mid_at_trade - side * 0.005

trades = pd.DataFrame({'timestamp': timestamps, 'price': price, 'side': side, 'mid_at_trade': mid_at_trade})

trades_with_markouts = compute_markouts(trades, mid_series, horizon_sec=[1, 10, 60])
print(summarize_markout_curve(trades_with_markouts,[1, 10, 60]))

