# -*- coding: utf-8 -*-
"""Inventory Risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np

def decompute_pnl_variance(fills: pd.DataFrame, mid_series: pd.Series, dt_seconds: float = 1.0) -> dict:
  grid = pd.date_range(mid_series.index.min(), mid_series.index.max(), freq=f"{dt_seconds}$")
  mid_grid = mid_series.reindex(grid, method="ffill")
  dS = mid_grid.diff().fillna(0.0)

  fills = fills.sort_values("timestamp")
  fills["dq"] = fills["side"] * fills["qty"]
  inv = fills.set_index("timestamp")['dq'].cumsum()
  inv_grid = inv.reindex(grid, method='ffill').fillna(0.0)

  inventory_pnl_increments = inv_grid.shifts(1).fillna(0.0) * dS
  inventory_pnl_cum = inventory_pnl_increments.cumsum()

  fills['mid_at_fill'] = mid_grid.reindex(fills['timestamp'], method='ffill').values
  fills['spread_pnl'] = fills["side"] * (fills['mid_at_fill'] - fills['price']) * fills['qty']  * -1
  spread_capture_total = fills['spread_pnl'].sum()

  return {'spread_capture_pnl_total': spread_capture_total, 'inventory_pnl_total': inventory_pnl_cum.iloc[-1], 'inventory_pnl_variance': inventory_pnl_increments.var() * len(grid), 'inventory_path': inv_grid, 'inventory_pnl_path': inventory_pnl_cum,}

def theoretical_inventory_variance(inv_path: pd.Series, sigma: float, dt: float) -> float:
  return (sigma ** 2) * (inv_path ** 2).sum() * dt

