# -*- coding: utf-8 -*-
"""Fill Probabilities.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.optimize import curve_fit

def estimate_fill_intensity_curve(lob_snapshot: pd.DataFrame, trades: pd.DataFrame, distance_bins: np.ndarray, window_seconds: float) -> pd.DataFrame:
  results = []
  for delta in distance_bins:
    fill_count = 0
    for _, snap in lob_snapshot.iterrows():
      hypothetical_ask = snap["mid_price"] + delta

      window_trades = trades[(trades['timestamp'] >= snap["timestamp"]) & (trades['timestamp'] < snap["timestamp"] + pd.Timedelta(seconds=window_seconds)) & (trades['side'] == "buy") & (trades["price"] >= hypothetical_ask)]
      fill_count += len(window_trades)

    total_exposure_time = len(lob_snapshot) * window_seconds
    lam_hat = fill_count / total_exposure_time if total_exposure_time > 0 else np.nan
    results.append({'delta': delta, "lambda_hat": lam_hat})
  return pd.DataFrame(results)

def fit_exponential_intensity(delta_lambda_df: pd.DataFrame):
  def model(delta, A, kappa):
    return A * np.exp(-kappa * delta)

  valid = delta_lambda_df.dropna()
  popt, pcov = curve_fit(model, valid['delta'], valid['lambda_hat'], p0=[valid["lambda_hat"].max(), 1.0], maxfev=10000)
  A_hat, kappa_hat = popt
  return A_hat, kappa_hat, pcov

np.random.seed(12)
n_snaps = 2000
timestamps = pd.date_range("2025-01-02 09:30:00", periods=n_snaps, freq="1s")
mid_prices = 100 + np.cumsum(np.random.normal(0, 0.005, n_snaps))
lob_snapshots = pd.DataFrame({'timestamp': timestamps, "mid_price": mid_prices})[::20]

n_trades = 8000
trade_times = pd.to_datetime("2025-01-02 09:30:00") + pd.to_timedelta(np.cumsum(np.random.exponential(0.25, n_trades)), unit='s')
true_kappa = 8.0
walk_depths = np.random.exponential(1 / true_kappa, n_trades)
trade_mid = np.interp(trade_times.astype(np.int64), timestamps.astype(np.int64), mid_prices)
side = np.random.choice(["buy", "sell"], n_trades)
price = np.where(side == "buy", trade_mid + walk_depths, trade_mid - walk_depths)
trades = pd.DataFrame({'timestamp': trade_times, "side": side, "price": price})
distance_bins = np.linspace(0.01,0.10, 10)
curve = estimate_fill_intensity_curve(lob_snapshots, trades, distance_bins, window_seconds=1.0)
A_hat, kappa_hat, _ = fit_exponential_intensity(curve)
print(f"Estimated A = {A_hat:.3f}, kappa = {kappa_hat:.3f} (true kappa) = {true_kappa}")

