# -*- coding: utf-8 -*-
"""Quote Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from dataclasses import dataclass

@dataclass
class ASParams:
  sigma: float
  gamma: float
  kappa: float
  A: float
  T: float

def reservation_price(S: float, q: int, t: float, p: ASParams) -> float:
  return S - q * p.gamma * p.sigma**2 * (p.T - t)

def optimal_total_spread(t: float, p:ASParams) -> float:
  risk_term = p.gamma * p.sigma**2 * (p.T - t)
  liquidity_term = (2.0 / p.gamma) * np.log(1.0 + p.gamma / p.kappa)
  return risk_term + liquidity_term

def optimal_quotes(S: float, q: int, t: float, p :ASParams) -> dict:
  r = reservation_price(S, q, t, p)
  total_spread = optimal_total_spread(t, p)
  half_spread = total_spread / 2.0

  return {
      "mid": S, "reservation": r,
      "total_spread": total_spread, "half_spread": half_spread,
      "bid": r - half_spread, "ask": r + half_spread,
      "inventory_skew": S - r,
  }

def simulate_as_session(p: ASParams, n_steps: int = 2000, seed: int = 12):
  rng = np.random.default_rng(seed)
  dt = p.T / n_steps

  S = 100.0
  q = 0
  X = 0.0

  times, mids, invs, cash, bids, asks = [], [], [], [], [], []

  for i in range(n_steps):
    t = i * dt
    quotes = optimal_quotes(S, q, t, p)
    delta_a = quotes["ask"] - S
    delta_b = S - quotes["bid"]

    lam_a = p.A * np.exp(-p.kappa * max(delta_a, 0.0))
    lam_b = p.A * np.exp(-p.kappa * max(delta_b, 0.0))

    if rng.uniform() < lam_a * dt:
      X += quotes['ask']
      q -= 1
    if rng.uniform() < lam_b * dt:
      X -= quotes['bid']
      q += 1

    times.append(t)
    mids.append(S)
    invs.append(q)
    cash.append(X)
    bids.append(quotes['bid'])
    asks.append(quotes['ask'])

    S += p.sigma * np.sqrt(dt) * rng.standard_normal()

  terminal_pnl = X + q * S
  return {"t": np.array(times), "mid": np.array(mids), "inventory": np.array(invs), "cash": np.array(times), "bid": np.array(bids), "ask": np.array(asks), "terminal_pnl": terminal_pnl,}

if __name__ == "__main__":
  params = ASParams(sigma=2.0, gamma=0.1, kappa=1.5, A=140.0, T=1.0)

  q1 = optimal_quotes(S=100.0, q=30, t=0.75, p=params)
  print("Worked Example 7.8.1 Check:")
  print(f"Reservation price: {q1['reservation']:.3f}")
  print(f"Bid: {q1['bid']:.3f} Ask: {q1['ask']:.3f}")

  pnls = [simulate_as_session(params, seed=s)['terminal_pnl'] for s in range(500)]
  pnls = np.array(pnls)
  print(f"\nMonte Carlo (500 Seesions): mean PnL = {pnls.mean():.2f}, " f"std = {pnls.std():.2f}, sharpe-like ratio = {pnls.mean()/pnls.std():3f}")

