# -*- coding: utf-8 -*-
"""Temporary Impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def walk_the_book(order_size, mid_price, levels):
  remaining = order_size
  cost = 0.0
  filled = 0
  for price, size in levels:
    take = min(remaining, size)
    cost += take * price
    filled += take
    remaining -= take
    if remaining == 0:
      break
  if filled == 0:
    return cost, filled

  avg_price = cost / filled
  impact_bps = (avg_price - mid_price) / mid_price * 1e4
  return avg_price, impact_bps, filled

levels = [(100.02, 500), (100.04, 800), (100.06, 1200), (100.08, 1500)]
avg_p, impact_bps, filled = walk_the_book(2000, 100.00, levels)
print(f"avg exec price: {avg_p:.4f}, Temporary impact: {impact_bps:.2f} bps, Filled:{filled}")

