# -*- coding: utf-8 -*-
"""Institutional Impact Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import matplotlib.pyplot as plt

def institutional_cost_model(Q, V, sigma_daily, spread_bps, POV, Y=0.5, perm_frac=0.5, kappa_T=0.3):
  spread_cost = 0.5 * spread_bps
  total_impact = 1e4 * Y * sigma_daily * np.sqrt(Q/V)
  perm_impact = perm_frac * total_impact
  temp_impact = (1 - perm_frac) * total_impact

  timing_risk_std = 1e4 * sigma_daily * np.sqrt(Q/V)* np.sqrt(kappa_T) * 0.5

  total = spread_cost + total_impact
  return {'spread_cost_bps': spread_cost,
          'temp_cost_bps': temp_impact,
          'perm_impact_bps': perm_impact,
          'timing_risk_bps': timing_risk_std,
          'expected_total_bps': total,}

result = institutional_cost_model(Q=50e6, V=400e6, sigma_daily=0.02, spread_bps=8, POV=0.10)
for k, v in result.items():
  print(f"{k}: {v:.2f}")

labels = ['spread', 'Temp.\nImpact', 'Perm.\nImpact', 'Timing\nRisk(1std)']
values = [result['spread_cost_bps'], result['temp_cost_bps'], result['perm_impact_bps'], result['timing_risk_bps']]
plt.bar(labels, values, color=['r', 'g', 'b', 'c'])
plt.ylabel('Cost (bps of notional)')
plt.title('Institutional Cost Decomposition: $50M Order')
plt.tight_layout()
plt.savefig('cost_decompostion.pdf')
plt.show()

