# -*- coding: utf-8 -*-
"""Permanent Impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

np.random.seed(12)
n = 5000
signed_vol = np.random.normal(0, 1e5, n)
true_gamma = 2.3e-7

price_change = true_gamma * signed_vol + np.random.normal(0, 0.01, n)

X = signed_vol.reshape(-1, 1)
gamma_hat = np.linalg.lstsq(X, price_change, rcond=None)[0][0]
print(f"True gamam: {true_gamma:.3e}, Estimated gamma: {gamma_hat:.3e}")

