# -*- coding: utf-8 -*-
"""Price Response Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def simulate_propagator(n_trades=20000, beta=0.6, gamma_corr=0.3, seed=42):
  rng = np.random.default_rng(seed)
  raw = rng.standard_normal((n_trades))

  fgn = np.cumsum(raw) * (np.arange(1, n_trades+1)** (-gamma_corr/2))

  eps = np.sign(np.diff(fgn, prepend=fgn[0]))
  eps[eps == 0] = 1

  lags = np.arange(1, 201)
  G = lags.astype(float) ** (-beta)

  price = np.zeros(n_trades)
  for n in range(1, n_trades):
    m_start = max(0, n-200)
    contrib = G[:n-m_start][::-1] @ eps[m_start:n]
    price[n] = price[n-1] * 0 + contrib
  return eps, price, lags, G

def response_function(eps, price, max_lag=150):
  n = len(price)
  R = np.zeros(max_lag)
  for ell in range(1, max_lag+1):
    R[ell-1] = np.mean((price[ell:n] - price[0:n-ell]) * eps[0:n-ell])
  return R

eps, price, lags, G = simulate_propagator()
R = response_function(eps, price)
print(f"Bare propagator G(1..5):", G[:5])
print("Dressed response R(1..5):", R[:5])

