# -*- coding: utf-8 -*-
"""Price Response Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def kyle_monte_carlo(sigma_v=2.0, sigma_u=1.0, n_sims=200000, seed=12):
  rng = np.random.default_rng(seed)
  lam_theory = 0.5 * sigma_v / sigma_u
  beta_theory = sigma_u / sigma_v

  v = rng.normal(0, sigma_v, n_sims)
  u = rng.normal(0, sigma_u, n_sims)
  x = beta_theory * v

  y = x + u
  p = lam_theory * y

  lam_hat = np.cov(y, v)[0, 1] / np.var(y)
  profit = (v - p) * x
  return lam_theory, lam_hat, profit.mean(), 0.5*sigma_u*sigma_v

lam_theory , lam_hat, profit_mc, profit_theory = kyle_monte_carlo()
print(f"Lmbda(theory): {lam_theory:.4f}")
print(f"Lmbda (regression): {lam_hat:.4f}")
print(f"Informed profit (MC): {profit_mc:.4f}")
print(f"Informed profit (thoery): {profit_theory:.4f}")

