# -*- coding: utf-8 -*-
"""Almren-Chriss Framework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def ac_trajectory(kappa, X0, T, t_grid):
  if kappa == 0:
    return X0 * (1- t_grid / T)
  return X0 * np.sinh(kappa * (T - t_grid)) / np.sinh(kappa*T)

def ac_via_guadratic_program(X0, T, N, eta, lam, sigma):
  tau = T / N
  kappa2_tau2 = lam * sigma**2 * tau**2 / eta
  A = np.zeros((N-1, N-1))
  for i in range(N-1):
    A[i, i] = 2 + kappa2_tau2
    if i > 0: A[i, i-1] = -1
    if i < N - 2: A[i, i+1] = -1
  b = np.zeros(N-1)
  b[0] = X0
  x_interior = np.linalg.solve(A, b)
  x_full = np.concatenate(([X0], x_interior, [0]))
  return x_full

X0, T, sigma, eta = 1.0, 1.0, 0.3, 0.5
for lam_r in [0.0, 1.0, 5.0]:
  kappa = np.sqrt(lam_r * sigma**2 / eta) if lam_r > 0 else 0.0
  t_grid = np.linspace(0, T, 11)
  x_closed = ac_trajectory(kappa, X0, T, t_grid)
  x_numeric = ac_via_guadratic_program(X0, T, 10, eta, lam_r, sigma)
  print(f"lambda=(lam_r): max | closed-form - numeric QP | = {np.max(np.abs(x_closed-x_numeric)):.2e}")

