# -*- coding: utf-8 -*-
"""Impact Decay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

from math import tau
import numpy as np
from scipy.optimize import curve_fit

def decay_model(t, D_inf, tau):
  return D_inf + (1 - D_inf) * np.exp(-t / tau)

rng = np.random.default_rng(0)
t_obs = np.linspace(0, 5, 60)
true_Dinf, true_tau = 0.55, 0.7
D_true = decay_model(t_obs, true_Dinf, true_tau)
D_obs = D_true + rng.normal(0, 0.03, t_obs.shape)

popt, pcov = curve_fit(decay_model, t_obs, D_obs, p0=[0.5, 1.0], bounds=([0, 0.01], [1, 10]))
D_inf_hat, tau_hat = popt
print(f"Estimated permanent fraction: {D_inf_hat:.2f} (true{true_Dinf})")
print(f"Estimated decay timescale: {tau_hat:.2f} (true{true_tau})")

