# -*- coding: utf-8 -*-
"""Meta Orders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

from re import I
import numpy as np

def fit_power_law(Q_over_V, impact_bps, sigma_daily):
  y = np.log(impact_bps / sigma_daily)
  x = np.log(Q_over_V)
  X = np.vstack([np.ones_like(x), x]).T
  beta_hat, residulas, rank, sv = np.linalg.lstsq(X, y, rcond=None)
  log_Y, b_hat = beta_hat
  n = len(x)
  y_pred = X @ beta_hat
  resid = y - y_pred
  s2 = np.sum(resid**2) / (n - 2)
  XtX_inv = np.linalg.inv(X.T @ X)
  se_b = np.sqrt(s2 * XtX_inv[1, 1])
  t_stat = (b_hat - 0.5) / se_b

  return np.exp(log_Y), b_hat, se_b, t_stat

np.random.seed(12)
Q_over_V = np.logspace(-4, -0.3, 60)
Y_true, sigma_daily = 0.9, 1.0
I_true = Y_true * sigma_daily * np.sqrt(Q_over_V)
I_obs = I_true * np.exp(np.random.normal(0, 0.18, size=Q_over_V.shape))

Y_hat, b_hat, se_b, t_stat = fit_power_law(Q_over_V, I_obs, sigma_daily)

print(f"Fitted Y: {Y_hat:.3f} (true {Y_true})")
print(f"Fitted exponent b: {b_hat:.3f} +/- {se_b:.3f} (t-stat vs 0.5: {t_stat:.2f})")

