# -*- coding: utf-8 -*-
"""Execution Risk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def simulate_ac_shortfall(X0, T, N, sigma, eta, kappa, n_paths=50000, seed=12):
  rng = np.random.default_rng(seed)
  tau = T / N
  t_grid = np.linspace(0, T, N+1)
  if kappa < 1e-8:
    x = X0 * (1- t_grid/T)
  else:
    x = X0 * np.sinh(kappa*(T - t_grid)) / np.sinh(kappa*T)
  n_trades = -np.diff(x)

  costs = np.zeros(n_paths)
  for p in range(n_paths):
    xi = rng.standard_normal(N)
    price = np.zeros(N+1)
    for k in range(1, N+1):
      price[k] = price[k-1] + sigma * np.sqrt(tau) * xi[k-1]
    temp_impact_cost = np.sum(eta * (n_trades/tau) * n_trades)
    risk_pl = np.sum(price[:-1] * n_trades)

    costs[p] = temp_impact_cost - risk_pl
  return costs

costs = simulate_ac_shortfall(X0=1.0, T=1.0, N=50, sigma=0.3, eta=0.05, kappa=2.0)
mean_cost = costs.mean()
var_cost = costs.var()
VaR_95 = np.percentile(costs, 95)
CVar_95 = costs[costs >= VaR_95].mean()
print(f"Mean cost: {mean_cost:.5f}, \nVar: {var_cost:.5f}")
print(f"VaR 95%: {VaR_95:.5f}, \nCVaR 95%: {CVar_95:.5f}")

