# -*- coding: utf-8 -*-
"""Impact Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import TimeSeriesSplit

def sqrt_lax_baseline(Q, V, sigma, Y=0.5):
  return Y * sigma * np.sqrt(Q/V)

def build_features(df):
  feats = pd.DataFrame({'participation': df['Q'] / df['V'], 'log_participation': np.log(df['Q'] / df['V']).clip(-10, 10), 'rel_spread': df['spread'] / df['price'], 'sigma': df['sigma'], 'adv_zscore': (df['V'] - df['adv_mean']) / df['adv_std'], 'imbalance': df['imbalance'], 'time_of_day': df['tod'],})
  return feats

def fit_hybrid_model(df, Y0=0.5):
  baseline = sqrt_lax_baseline(df['Q'], df['V'], df['sigma'], Y0)
  residual = df['realized_impact'] - baseline
  X = build_features(df)

  tscv = TimeSeriesSplit(n_splits=5)
  oos_errors_hybrid, oos_errors_baseline = [], []

  for train_idx, test_idx in tscv.split(X):
    model = GradientBoostingRegressor(n_estimators=200, max_depth=3, learning_rate=0.05, subsample=0.8)
    model.fit(X.iloc[train_idx], residual.iloc[train_idx])
    resid_pred = model.predict(X.iloc[test_idx])
    hybrid_pred = baseline.iloc[test_idx] + resid_pred

    oos_errors_hybrid.append(np.mean((hybrid_pred - df['realized_impact'].iloc[test_idx])**2))
    oos_errors_baseline.append(np.mean((baseline.iloc[test_idx] - df['realized_impact'].iloc[test_idx])**2))

  print(f"Baseline MSE (sqrt-law only): {np.mean(oos_errors_baseline):.6f}")
  print(f"Hybrid MSE (sqrt-law + ML residual): {np.mean(oos_errors_hybrid):.6f}")
  return model

