# -*- coding: utf-8 -*-
"""LOB Data Structure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

from dataclasses import dataclass, field
from collections import deque
from sortedcontainers import SortedDict
from typing import Optional, Deque, Dict, List
import time

@dataclass
class Order:
    order_id: int
    price: float
    quantity: int
    side: str
    order_type: str
    timestamp: int
    remaining: int = field(init=False)
    participant_id: str = ''

    def __post_init__(self):
        self.remaining = self.quantity

    @property
    def is_filled(self) -> bool:
        return self.remaining <= 0

@dataclass
class PriceLevel:
    price: float
    orders: Deque[Order] = field(default_factory=deque)

    @property
    def total_quantity(self) -> int:
        return sum(o.remaining for o in self.orders)

    @property
    def order_count(self) -> int:
        return len(self.orders)

class LimitOrderBook:
    def __init__(self, instrument: str, tick_size: float = 0.01):
        self.instrument = instrument
        self.tick_size = tick_size
        self.bids: SortedDict[float, PriceLevel] = SortedDict()
        self.asks: SortedDict[float, PriceLevel] = SortedDict()
        self.orders: Dict[int, Order] = {}

    @property
    def best_bid(self) -> Optional[float]:
        if not self.bids:
            return None
        return -next(iter(self.bids))

    @property
    def best_ask(self) -> Optional[float]:
        if not self.asks:
            return None
        return next(iter(self.asks))

    @property
    def mid_price(self) -> Optional[float]:
        if self.best_bid is None or self.best_ask is None:
            return None
        return (self.best_bid + self.best_ask) / 2.0

    @property
    def spread(self) -> Optional[float]:
        if self.best_bid is None or self.best_ask is None:
            return None
        return self.best_ask - self.best_bid

    def get_depth(self, levels: int = 5):
        bid_levels, ask_levels = [], []
        for neg_p, lvl in list(self.bids.items())[:levels]:
            bid_levels.append((-neg_p, lvl.total_quantity))
        for p, lvl in list(self.asks.items())[:levels]:
            ask_levels.append((p, lvl.total_quantity))
        return bid_levels, ask_levels

    def __repr__(self):
        bids, asks = self.get_depth(3)
        lines = [f"=== LOB: {self.instrument} ==="]
        for p, q in reversed(asks):
            lines.append(f" ASK {p: >10.4f} {q: >8}")
        lines.append(f" --- Spread: {self.spread if self.spread is not None else 0.0:.4f} ---")
        for p, q in bids:
            lines.append(f" BID {p: >10.4f} {q: >8}")
        return '\n'.join(lines)

