# -*- coding: utf-8 -*-
"""Queue Position Tracking and Fill Probability Estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

from dataclasses import dataclass, field
from collections import deque
from sortedcontainers import SortedDict
from typing import Optional, Deque, Dict, List
import time

@dataclass
class Order:
    order_id: int
    price: float
    quantity: int
    side: str
    order_type: str
    timestamp: int
    remaining: int = field(init=False)
    participant_id: str = ''

    def __post_init__(self):
        self.remaining = self.quantity

    @property
    def is_filled(self) -> bool:
        return self.remaining <= 0

@dataclass
class PriceLevel:
    price: float
    orders: Deque[Order] = field(default_factory=deque)

    @property
    def total_quantity(self) -> int:
        return sum(o.remaining for o in self.orders)

    @property
    def order_count(self) -> int:
        return len(self.orders)

class LimitOrderBook:
    def __init__(self, instrument: str, tick_size: float = 0.01):
        self.instrument = instrument
        self.tick_size = tick_size
        self.bids: SortedDict[float, PriceLevel] = SortedDict()
        self.asks: SortedDict[float, PriceLevel] = SortedDict()
        self.orders: Dict[int, Order] = {}

    @property
    def best_bid(self) -> Optional[float]:
        if not self.bids:
            return None
        return -next(iter(self.bids))

    @property
    def best_ask(self) -> Optional[float]:
        if not self.asks:
            return None
        return next(iter(self.asks))

    @property
    def mid_price(self) -> Optional[float]:
        if self.best_bid is None or self.best_ask is None:
            return None
        return (self.best_bid + self.best_ask) / 2.0

    @property
    def spread(self) -> Optional[float]:
        if self.best_bid is None or self.best_ask is None:
            return None
        return self.best_ask - self.best_bid

    def get_depth(self, levels: int = 5):
        bid_levels, ask_levels = [], []
        for neg_p, lvl in list(self.bids.items())[:levels]:
            bid_levels.append((-neg_p, lvl.total_quantity))
        for p, lvl in list(self.asks.items())[:levels]:
            ask_levels.append((p, lvl.total_quantity))
        return bid_levels, ask_levels

    def __repr__(self):
        bids, asks = self.get_depth(3)
        lines = [f"=== LOB: {self.instrument} ==="]
        for p, q in reversed(asks):
            lines.append(f" ASK {p: >10.4f} {q: >8}")
        lines.append(f" --- Spread: {self.spread if self.spread is not None else 0.0:.4f} ---")
        for p, q in bids:
            lines.append(f" BID {p: >10.4f} {q: >8}")
        return '\n'.join(lines)

from dataclasses import dataclass
from typing import List, Tuple, Optional
from enum import Enum
import heapq

class Side(Enum):
    BUY = 'BUY'
    SELL = 'SELL'

class OrderType(Enum):
    LIMIT = 'LIMIT'
    MARKET = 'MARKET'
    IOC = 'IOC'
    FOK = 'FOK'
    ICEBERG = 'ICEBERG'

@dataclass
class Fill:
    aggressive_id: int
    passive_id: int
    price: float
    quantity: int
    timestamp: int

class MatchingEngine:
    def __init__(self, instrument: str, tick_size: float = 0.01):
        self.instrument = instrument
        self.tick_size = tick_size
        self.lob = LimitOrderBook(instrument, tick_size)
        self.order_seq = 0
        self.fills: List[Fill] = []
        self.time_ns: int = 0

    def _next_id(self) -> int:
        self.order_seq += 1
        return self.order_seq

    def _now(self) -> int:
        return self.time_ns

    def submit(self, side: Side, price: Optional[float], qty: int,
               order_type: OrderType = OrderType.LIMIT,
               peak_qty: Optional[int] = None) -> List[Fill]:
        default_price = float('inf') if side == Side.BUY else 0.0
        actual_price = price if price is not None else default_price

        o = Order(
            order_id=self._next_id(),
            price=actual_price,
            quantity=qty,
            side=side.value,
            order_type=order_type.value,
            timestamp=self._now(),
        )
        if order_type == OrderType.ICEBERG and peak_qty is not None:
            o._peak_qty = peak_qty
            o._reserve_qty = qty - peak_qty
            o.remaining = peak_qty

        if order_type == OrderType.FOK:
            if not self._can_fully_fill(o):
                return []

        new_fills = self._match(o)

        if o.remaining > 0:
            if order_type == OrderType.LIMIT:
                self._add_to_book(o)
            elif order_type == OrderType.ICEBERG:
                self._replenish_iceberg(o)

        return new_fills

    def _can_fully_fill(self, order: Order) -> bool:
        avail = 0
        book = self.lob.asks if order.side == 'BUY' else self.lob.bids
        for neg_p, lvl in book.items():
            p = -neg_p if order.side == 'BUY' else neg_p
            if order.side == 'BUY' and p > order.price:
                break
            if order.side == 'SELL' and p < order.price:
                break
            avail += lvl.total_quantity
        return avail >= order.remaining

    def _match(self, aggressor: Order) -> List[Fill]:
        fills = []
        if aggressor.side == 'BUY':
            opposite = self.lob.asks
            price_ok = lambda rp: rp <= aggressor.price
            key_sign = +1
        else:
            opposite = self.lob.bids
            price_ok = lambda rp: rp >= aggressor.price
            key_sign = -1

        while aggressor.remaining > 0 and opposite:
            best_key, best_level = next(iter(opposite.items()))
            rest_price = key_sign * best_key

            if not price_ok(rest_price):
                break

            while aggressor.remaining > 0 and best_level.orders:
                passive = best_level.orders[0]
                fill_qty = min(aggressor.remaining, passive.remaining)

                f = Fill(
                    aggressive_id=aggressor.order_id,
                    passive_id=passive.order_id,
                    price=rest_price,
                    quantity=fill_qty,
                    timestamp=self._now(),
                )
                fills.append(f)
                self.fills.append(f)

                aggressor.remaining -= fill_qty
                passive.remaining -= fill_qty

                if passive.is_filled:
                    best_level.orders.popleft()
                    del self.lob.orders[passive.order_id]

            if not best_level.orders:
                del opposite[best_key]
        return fills

    def _add_to_book(self, order: Order):
        if order.side == 'BUY':
            key = -order.price
            book = self.lob.bids
        else:
            key = order.price
            book = self.lob.asks

        if key not in book:
            book[key] = PriceLevel(price=order.price)
        book[key].orders.append(order)
        self.lob.orders[order.order_id] = order

    def _replenish_iceberg(self, order: Order):
        if hasattr(order, '_reserve_qty') and order._reserve_qty > 0:
            refill = min(order._peak_qty, order._reserve_qty)
            order.remaining = refill
            order._reserve_qty -= refill
            order.timestamp = self._now()
            self._add_to_book(order)

    def cancel(self, order_id: int) -> bool:
        if order_id not in self.lob.orders:
            return False
        o = self.lob.orders[order_id]
        book = self.lob.bids if o.side == 'BUY' else self.lob.asks
        key = -o.price if o.side == 'BUY' else o.price
        lvl = book.get(key)
        if lvl:
            try:
                lvl.orders.remove(o)
            except ValueError:
                pass
            if not lvl.orders:
                del book[key]
            del self.lob.orders[order_id]
            return True
        return False

import numpy as np
from scipy.stats import expon, poisson
from dataclasses import dataclass, field
from typing import List, Optional
import bisect

@dataclass
class QueueState:
    price: float
    side: str
    qty_ahead: int = 0
    our_qty: int = 0
    qty_behind: int = 0
    arrival_time: int = 0

    @property
    def total_qty_at_level(self) -> int:
        return self.qty_ahead + self.our_qty + self.qty_behind

class QueueSimulator:
    def __init__(self, arrival_rate: float, cancel_rate: float,
                 fill_rate: float, tick_size: float = 0.01):
        self.arrival_rate = arrival_rate
        self.cancel_rate = cancel_rate
        self.fill_rate = fill_rate
        self.tick_size = tick_size

    def simulate_queue_evolution(self, initial_state: QueueState,
                                 horizon_sec: float,
                                 n_paths: int = 10000) -> np.ndarray:
        rng = np.random.default_rng(42)
        Q0 = initial_state.qty_ahead
        dt = 1e-3
        n_steps = int(horizon_sec / dt)

        paths = np.full((n_paths,), float(Q0))
        paths = np.maximum(paths, 0)

        for _ in range(n_steps):
            arrivals = rng.poisson(self.arrival_rate * dt, size=n_paths)
            reductions = rng.poisson((self.cancel_rate + self.fill_rate)
                                     * dt * np.maximum(paths, 1), size=n_paths)
            paths = np.maximum(paths + arrivals - reductions, 0)

        return paths

    def fill_probability(self, state: QueueState,
                         incoming_vol_distribution: np.ndarray,
                         n_sim: int = 50000) -> dict:
        Q_ahead = state.qty_ahead
        Q_our = state.our_qty

        fill_probs = np.zeros(n_sim)
        fill_qtys = np.zeros(n_sim)
        rng = np.random.default_rng(0)

        for i in range(n_sim):
            V = rng.choice(incoming_vol_distribution)
            if V <= Q_ahead:
                fill_qty = 0
            elif V <= Q_ahead + Q_our:
                fill_qty = V - Q_ahead
            else:
                fill_qty = Q_our
            fill_probs[i] = 1.0 if fill_qty > 0 else 0.0
            fill_qtys[i] = fill_qty

        return {
            'fill_probability': fill_probs.mean(),
            'expected_fill_qty': fill_qtys.mean(),
            'full_fill_probability': (fill_qtys == Q_our).mean(),
            'partial_fill_prob': ((fill_qtys > 0) & (fill_qtys < Q_our)).mean(),
        }

class QueuePositionEstimator:
    def __init__(self, order_id: int, price: float, side: str,
                 qty: int, queue_state: QueueState):
        self.order_id = order_id
        self.price = price
        self.side = side
        self.qty = qty
        self.state = queue_state

    def on_new_order_at_level(self, order_qty: int, timestamp: int):
        self.state.qty_behind += order_qty

    def on_cancel_at_level(self, cancelled_qty: int, is_ahead: bool):
        if is_ahead:
            self.state.qty_ahead = max(0, self.state.qty_ahead - cancelled_qty)
        else:
            self.state.qty_behind = max(0, self.state.qty_behind - cancelled_qty)

    def on_trade_at_level(self, traded_qty: int):
        if traded_qty <= self.state.qty_ahead:
            self.state.qty_ahead -= traded_qty
        else:
            our_fill = min(traded_qty - self.state.qty_ahead, self.state.our_qty)
            self.state.qty_ahead = 0
            self.state.our_qty = max(0, self.state.our_qty - our_fill)
            return our_fill
        return 0

    def queue_ahead(self) -> int:
        return self.state.qty_ahead

    def estimated_fill_time(self, avg_fill_rate_per_sec: float) -> float:
        if avg_fill_rate_per_sec <= 0:
            return float('inf')
        return self.state.qty_ahead / avg_fill_rate_per_sec

