# -*- coding: utf-8 -*-
"""Routing Logic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

class Venue:
  def __init__(self, name, best_price, fee, rebate, latency_us, queue_ahead, fill_rate_per_sec, toxicity):
    self.name = name
    self.best_price = best_price
    self.fee = fee
    self.rebate = rebate
    self.latency_us = latency_us
    self.queue_ahead = queue_ahead
    self.fill_rate_per_sec = fill_rate_per_sec
    self.toxicity = toxicity

  def fill_probability(self, horizon_sec):
    rate = self.fill_rate_per_sec / max(self.queue_ahead, 1)
    return 1 - np.exp(-rate * horizon_sec)

def score_venues(venues, horizon_sec, weights):
  w_fill, w_tox, w_fee, w_lat = weights
  scores = {}
  for v in venues:
    p_fill = v.fill_probability(horizon_sec)
    net_fee = v.fee - v.rebate
    lat_penalty = v.latency_us / 1000.0
    scores[v.name] = (w_fill * p_fill - w_tox * v.toxicity - w_fee * net_fee - w_lat * lat_penalty)
    return scores

def softmax_allocate(scores, total_qty, beta=3.0):
  names = list(scores.keys())
  vals = np.array([scores[n] for n in names])
  exp_vals = np.exp(beta * (vals - vals.max()))
  weights = exp_vals / exp_vals.sum()
  alloc = {n: int(round(w * total_qty)) for n, w in zip(names, weights)}
  return alloc

if __name__ == '__main__':
  Venues = [
      Venue('NASDAQ', 100.01, fee=0.0030, rebate=0.0020, latency_us=180, queue_ahead=500, fill_rate_per_sec=2000, toxicity=0.8),
      Venue('NYSE', 100.01, fee=0.0029, rebate=0.0018, latency_us=210, queue_ahead=300, fill_rate_per_sec=1500, toxicity=0.6),
      Venue('EDGX', 100.02, fee=0.0010, rebate=0.0005, latency_us=150, queue_ahead=80, fill_rate_per_sec=800, toxicity=1.4),
      Venue('IEX', 100.01, fee=0.0009, rebate=0.000, latency_us=350, queue_ahead=120, fill_rate_per_sec=600, toxicity=0.2),
  ]
  weights = (w_fill := 1.0, w_tox := 0.5, w_fee := 50.0, w_lat := 0.02)
  horizon = 0.5

  scores = score_venues(Venues, horizon, weights)
  alloc = softmax_allocate(scores, 1000, beta=4.0)

  print("Venue Scores:", {k: round(v, 4) for k, v in scores.items()})
  print("Child Order Allocation:", alloc)

