# -*- coding: utf-8 -*-
"""Order Flow Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd

def load_taq_data(filepath: str) -> pd.DataFrame:
  df = pd.read_parquet(filepath)
  df['time'] = pd.to_datetime(df['time'])
  df = df.sort_values('time').reset_index(drop=True)

  df = df[df['time'].dt.time.between(
      pd.Timestamp('09:30').time(),
      pd.Timestamp('16:00').time()
  )]

  regular_conditions = ['@', '', ' ', '@F', '@I', '@O']
  df = df[df['cond_codes'].isin(regular_conditions)]

  return df

def compute_quote_midpoint(quotes_df: pd.DataFrame) -> pd.DataFrame:
  quotes_df['midpoint'] = (quotes_df['best_ask'] + quotes_df['best_bid']) / 2
  quotes_df['spread'] = quotes_df['best_ask'] - quotes_df['best_bid']
  return quotes_df

def merge_traders_quotes(trades: pd.DataFrame, quotes: pd.DataFrame, method: str = 'asof') -> pd.DataFrame:
  trades = trades.sort_values('time')
  quotes = quotes.sort_values('time')

  merged = pd.merge_asof(trades, quotes[['time', 'best_bid', 'best_ask', 'mid_point', 'spread']], on='time', direction='backward', tolerance=pd.Timeselta('1s'))

  return merged

