# -*- coding: utf-8 -*-
"""Order Flow Alpha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from typing import List, Optional

class OFIAlphaSignal:
  def __init__(self, lookback_periods: List[int] = [1, 5, 10, 20, 60], decay: float = 0.95, normalize_window: int = 20):
    self.lookbacks = lookback_periods
    self.decay = decay
    self.norm_window = normalize_window
    self.beta_estimates = {}

  def compute_multi_horizon_ofi(self, trades_quotes: pd.DataFrame, freq: str = '1min') -> pd.DataFrame:
    flow = (trades_quotes.set_index('time')['signed_volmue'].resample(freq).sum())

    mid = (trades_quotes.set_index('time')['midpoint'].resample(freq).last())

    signals = pd.DataFrame(index=flow.index)
    signals['base_ofi'] = flow
    signals['mid'] = mid
    signals['return'] = mid.pct_change()

    for lb in self.lookbacks:
      signals[f'ofi_{lb}'] = flow.rolling(lb).sum()
      total_vol = (trades_quotes.set_index('time')['signed_volume'].abs().resample(freq).sum().rolling(lb).sum())
      signals[f'ofi_{lb}_norm'] = signals[f'ofi_{lb}'] / (total_vol + 1e-10)

    return signals

  def z_score_signal(self, signal: pd.Series, window: Optional[int] = None) -> pd.Series:
    w = window or self.norm_window
    rolling_mean = signal.rolling(w).mean()
    rolling_std = signal.rolling(w).std()
    z = (signal - rolling_mean) / (rolling_std + 1e-10)

    return z.clip(-3, 3)

  def construct_composite_signal(self, signals: pd.DataFrame, method: str = 'pcs') -> pd.Series:
    ofi_cols = [c for c in signals.columns if c.startwith('ofi')]
    X = signals[ofi_cols].copy()

    X = X.apply(lambda col: self.z_score_signal(col))
    X = X.dropna()

    if method == 'equal_weight':
      return X.mean(axis=1)

    elif method == 'pca':
      from sklearn.decomposition import PCA
      pca = PCA(n_components=1)
      X_filled = X.fillna(0)
      pc1 = pca.fit_transform(X_filled)
      composite = pd.Series(pc1[:,0], index=X.index)
      print(f"PC1 explains {pca.explained_variance_ratio_[0]:.2%} ofvariance")
      return self.z_score_signal(composite)

    elif method == 'regression':
      y = signals['return'].shift(-1)
      results = []
      window = 252
      for i in range(window, len(X)):
        X_win = X.iloc[i-window:i]
        y_win = y.iloc[i-window:i]
        valid = X_win.join(y_win).dropna()
        if len(valid) < 50:
          results.append(0.0)
          continue
        from sklearn.linear_model import Ridge
        reg = Ridge(alpha=10.0)
        reg.fit(valid[ofi_cols], valid['return'])
        pred = reg.predict(X.iloc[i:i+1][ofi_cols])
        results.append(float(pred))
      return pd.Series(results, index=X.index[window:])

  def backtest_signal(self, signal: pd.Series, returns: pd.Series, transaction_cost: float = 0.0005, holding_period: int = 1) -> dict:
    position = np.sign(signal).shift(1)

    strat_returns = position * returns

    position_change = position.diff().abs()
    costs = position_change * transaction_cost / 2

    net_returns = strat_returns - costs

    n_per_year = 252 * 390

    ann_ret = net_returns.mean() * n_per_year
    ann_vol = net_returns.std() * np.sqrt(n_per_year)
    sharpe = ann_ret / (ann_vol + 1e-10)
    cum_ret = (1 + net_returns).cumprod()
    max_dd = (cum_ret / cum_ret.cummax() - 1).min()
    hit_rate = (strat_returns > 0).mean()

    print(f"Annualized Return: {ann_ret:.4f}")
    print(f"Annualized Vol: {ann_vol:.4f}")
    print(f"Sharpe Ratio: {sharpe:.3f}")
    print(f"Max Drawdaown: {max_dd:.4f}")
    print(f"Hit Rate: {hit_rate:.4f}")

    return {
      'annualized_return': ann_ret,
      'annualized_volatility': ann_vol,
      'sharpe_ratio': sharpe,
      'max_drawdown': max_dd,
      'hit_rate': hit_rate,
      'cumulative_returns': cum_ret,
      'net_returns': net_returns}

