# -*- coding: utf-8 -*-
"""Signed Order Flow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.api as sm

def estimate_kyle_lambda(trades: pd.DataFrame, interval: str = '5min', method: str = 'OLS') -> dict:
  trades_ts = trades.set_index('time')
  agg = trades_ts.resample(interval).agg(open_price=('price', 'first'), close_price=('price', 'last'), signed_vol=('signed_volume', 'sum'), total_vol=('signed_volume', lambda x: x.abs().sum())).dropna()

  agg['dp'] = np.log(agg['close_price']) - np.log(agg['open_price'])
  agg = agg.dropna()

  X = agg['signed_vol'].values
  y = agg['dp'].values

  if method == 'OLS':
    X_const = sm.add_constant(X)
    model = sm.OLS(y, X_const).fit()
    lam = model.param[1]
    se = model.bse[1]
    r2 = model.rsquared
    t = model.tvalues[1]
    p = model.pvalues[1]

  elif method == 'WLS':
    weights = agg['total_vol'].values
    X_const = sm.add_constant(X)
    model = sm.WLS(y, X_const, weights=weights).fit()
    lam = model.params[1]
    se = model.bse[1]
    r2 = model.rsquared
    t = model.tvalues[1]
    p = model.pvalues[1]

  elif method == 'robust':
    X_const = sm.add_constant(X)
    model = sm.RLM(y, X_const).fit()
    lam = model.params[1]
    se = model.bse[1]
    r2 = np.nan
    t = model.tvalues[1]
    p = model.pvalues[1]

  print(f"Kyle's Lambda: {lam:.6f}")
  print(f"Srd. Err.: {se:.6f}")
  print(f"R^2: {r2:.6f}")
  print(f"t-stat: {t:.6f}")
  print(f"p-value: {p:.6f}")

  return {'lambda': lam, 'se': se, 'r2': r2, 't': t, 'p': p, 'n_obs': len(y), 'interval': interval}

def estimate_lambda_rolling(trades: pd.DataFrame, window_days: int = 20, interval: str = '5min') -> pd.DataFrame:
  results = []
  dates = pd.to_datetime(trades['time'].dt.date.unique())

  for i in range(window_days, len(dates)):
    window_trades = trades[trades['time'].dt.date.isin(dates[i-window_days:i])]
    results = estimate_kyle_lambda(window_trades, interval)
    results['date'] = dates[i]
    results.append(results)

  return pd.DataFrame(results).set_index('date')

def signed_flow_acf(trades: pd.DataFrame, max_lags: int = 20, interval: str = '1min') -> pd.DataFrame:
  signed_flow = (trades.set_index('time')['signed_volume'].resample(interval).sum().dropna())

  acf_values = []
  for lag in range(1, max_lags+1):
    corr = signed_flow.autocorr(lag=lag)
    from statsmodels.stats.stattools import durbin_watson
    acf_values.append({'lag': lag, 'acf': corr, 'significant': abs(corr) > 1.96 / np.sqrt(len(signed_flow))})

  return pd.DataFrame(acf_values)

