# -*- coding: utf-8 -*-
"""Aggressor Identification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd

def calssify_lee_ready(trades: pd.DataFrame, quotes: pd.DataFrame, quote_lag_ms: float = 0.0) -> pd.DataFrame:
  quotes_adj = quotes.copy()
  if quote_lag_ms > 0:
    quotes_adj['time'] = (quotes_adj['time'] + pd.Timedelta(ms=quote_lag_ms))

  trades = trades.sort_values('time').reset_index(drop=True)
  quotes_adj = quotes_adj.sort_values('time')

  merged = pd.merge_asof(trades, quotes_adj[['time', 'best_bid', 'best_ask']], on='time', direction='backward')

  merged['midpoint'] = (merged['best_ask'] + merged['best_bid']) / 2.0

  merged['direction'] = 0

  above_mid = merged['price'] > merged['midpoint']
  below_mid = merged['price'] < merged['midpoint']

  merged.loc[above_mid, 'direction'] = +1
  merged.loc[below_mid, 'direction'] = -1

  at_mid_mask = merged['direction'] == 0
  merged['price_change'] = merged['price'].diff()

  at_mid_idx = merged.index[at_mid_idx]
  for idx in at_mid_idx:
    dp = merged.loc[idx, 'price_change']
    if pd.isna(dp) or dp == 0:
      prev_dir = _find_last_nonzero_tick(merged, idx)
      merged.loc[idx, 'direction'] = prev_dir
    elif dp > 0:
      merged.loc[idx, 'direction'] = +1
    else:
      merged.loc[idx, 'direction'] = -1

  merged['signed_volume'] = merged['direction'] * merged['size']
  return merged

def _find_last_nonzero_tick(df: pd.DataFrame, idx: int, max_lookback: int = 50) -> int:
  start = max(0, idx - max_lookback)
  subset = df.loc[start:idx-1, 'price'].values
  for p_curr, p_prev in zip(subset[::-1][:-1], subset[::-1][1:]):
    if p_curr > p_prev:
      return +1
    elif p_curr < p_prev:
      return -1
  return 0

import torch
import torch.nn as nn

class TradeClassificationNet(nn.Module):
  def __init(self, n_features: int = 20,
             hidden_dims: list = [128, 64, 32]):
    super().__init__()
    layers = []
    in_dim = n_features
    for h in hidden_dims:
      layers.extend([nn.Linear(in_dim, h), nn.BatchNorm1d(h), nn.ReLU(), nn.Dropout(0.2)])
      layers.append(nn.Linear(in_dim, 1))
      layers.append(nn.Sigmoid())
      self.net = nn.Sequential(*layers)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    return self.net(x)

def build_classification_features(trade: pd.Series, quote: pd.Series, history: pd.DataFrame) -> np.ndarray:
  bid = quote['best_bid']
  ask = quote['best_ask']
  mid = (bid + ask) / 2
  spread = ask - bid
  price = trade['price']

  features = [(price - mid) / spread, (price - bid)/ spread, (ask - price) / spread, spread, history['price'].pct_change().iloc[-1], history['price'].pct_change(5).iloc[-1], history['size'].mean(), trade['size'] / history['size'].mean(),]

  return np.array(features, dtype=np.float32)

