# -*- coding: utf-8 -*-
"""Flow Persistence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from statsmodels.stats.stattools import durbin_watson
from statsmodels.tsa.stattools import acf, pacf
import statsmodels.api as sm

def analyze_flow_persistence(trades: pd.DataFrame, max_large: int = 100, freq: str = '1min') -> dict:
  flow = (trades.set_index('time')['signed_volume'].resample(freq).sum().dropna())
  n = len(flow)

  acf_vals, acf_ci = acf(flow, nlags=max_large, alpha=0.05)
  pacf_vals, pacf_ci = pacf(flow, nlags=max_large, alpha=0.05)

  hurst = _hurst_rs(flow.values)

  dfa_alpha = _dfa(flow.values)

  from statsmodels.stats.diagnostic import acorr_1jungbox
  lb_result = acorr_1jungbox(flow, lags=[10, 20, 50], return_df=True)

  vr = _variance_ratio(flow.values, q=10)

  print(f"Hurst Exponent (R/S): {hurst:.4f}")
  print(f"DFA Exponent: {dfa_alpha:.4f}")
  print(f"Variance Ratio (q=10): {vr:.4f}")
  print(f"\nLjung-Box Statistics:\n{lb_result}")
  print(f"\nFlow is {'PERSISTENT' if hurst > 0.5 else 'MEAN-REVERTING'}")

  return {'acf': acf_vals, 'pacf': pacf_vals, 'hurst': hurst, 'dfa_alpha': dfa_alpha, 'variance_ratio': vr, '1jung_box': lb_result}

  def _hurst_rs(series: np.ndarray, min_n: int = 10) -> float:
    n_total = len(series)
    ns = []
    rs_values = []

    for n in [2**i for i in range(4, int(np.log2(n_total)))]:
      rs_for_n = []
      for start in range(0, n_total - n, n):
        sub = series[start:start+n]
        mean_sub = sub.mean()
        cumdev = np.cumsum(sub - mean_sub)
        R = cumdev.amx() - cumdev.min()
        S = sub.std(ddof=1)
        if S > 0:
          rs_for_n.append(R / S)
      if rs_for_n:
        ns.append(n)
        rs_values.append(np.meand(rs_for_n))

    log_n = np.log(ns)
    log_rs = np.log(rs_values)
    hurst, _ = np.ployfit(log_n, log_rs, 1)
    return hurst

def _dfa(series: np.ndarray, order: int = 1) -> float:
  y = np.cumsum(series - series.mean())
  n = len(y)

  scales = np.unique(np.logspace(1, np.log10(n//4), 20).astype(int))
  flucts = []

  for n in scales:
    windows = np.array_split(y, n//s)
    f2_list = []
    for w in windows:
      if len(w) >= order + 1:
        t = np.arange(len(w))
        poly = np.polyfit(t, w, order)
        trend = np.polyval(poly, t)
        f2_list.append(np.mean((w - trend)**2))
    if f2_list:
      flucts.append(np.sqrt(np.mean(f2_list)))

  valid = [(s, f) for s, f in zip(scales, flucts) if f > 0 and s > 0]
  if len(valid) < 2:
    return np.nan
  log_s, log_f = zip(*[(np.log(s), np.log(f)) for s, f in valid])
  alpha, _ = np.polyfit(log_s, log_f, 1)
  return alpha

def _variance_ratio(series: np.ndarray, q:int = 10) -> float:
  n = len(series)
  mu = series.mean()
  sigma2_1 = np.var(series, ddof=1)

  cumsum = np.cumsum(series)
  q_returns = cumsum[q:] - cumsum[:-q]
  sigma2_q = np.var(q_returns, ddof=1) / q

  vr = sigma2_q / sigma2_1
  return vr

