# -*- coding: utf-8 -*-
"""Informed Trading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.optimize import minimize, differential_evolution
from scipy.special import gammaln

def pin_log_likelihood(params: np.ndarray, buys: np.ndarray, sells: np.ndarray) -> float:
  alpha, delta, epsilon, mu = params

  if not (0 <= alpha <= 1 and 0 <= delta <= 1 and epsilon > 0 and mu > 0):
    return 1e10

  n_days = len(buys)
  total_ll = 0.0

  for b, s in zip(buys, sells):
    log_epsilon = np.log(epsilon) if epsilon > 0 else -np.inf
    log_mu_epsilon = np.log(mu + epsilon) if (mu + epsilon) > 0 else -np.inf
    log_1_alpha = np.log(1 - alpha) if (1 - alpha) > 0 else -np.inf
    log_alpha_delta = np.log(alpha * delta) if (alpha * delta) > 0 else -np.inf
    log_alpha_1_delta = np.log(alpha * (1 - delta)) if (alpha * (1 - delta)) > 0 else -np.inf

    ll_no_event = (-2*epsilon + b*log_epsilon + s*log_epsilon - gammaln(b+1) - gammaln(s+1))

    ll_bad_news = (-epsilon + b*log_epsilon -(mu+epsilon) + s*log_mu_epsilon - gammaln(b+1) - gammaln(s+1))

    ll_good_news = (-(mu+epsilon) + b*log_mu_epsilon - epsilon + s*log_epsilon - gammaln(b+1) - gammaln(s+1))

    log_weights = np.array([log_1_alpha + ll_no_event, log_alpha_delta + ll_bad_news, log_alpha_1_delta + ll_good_news])

    max_ll_val = np.max(log_weights)
    day_ll = max_ll_val + np.log(np.sum(np.exp(log_weights - max_ll_val)))
    total_ll +=  day_ll

  return -total_ll

def estimate_pin(buys: np.ndarray, sells: np.ndarray, n_restarts: int = 20) -> dict:
  bounds = [(1e-4, 1-1e-4), (1e-4, 1-1e-4), (1e-3, None), (1e-3, None)]

  best_result = None
  best_ll = np.inf

  np.random.seed(12)
  for _ in range(n_restarts):
    x0 = [np.random.uniform(0.1, 0.9),
          np.random.uniform(0.1, 0.9),
          np.random.uniform(50, 300),
          np.random.uniform(50, 500)]

    try:
      result = minimize(
          pin_log_likelihood,
          x0=x0,
          args=(buys, sells), method='L-BFGS-B',bounds=bounds,options={'ftol': 1e-9, 'gtol': 1e-7, 'maxiter': 10000}
      )
      if result.fun < best_ll:
        best_ll = result.fun
        best_result = result
    except Exception as e:
      continue

  if best_result is None:
    return {'pin': np.nan}

  alpha, delta, epsilon, mu = best_result.x
  pin = alpha * mu / (alpha * mu + 2 * epsilon)

  return {'pin': pin,
          'alpha': alpha,
          'delta': delta,
          'epsilon': epsilon,
          'mu': mu,
          'log_likelihood': -best_ll,
          'convergence': best_result.success}

def compute_rolling_pin(buys: pd.Series, sells: pd.Series, window: int = 60) -> pd.Series:
  n = len(buys)
  pin_series = pd.Series(index=buys.index, dtype=float)

  for i in range(window, n):
    b_window = buys.iloc[i-window:i].values
    s_window = sells.iloc[i-window:i].values
    result = estimate_pin(b_window, s_window, n_restarts=10)
    pin_series.iloc[i] = result.get('pin', np.nan)

  return pin_series

def compute_vpin(trades: pd.DataFrame, bucket_size: float = None, n_buckets: int = 50, window_buckets: int = 50) -> pd.DataFrame:
  if bucket_size is None:
    daily_vol = trades['size'].sum() / trades['time'].dt.date.nunique()
    bucket_size = daily_vol / n_buckets

  sigma = trades['price'].pct_change().std()

  bars = []
  cumvol = 0.0
  bar_buy = 0.0
  bar_sell = 0.0
  bar_start = trades['time'].iloc[0]

  for _, row in trades.iterrows():
    dp = row['price'] - trades['price'].shift(1).loc[row.name]
    if pd.isna(dp):
      z = 0.5
    else:
      from scipy.stats import norm
      z = norm.cdf(dp / (sigma * row['price']))
    vol_buy = row['size'] * z
    vol_sell = row['size'] * (1 - z)

    remaining = bucket_size - cumvol
    if row['size'] <= remaining:
      bar_buy += vol_buy
      bar_sell += vol_sell
      cumvol += row['size']
    else:
      frac = remaining / row['size']
      bar_buy += vol_buy * frac
      bar_sell += vol_sell * frac
      bars.append({'time': row['time'], 'buy': bar_buy, 'sell': bar_sell, 'imbalance': abs(bar_buy - bar_sell)})

      bar_buy = vol_buy * (1 - frac)
      bar_sell = vol_sell * (1 - frac)
      cumvol = row['size'] * (1-frac)

  bars_df = pd.DataFrame(bars)

  bars_df['vpin'] = (bars_df['imbalance'].rolling(window_buckets).sum()) / (window_buckets * bucket_size)

  return bars_df

