# -*- coding: utf-8 -*-
"""Informed Trading.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm

def glosten_harris_decomposition(trades_quotes: pd.DataFrame) -> dict:
  df = trades_quotes.dropna(subset=['price', 'signed_volume', 'midpoint'])

  df['eff_spread'] = (df['signed_volume'].apply(np.sign) * (df['price'] - df['midpoint']))

  df['delta_mid'] = df['midpoint'].diff()

  df['realized_spread'] = (df['signed_volume'].apply(np.sign) * (df['midpoint'].shift(-5) - df['midpoint']))

  df['adverse_selection'] = df['eff_spread'] - df['realized_spread']
  df = df.dropna()

  s = df['signed_volume'].apply(np.sign)
  Q = df['signed_volume'].abs()

  X = pd.DataFrame({'z0_s': s, 'z1_sQ': s * Q, 'c0_ds': s - s.shift(1), 'c1_dsQ': s * Q - s.shift(1) * Q. shift(1)}).dropna()
  y = df['price'].diff().dropna()

  min_len = min(len(X), len(y))
  X = X.iloc[-min_len:]
  y = y.iloc[-min_len:]

  model = sm.OLS(y, X).fit()
  z0 = model.params.get('z0_s', np.nan)
  z1 = model.params.get('z1_sQ', np.nan)
  c0 = model.params.get('c0_ds', np.nan)
  c1 = model.params.get('c1_dsQ', np.nan)

  Q_avg = Q.mean()
  adverse_frac = (z0 +  z1 * Q_avg) / (z0 + z1 + Q_avg + c0 + c1 * Q_avg)

  results = {'z0': z0, 'z1': z1, 'c0': c0, 'c1': c1, 'adverse_frac': adverse_frac, 'mean_adverse_selction': df['adverse_selection'].mean(), 'mean_realized_spread': df['realized_spread'].mean(),}

  print(f"Adverse Selection Fraction: {adverse_frac:.4f}")
  print(f"Mean Effective Spread: {df['eff_spread'].mean():.4f}")
  print(f"Mean Adverse Selection: {df['adverse_selection'].mean():.4f}")
  print(f"Mean Realized Spread: {df['realized_spread'].mean():.4f}")

  return results

