# -*- coding: utf-8 -*-
"""Flow Imbalance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np

def compute_lob_ofi(lob_snapshots: pd.DataFrame, aggregate_ms: int = 100) -> pd.DataFrame:
  df = lob_snapshots.copy().sort_values('time').reset_index(drop=True)

  df['prev_bid'] = df['best_bid'].shift(1)
  df['prev_bid_size'] = df['best_bid_size'].shift(1)
  df['prev_ask'] = df['best_ask'].shift(1)
  df['prev_ask_size'] = df['best_ask_size'].shift(1)

  conditions_bid = [df['best_bid'] > df['prev_bid'], df['best_bid'] == df['prev_bid'], df['best_bid'] < df['prev_bid'],]

  choices_bid = [df['best_bid_size'], df['best_bid_size'] - df['prev_bid_size'], 0.0]

  df['e_bid'] = np.select(conditions_bid, choices_bid, default=0.0)

  conditions_ask = [df['best_ask'] < df['prev_ask'], df['best_ask'] == df['prev_ask'], df['best_ask'] > df['prev_ask'],]
  choices_ask = [-df['best_ask_size'], df['best_ask_size'] - df['prev_ask_size'], 0.0]

  df['e_ask'] = np.select(conditions_ask, choices_ask, default=0.0)

  df['ofi_raw'] = df['e_bid'] - df['e_ask']
  df = df.dropna()

  df_ts = df.set_index('time')
  freq = f'{aggregate_ms}ms'
  ofi_agg = df_ts['ofi_raw'].resample(freq).sum().rename('ofi')
  price_agg = df_ts['best_bid'].resample(freq).last()

  result = pd.DataFrame({'ofi': ofi_agg, 'price': price_agg})
  result['dp'] = result['price'].diff()
  result = result.dropna()

  return result

def ofi_price_impact_regression(ofi_price: pd.DataFrame, horizon_bars: int = 1) -> dict:
  import statsmodels.api as sm

  y = ofi_price['dp'].shift(-horizon_bars).dropna()
  X = ofi_price['ofi'].iloc[:len(y)]

  X_const = sm.add_constant(X)
  model = sm.OLS(y, X_const).fit(cov_type='HAC', cov_kwds={'maxlags':10})

  beta = model.params['ofi']
  print(f"OFI Price Impact (beta): {beta:.8f}")
  print(f"R-Squared: {model.rsquared}:.4f")
  print(f"t-statistic: {model.tvalues['ofi']:.4f}")

  return {'beta': beta, 'r2': model.rsquared, 'model': model}

