# -*- coding: utf-8 -*-
"""Flow Predictability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.model_selection import TimeSeriesSplit

def fit_as_flow_model(flow: pd.Series, returns: pd.Series, max_lags_flow: int = 20, max_lags_ret: int = 10, select_lags: bool = True) -> dict:
  if select_lags:
    best_bic = np.inf
    best_k, best_j = 1, 1

    for k in range(1, max_lags_flow + 1):
      for j in range(0, max_lags_ret + 1):
        X_data = {}
        for lag in range(1, k+1):
          X_data[f'flow_lag{lag}'] = flow.shift(lag)
        for lag in range(1, k+1):
          X_data[f'ret_lag{lag}'] = returns.shift(lag)

        df_model = pd.DataFrame(X_data).assign(y=flow).dropna()
        X = s.add_constant(df_model.drop('y', axis=1))
        y = df_model['y']

        try:
          m = sm.OLS(y, X).fit()
          if m.bic < best_bic:
            best_bic = m.bic
            best_k, best_j = k, j
        except:
          continue

    K, J = best_k, best_j
    print(f"Optimal lags: K={K} (flow), J={J} (return)")
  else:
    K, J = max_lags_flow, max_lags_ret

  X_data = {}
  for lag in range(1, K+1):
    X_data[f'flow_lag{lag}'] = flow.shift(lag)
  for lag in range(1, J+1):
    X_data[f'ret_lag{lag}'] = returns.shift(lag)

  df_model = pd.DataFrame(X_data).assign(y=flow).dropna()
  X = sm.add_constant(df_model.drop('y', axis=1))
  y = df_model['y']

  model = sm.OLS(y, X).fit(cov_type='HAC', cov_kwds={'maxlags': 10})
  print(model.summary())

  return {'model': model, 'K': K, 'J': J, 'bic': model.bic}

from scipy.optimize import minimize
import numpy as np

def hawkes_log_likelihood(params: np.ndarray, event_times_buy: np.ndarray, event_times_sell: np.ndarray, T: float) -> float:
  (mu_b, mu_s, a_bb, b_bb, a_bs, b_bs, a_sb, b_sb, a_ss, b_ss) = params

  if any(p <= 0 for p in params):
    return 1e10

  if a_bb >= b_bb or a_ss >= b_ss:
    return 1e10

  ll_b = 0.0
  for t in event_times_buy:
    lam_b = mu_b
    lam_b += a_bb * np.sum(np.exp(-b_bb * (t - event_times_buy[event_times_buy < t])))
    lam_b += a_bs * np.sum(np.exp(-b_bs * (t - event_times_sell[event_times_sell < t])))
    lam_b = max(lam_b, 1e-10)
    ll_b += np.log(lam_b)

  comp_b = mu_b * T

  for s in event_times_buy:
    comp_b += (a_bb/b_bb) * (1 - np.exp(-b_bb * (T - s)))
  for s in event_times_sell:
    comp_b += (a_bs/b_bs) * (1 - np.exp(-b_bs * (T - s)))

  ll_s = 0.0
  for t in event_times_sell:
    lam_s = mu_s
    lam_s += a_ss * np.sum(np.exp(-b_ss * (t - event_times_sell[event_times_sell < t])))
    lam_s += a_sb * np.sum(np.exp(-b_sb * (t - event_times_buy[event_times_buy < t])))
    lam_s = max(lam_s, 1e-10)
    ll_s += np.log(lam_s)

  comp_s = mu_s * T
  for s in event_times_sell:
    comp_s += (a_ss/b_ss) * (1 - np.exp(-b_ss * (T - s)))
  for s in event_times_buy:
    comp_s += (a_sb/b_sb) * (1 - np.exp(-b_sb * (T - s)))

  total_ll = ll_b - comp_b + ll_s - comp_s
  return -total_ll

import xgboost as xgb
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, log_loss
import numpy as np
import pandas as pd

def build_flow_prediction_features(trades_quotes: pd.DataFrame, n_lags: int = 20) -> pd.DataFrame:
  df = trades_quotes.copy()
  features = {}

  for k in range(1, n_lags + 1):
    features[f'flow_lag_{k}'] = df['signed_volume'].shift(k)

  df['mid_return'] = df['midpoint'].pct_change()
  for k  in range(1, 10):
    features[f'ret_lag_{k}'] = df['mid_return'].shift(k)

  df['spread'] = df['best_ask'] - df['best_bid']
  df['depth_imbalance'] = ((df.get('bid_depth', df['best_bid']) - df.get('ask_depth', df['best_ask'])) / (df.get('bid_depth', df['best_bid']) + df.get('ask_depth', df['best_ask']) + 1e-10))

  features['spread'] = df['spread']
  features['depth_imbalance'] = df['depth_imbalance']

  for window in [5, 10, 20]:
    features[f'flow_ma_{window}'] = df['signed_volume'].rolling(window).mean()
    features[f'flow_std_{window}'] = df['signed_volume'].rolling(window).std()
    features[f'vol_ma_{window}'] = df['signed_volume'].abs().rolling(window).mean()

  df['tod_sec'] = (pd.to_datetime(df['time']).dt.hour * 3600 + pd.to_datetime(df['time']).dt.minute * 60 + pd.to_datetime(df['time']).dt.second)
  features['tod_sin'] = np.sin(2 * np.pi * df['tod_sec'] / 23400)
  features['tod_cos'] = np.cos(2 * np.pi * df['tod_sec'] / 23400)

  X = pd.DataFrame(features)
  y = np.sign(df['signed_volume'])

  return X.dropna(), y.loc[X.dropna().index]

def train_xgb_flow_predictor(X: pd.DataFrame, y: pd.Series, n_splits: int = 5) -> dict:
  y_binary = (y > 0).astype(int)

  tscv = TimeSeriesSplit(n_splits=n_splits)
  val_accuracies = []
  val_log_losses = []
  feature_importances = []

  params = {'max_depth': 6,
            'learning_rate': 0.05, 'n_estimators': 500, 'subsample': 0.8, 'min_child_weight': 10, 'gamma': 0.1, 'use_label_encoder': False, 'eval_metric': 'logloss', 'treemethid': 'hist', 'random_state': 12}

  models = []
  for fold, (train_idx, val_idx) in enumerate(tscv.split(X)):
    X_train, X_val = X.iloc[train_idx], X.iloc[val_idx]
    y_train, y_val = y_binary.iloc[train_idx], y_binary.iloc[val_idx]

    model = xgb.XGBClassifier(**params)
    model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=False)

    proba = model.predict_proba(X_val)[:, 1]
    preds = (proba > 0.5).astype(int)

    acc = accuracy_score(y_val, preds)
    ll = log_loss(y_val, proba)
    val_accuracies.append(acc)
    val_log_losses.append(ll)
    feature_importances.append(model.feature_importances_)
    models.append(model)

    print(f"Fold {fold+1}: Acc={acc:.4f}, LogLoss={ll:.4f}")

  avg_acc = np.mean(val_accuracies)
  avg_ll = np.mean(val_log_losses)
  avg_fi = np.mean(feature_importances, axis=0)

  print(f"\nAverage Accuracy: {avg_acc:.4f} {np.std(val_accuracies):.4f}")
  print(f"Average LogLoss: {avg_ll:.4f} {np.std(val_log_losses):.4f}")

  fi_df = pd.DataFrame({'feature': X.columns, 'importance': avg_fi}).sort_values('importance', ascending=False)
  print("\nTop 10 features:\n", fi_df.head(10).to_string())

  return {'models': models, 'val_accuracies': val_accuracies, 'feature_importance': fi_df, 'mean_accuracy': avg_acc}

