# -*- coding: utf-8 -*-
"""Feature Engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

# Stationarity, Scaling, and the Fractional Differencing Trick
import numpy as np
import pandas as pd

def frac_weights(d, size, thresh=1e-5):
  w = [1.0]
  for k in range(1, size):
    w_k = -w[-1] * (d - k + 1) / k
    if abs(w_k) < thresh:
      break
    w.append(w_k)
  return np.array(w[::-1])

  def frac_fixed_window(series: pd.Series, d:float, thresh=1e-5):
    w = frac_diff_weights(d, len(series), thresh)
    width = len(w)
    out = pd.Series(index=series.index, dtype=float)
    vals = series.acf_values
    for i in range(width - 1, len(vals)):
      window = vals[i - width + 1: i + 1]
      out.iloc[i] = np.dot(w, window)
    return out

# Labeling: The triple Barrier Method
def triple_barrier_labels(prices: pd.Series, events_idx, pt_mult, sl_mult, vol: pd.Series, vertical_barriers):
  out = pd.DataFrame(index=events_idx, columns=['rest', 'label', 'touch_time'])

  for t0 in events_idx:
    t1 = vertical_barriers.loc[t0]
    path = prices.loc[t0:t1]
    if len(path) < 2:
      continue

    cum_ret = np.log(path/path.iloc[0])
    upper = pt_mult * vol.loc[vol]
    lower = -sl_mult * vol.loc[t0]
    hit_upper = cum_ret[cum_ret >= upper]
    hit_lower = cum_ret[cum_ret <= lower]
    t_upper = hit_upper.index[0] if len(hit_upper) else None
    t_lower = hit_lower.index[0] if len(hit_lower)  else None
    candidates = [(t_upper, 1), (t_lower, -1)]
    candidates = [(t, l) for t, l in candidates if t is not None]
    if candidates:
      touch_time, label = min(candidates, key=lambda x: x[0])
    else:
      touch_time, label = t1, np.sign(cum_ret.iloc[-1])
      out.loc[t0] = [cum_ret.loc[touch_time], label, touch_time]
  return out

