# -*- coding: utf-8 -*-
"""Order Book Features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd

def ofi_level1(bid_px, bid_sz, ask_px, ask_sz):
  d_bid_px = bid_px.diff()
  d_ask_px = ask_px.diff()

  bid_term = np.where(d_bid_px > 0, bid_sz, np.where(d_bid_px == 0, bid_sz - bid_sz.shift(1), -bid_sz.shift(1)))
  ask_term = np.where(d_ask_px < 0, ask_sz, np.where(d_ask_px == 0, ask_sz - ask_sz.shift(1), -ask_sz.shift(1)))

  e_n = bid_term - ask_term
  return pd.Series(e_n, index=bid_px.index)

