# -*- coding: utf-8 -*-
"""Flow Features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

class HawkesIntensity:
  def __init__(self, mu, alpha, beta):
    self.mu, self.alpha, self.beta = mu, alpha, beta
    self.K = len(mu)
    self.R = np.zeros((self.K, self.K))
    self.t_last = 0.0

  def update(self, t, k_events):
    dt = t - self.t_last
    self.R *= np.exp(-self.beta * dt)
    self.R[:, k_events] += 1.0
    self.t_last = t
    intensity = self.mu + np.sum(self.alpha * self.R, axis=1)
    return intensity

