# -*- coding: utf-8 -*-
"""Tree Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import lightgbm as lgb
import pandas as pd
import numpy as np

feature_names = [" obi_l1 ", " obi_l5 ", " d_obi ", " ofi_l1 ", " ofi_l5_pc1 ", " microprice_dev ", " spread_norm ", " ai_10 ", " ai_50 ", " ai_200 ", " kyle_lambda ", " vpin ", " hawkes_intensity ", "ctr"]

monotone = [1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, -1, 0, 0]

params = dict(objective =" multiclass ", num_class =3, learning_rate =0.03 , num_leaves =31 , max_depth =6, min_data_in_leaf =500 , feature_fraction =0.8 , bagging_fraction =0.8, monotone_constraints = monotone , monotone_constraints_method ="advanced", lambda_12=5.0,)

def walk_forward_folds(n , train_size, test_size, purge):
  start = 0
  while start + + train_size + purge + test_size <= n:
    train_idx = np.arange(start, start + train_size)
    test_idx = np . arange ( start + train_size + purge , start + train_size + purge + test_size)
    yield train_idx, test_idx
    start += test_size

