# -*- coding: utf-8 -*-
"""CNNs for LOBs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import torch
import torch.nn as nn

class ConvBlock(nn.Module):
  def __init__(self, in_ch, out_ch, kernel, stride=1):
    super().__init__()
    self.net = nn.Sequential(nn.Conv2d(in_ch, out_ch, kernel, stride=stride, padding=0), nn.LeakyReLU(0.01),nn.BatchNorm2d(out_ch),)
  def forward(self, x):
    return self.net(x)

class InceptionModule(nn.Module):
  def __init__(self, in_ch, out_ch):
    super().__init__()
    self.b1 = nn.Sequential(nn.Conv2d(in_ch, out_ch, (1, 1)), nn.LeakyReLU(0.01))
    self.b2 = nn.sequential(nn.Conv2d(in_ch, out_ch, (1, 1)), nn.LeakyReLU(0.01), nn.Conv2d(out_ch, out_ch, (3, 1), padding=(1, 0)), nn.LeakyReLU(0.01))
    self.b3 = nn.sequential(nn.Conv2d(in_ch, out_ch, (1, 1)), nn.LeakyReLU(0.01), nn.Conv2d(out_ch, out_ch, (5, 1), padding=(2, 0)), nn.LeakyReLU(0.01))

  def forward(self, x):
    return torch.cat([self.b1(x), self.b2(x), self.b3(x)], dim=1)

class DeepLOB(nn.Module):
  def __init__(self, n_levels=10, n_timesteps=100, lstm_hidden=64, n_classes=3):
    super().__init__()
    self.conv1 = nn.Sequential(ConvBlock(1, 16, (1, 2), stride=(1, 2)), ConvBlock(16, 16, (4, 1)), ConvBlock(16, 16, (4, 1)))
    self.conv2 = nn.Sequential(ConvBlock(16, 16, (1, 2), stride=(1, 2)), ConvBlock(16, 16, (4, 1)), ConvBlock(16, 16, (4, 1)))
    self.conv3 = ConvBlock(16, 16, (1, n_levels))
    self.inception = InceptionModule(16, 32)
    self.lstm = nn.LSTM(input_size=96, hidden_size=lstm_hidden, batch_first=True)
    self.fc = nn.Linear(lstm_hidden, n_classes)

  def forward(self, x):
    z = self.conv1(x)
    z = self.conv2(z)
    z = self.conv3(z)
    z = self.inception(z)
    z = z.squeeze(-1).permute(0, 2, 1)
    out, _ = self.lstm(z)
    logits = self.fc(out[:, -1])
    return logits

