# -*- coding: utf-8 -*-
"""Tranformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import torch
import torch.nn as nn
import math

class CausalSelfAttention(nn.Module):
    def __init__(self, d_model, n_heads, window=256):
        super().__init__()
        assert d_model % n_heads == 0
        self.d_module, self.n_heads, self.d_k = d_model, n_heads, d_model // n_heads
        self.window = window

        self.qkv = nn.Linear(d_model, 3 * d_model)
        self.out_proj = nn.Linear(d_model, d_model)

    def forward(self, x, kv_cache=None):
      B, T, D = x.shape
      qkv = self.qkv(x).view(B, T, 3, self.n_heads, self.d_k).permute(2, 0, 3, 1, 4)
      q, k, v = qkv[0], qkv[1], qkv[2]

      if kv_cache is not None:
        k = torch.cat([kv_cache['k'], k], dim=2)
        v = torch.cat([kv_cache["v"], v], dim=2)
        kv_cache['k'], kv_cache['v'] = k[:, :, -self.window:], v[:, :, -self.window:]

      scores = (q @ k.transpose(-2, -1)) / math.sqrt(self.d_k)

      Tq, Tk = scores.shape[-2], scores.shape[-1]
      idx_q = torch.arange(Tq).unsqueeze(1) + (Tk - Tq)
      idx_k = torch.arange(Tk).unsqueeze(0)
      mask = (idx_k > idx_q) | (idx_k < idx_q - self.window)
      scores = scores.masked_fill(mask, float("-inf"))

      attn = torch.softmax(scores, dim=-1)
      out = attn @ v
      out = out.transpose(1, 2).reshape(B, Tq, D)
      return self.out_proj(out), kv_cache

