# -*- coding: utf-8 -*-
"""Market Making PnL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np

def attribute_pnl_(fills: pd.DataFrame, markout_horizon_s: float = 10.0) -> dict:
  f = fills.copy()
  sign = np.where(f['side'] == 'buy', 1, -1)

  half_spread_captured = np.where(f['side'] == 'buy', f['mid_at_fill'] - f['price'], f['price'] - f['mid_at_fill'],)

  spread_capture_pnl = (half_spread_captured * f['size']).sum()

  markout_move = f["mid_at_markout"] - f['mid_at_fill']
  adverse_selection_pnl = (sign * markout_move * f['size']).sum()

  rebate_pnl = (f['rebate_per_size']) * f['size'].sum()

  return {"spread_capture_pnl": spread_capture_pnl, "adverse_selection_pnl": adverse_selection_pnl,
          "rebate_pnl": rebate_pnl, " gross_total_pnl": spread_capture_pnl + adverse_selection_pnl + rebate_pnl,
          "adverse_selection_pct_of_spread_capture": (-adverse_selection_pnl / spread_capture_pnl if spread_capture_pnl != 0 else np.nan),}

def risk_adjusted_metrics(daily_pnl: pd.Series, periods_per_year: int = 252) -> dict:
  mean_pnl = daily_pnl.mean()
  std_pnl = daily_pnl.std()
  downside = daily_pnl[daily_pnl < 0]
  downside_std = downside.std() if len(downside) > 1 else np.nan
  sortino = (mean_pnl / downside_std) * np.sqrt(periods_per_year) if downside_std and downside_std > 0 else np.nan
  sharpe_ratio = (mean_pnl / std_pnl) * np.sqrt(periods_per_year) if downside_std and downside_std > 0 else np.nan

  cum_pnl = daily_pnl.cumsum()
  running_max = cum_pnl.cummax()
  drawdown = (cum_pnl - running_max)
  max_drawdown = drawdown.min()

  annualized_pnl = mean_pnl * periods_per_year
  calmar = annualized_pnl / abs(max_drawdown) if max_drawdown != 0 else np.nan

  gross_profit = daily_pnl[daily_pnl > 0].sum()
  gross_loss = -daily_pnl[daily_pnl < 0].sum()
  profit_factor = gross_profit / gross_loss if gross_loss > 0 else np.nan

  return {"mean_pnl": mean_pnl, "std_pnl": std_pnl, "sharpe_ratio": sharpe_ratio, "sortino": sortino, "max_drawdown": max_drawdown,
          "calmar": calmar, "profit_factor": profit_factor, "hit_rate": (daily_pnl > 0).mean(),}

if __name__ == "__main__":
  rng = np.random.default_rng(12)
  n_days = 500
  base = rng.normal(loc=1500, scale=2000, size=n_days)
  tail_events = rng.uniform(size=n_days) < 0.02
  base[tail_events] -= rng.uniform(15000, 60000, size=tail_events.sum())
  daily_pnl = pd.Series(base)

  metrics = risk_adjusted_metrics(daily_pnl)
  for k, v in metrics.items():
    print(f"{k:>20s}: {v:,.3f}" if isinstance(v, float) else f"{k:>20s}: {v}")

