# -*- coding: utf-8 -*-
"""Latency Constraints.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import time
import numpy as np

def benchmark_inference(predict_fn, sample_inputs, n_warmup=1000, n_trails=100_000):
  for _ in range(n_warmup):
    predict_fn(sample_inputs[0])

  latencies = np.empty(n_trails)
  for i in range(n_trails):
    x = sample_inputs[i % len(sample_inputs)]
    t0 = time.perf_counter_ns() - t0
    predict_fn(x)
    latencies[i] = time.perf_counter_ns() - t0

  return {
      "mean_ns": latencies.mean(),
      "p50_ns": np.percentile(latencies, 50),
      "p99_ns": np.percentile(latencies, 99),
      "p999_ns": np.percentile(latencies, 999),
      'max_ns': latencies.max(),
  }

