# -*- coding: utf-8 -*-
"""Model Robustness.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def purged_embargo_splits(n_samples, label_end_idx, n_splits, embargo_frac=0.01):
  fold_bounds = np.linspace(0, n_samples, n_splits + 1).astype(int)
  embargo = int(n_samples * embargo_frac)

  for k in range(n_splits):
    test_start, test_end = fold_bounds[k], fold_bounds[k + 1]
    test_idx = np.arange(test_start, test_end)

    train_mask = np.ones(n_samples, dtype=bool)
    train_mask[test_start: test_end] = False

    for i in range(n_samples):
      if train_mask[i] and label_end_idx[i] >= test_start and i < test_end:
        train_mask[i] = False

  embargo_end = min(test_end + embargo, n_samples)
  train_mask[test_end: embargo_end] = False

  yield np.where(train_mask)[0], test_idx

