# -*- coding: utf-8 -*-
"""Micro Price Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np
from numba import njit

@njit
def compute_microprice_l1(bid_price, ask_price, bid_size, ask_size):
  total = bid_size + ask_size
  if total == 0:
    return 0.5 * (bid_price + ask_price), 0.0

  imbalance = (bid_size - ask_size) / total
  mid = 0.5 * (bid_price + ask_price)
  spread = ask_price - bid_price
  microprice = mid + 0.5 * spread * imbalance
  return microprice, imbalance

def compute_microprice_generalized(bid_prices, ask_prices, bid_sizes, ask_sizes, n_levels=10):
  bids = bid_prices[:, :n_levels]
  asks = ask_prices[:, :n_levels]
  bsz = bid_sizes[:, :n_levels]
  asz = ask_sizes[:, :n_levels]

  total_value = (bids * bsz).sum(axis=1) + (asks * asz).sum(axis=1)
  total_size = bsz.sum(axis=1) + asz.sum(axis=1)

  return total_value / total_size

def calibrate_microprice_signal(mid_prices, imbalances, ewma_half_life=100):
  from sklearn.linear_model import LinearRegression

  alpha_ewma = 1.0 - np.exp(-np.log(2) / ewma_half_life)
  ewma = pd.Series(mid_prices).ewm(alpha=alpha_ewma).mean().values

  delta_mid = np.diff(mid_prices)
  I_t = imbalances[:-1]
  dev_t = (mid_prices[:-1] - ewma[:-1])

  X = np.column_stack([I_t, dev_t])
  y = delta_mid

  mask = np.isfinite(X).all(axis =1) & np.isfinite(y)
  model = LinearRegression(fit_intercept=False)
  model.fit(X[mask], y[mask])

  alpha, beta = model.coef_
  r2 = model.score(X[mask], y[mask])
  print(f"alpha={alpha:.6f}, beta = {beta:.6f}, R2 ={r2:.4f}")
  return alpha, beta

from numba.np.ufunc.wrappers import build_slow_loop_body
np.random.seed(12)
T = 100000
bid_price = 100.0 + np.cumsum(np.random.randn(T) * 0.01)
ask_price = bid_price + 0.01
bid_size = np.maximum(100, np.random.exponential(500, T))
ask_size = np.maximum(100, np.random.exponential(500, T))
microprices = np.array([compute_microprice_l1(bid_price[i], ask_price[i], bid_size[i], ask_size[i])[0] for i in range(T)])

imbalances = (bid_size - ask_size) / (bid_size + ask_size)
alpha, beta = calibrate_microprice_signal(bid_price, imbalances)

