# -*- coding: utf-8 -*-
"""Queue Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.stats import norm

class QueueSignalBuilder:
  def __init__(self, n_levels=10, decay_rho=1.0):
    self.n_levels = n_levels
    self.decay_rho = decay_rho
    self.weights = np.exp(-decay_rho * np.arange(n_levels))
    self.weights /= self.weights.sum()

  def compute_l1_imbalance(self, bid_sizes, ask_sizes):
    total = bid_sizes[:, 0] + ask_sizes[:, 0]
    return (bid_sizes[:, 0] - ask_sizes[:, 0]) / np.where(
        total > 0, total, 1)

  def compute_nqi(self, bid_sizes, ask_sizes):
    q_b = bid_sizes[:, 0]
    q_a = ask_sizes[:, 0]
    denom = np.sqrt(np.maximum(q_b + q_a, 1))
    return (q_b - q_a) / denom

  def compute_multilevel_imbalance(self, bid_sizes, ask_sizes):
    w = self.weights[:self.n_levels]
    wb = (bid_sizes[:, :self.n_levels] * w[np.newaxis, :]).sum(axis=1)
    wa = (ask_sizes[:, :self.n_levels] * w[np.newaxis, :]).sum(axis=1)
    total = wb + wa
    return (wb - wa) / np.where(total > 0, total, 1)

  def compute_cst_tick_prob(self, bid_sizes, ask_sizes):
    q_b = bid_sizes[:, 0].astype(float)
    q_a = ask_sizes[:, 0].astype(float)
    z = (q_b - q_a) / np.sqrt(np.maximum(q_b + q_a, 1))
    return norm.cdf(z)

  def compute_queue_slope(self, bid_prices, ask_prices,
                          bid_sizes, ask_sizes):
    bid_dp = bid_prices[:, 0] - bid_prices[:, 1]
    ask_dp = ask_prices[:, 1] - ask_prices[:, 0]

    bid_dp = np.where(bid_dp > 0, bid_dp, 1e-8)
    ask_dp = np.where(ask_dp > 0, ask_dp, 1e-8)

    bid_slope = bid_sizes[:, 0] / bid_dp
    ask_slope = ask_sizes[:, 0] / ask_dp
    return bid_slope - ask_slope

  def compute_all_signals(self, bid_prices, ask_prices,
                          bid_sizes, ask_sizes):
    return pd.DataFrame({
        'l1_imbalance': self.compute_l1_imbalance(bid_sizes, ask_sizes),
        'nqi': self.compute_nqi(bid_sizes, ask_sizes),
        'ml_imbalance': self.compute_multilevel_imbalance(bid_sizes, ask_sizes),
        'cst_prob': self.compute_cst_tick_prob(bid_sizes, ask_sizes),
        'queue_slope': self.compute_queue_slope(bid_prices, ask_prices,
                                                 bid_sizes, ask_sizes),
    })


def compute_car_signal(event_df, window_ms=500):
  event_df = event_df.sort_values('timestamp_ms').copy()

  results = []
  for ts in event_df['timestamp_ms'].values:
    window = event_df[(event_df['timestamp_ms'] > ts - window_ms) &
                      (event_df['timestamp_ms'] <= ts)]

    for side in ['bid', 'ask']:
      side_data = window[window['side'] == side]
      added = side_data[side_data['event_type'] == 'add']['size'].sum()
      cancelled = side_data[side_data['event_type'] == 'cancel']['size'].sum()
      car = cancelled / (added + 1e-8)
      results.append({'timestamp_ms': ts, 'side': side, 'car': car})

  df = pd.DataFrame(results)
  bid_car = df[df['side'] == 'bid'][['timestamp_ms', 'car']].rename(
      columns={'car': 'bid_car'})
  ask_car = df[df['side'] == 'ask'][['timestamp_ms', 'car']].rename(
      columns={'car': 'ask_car'})
  return bid_car.merge(ask_car, on='timestamp_ms')

