# -*- coding: utf-8 -*-
"""Flow Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from numba import njit

@njit
def lee_ready_classify(trade_price, mid_before, prev_price):
  if trade_price > mid_before:
    return 1
  elif trade_price < mid_before:
    return -1
  elif trade_price > prev_price:
    return 1
  elif trade_price < prev_price:
    return -1
  else:
    return 0


@njit
def compute_ofi_series(bid_prices_l1, ask_prices_l1,
                       bid_sizes_l1, ask_sizes_l1):
  n = len(bid_prices_l1)
  ofi_events = np.zeros(n)

  for t in range(1, n):
    if bid_prices_l1[t] == bid_prices_l1[t-1]:
      e_b = bid_sizes_l1[t] - bid_sizes_l1[t-1]
    elif bid_prices_l1[t] > bid_prices_l1[t-1]:
      e_b = bid_sizes_l1[t]
    else:
      e_b = -bid_sizes_l1[t-1]

    if ask_prices_l1[t] == ask_prices_l1[t-1]:
      e_a = ask_sizes_l1[t] - ask_sizes_l1[t-1]
    elif ask_prices_l1[t] < ask_prices_l1[t-1]:
      e_a = -ask_sizes_l1[t]
    else:
      e_a = ask_sizes_l1[t-1]

    ofi_events[t] = e_b - e_a

  return ofi_events


def compute_rolling_ofi(ofi_events, timestamps_ms, window_ms=1000):
  ofi_series = pd.Series(ofi_events, index=timestamps_ms)
  rolling_ofi = ofi_series.rolling(
      window=pd.Timedelta(milliseconds=window_ms),
      min_periods=1
  ).sum()
  return rolling_ofi.values


def compute_vpin(trade_df, bucket_size_shares, n_buckets=50):
  trade_df = trade_df.copy()
  trade_df['cum_vol'] = trade_df['size'].cumsum()
  trade_df['bucket'] = (trade_df['cum_vol'] /
                        bucket_size_shares).astype(int)

  bucket_df = trade_df.groupby('bucket').agg(
      buy_vol=('size', lambda x: x[trade_df.loc[x.index, 'direction'] == 1].sum()),
      sell_vol=('size', lambda x: x[trade_df.loc[x.index, 'direction'] == -1].sum()),
      total_vol=('size', 'sum')
  )

  bucket_df['imb'] = np.abs(bucket_df['buy_vol'] - bucket_df['sell_vol'])

  vpin = (bucket_df['imb'].rolling(n_buckets).mean() /
          bucket_size_shares)

  return vpin


def compute_flow_signals(trades_df, lob_df, windows_ms=[100, 500,
                                                       2000, 10000]):
  merged = pd.merge_asof(
      trades_df.sort_values('timestamp_ms'),
      lob_df.sort_values('timestamp_ms'),
      on='timestamp_ms', direction='backward'
  )

  results = {'timestamp_ms': lob_df['timestamp_ms'].values}

  ofi_events = compute_ofi_series(
      lob_df['bid_p1'].values, lob_df['ask_p1'].values,
      lob_df['bid_s1'].values, lob_df['ask_s1'].values
  )
  for w in windows_ms:
    results[f'ofi_{w}ms'] = compute_rolling_ofi(
        ofi_events, lob_df['timestamp_ms'].values, window_ms=w)

  ts_idx = pd.to_datetime(trades_df['timestamp_ms'], unit='ms')
  trades_ts = trades_df.set_index(ts_idx)

  for w in windows_ms:
    w_str = f'{w}ms'
    buy_vol = trades_ts[trades_ts['direction'] == 1]['size'].rolling(w_str).sum()
    sell_vol = trades_ts[trades_ts['direction'] == -1]['size'].rolling(w_str).sum()

  return pd.DataFrame(results)

