# -*- coding: utf-8 -*-
"""Liquidity Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from sklearn . linear_model import LinearRegression

class LiquiditySignalEngine :
  def compute_spread_signals ( self , bid_p , ask_p , trade_p = None ,
                              trade_dir = None , mid_future = None ) :
    mid = 0.5 * ( bid_p + ask_p )
    quoted = ask_p - bid_p
    rel = quoted / mid

    result = {
        'mid' : mid ,
        'quoted_spread' : quoted ,
        'rel_spread' : rel ,
    }

    if trade_p is not None and trade_dir is not None :
      result ['eff_spread'] = 2.0 * trade_dir * ( trade_p - mid )

    if mid_future is not None and trade_dir is not None :
      result ['realized_spread'] = 2.0 * trade_dir * ( trade_p - mid_future )
    result ['price_impact'] = 2.0 * trade_dir * ( mid_future - mid )
    return result

  def estimate_kyle_lambda ( self , signed_flow , mid_returns ,
                             window =200 , min_obs =50) :
    n = len( signed_flow )
    lambdas = np . full (n , np . nan )

    for t in range ( window , n ) :
      x = signed_flow [t - window : t ]. reshape ( -1 , 1)
      y = mid_returns [t - window : t ]
      mask = np . isfinite ( x . ravel () ) & np . isfinite ( y )
      if mask .sum () < min_obs :
        continue
      model = LinearRegression ( fit_intercept = False )
      model . fit ( x [ mask ] , y [ mask ])
      lambdas [ t ] = model . coef_ [0]

    return lambdas

  def compute_amihud_intraday ( self , mid_changes , dollar_volumes ,
                                window =20) :
    illiq = ( np .abs( mid_changes ) / ( dollar_volumes + 1e-8) ) * 1e6

    return pd . Series ( illiq ) . rolling ( window ) . mean () . values

  def compute_resilience ( self , ask_sizes , trade_events ,
                           window_events =20 , theta =0.8) :
    n = len( ask_sizes )
    recovery_times = []

    for t in range ( n - window_events ) :
      if not trade_events [ t ]:
        continue
      pre_size = ask_sizes [t -1] if t > 0 else ask_sizes [ t ]
      target = pre_size * theta

      recovered = False
      for k in range (1 , window_events + 1) :
        if ask_sizes [ t + k ] >= target :
          recovery_times . append ( k )
          recovered = True
          break
      if not recovered :
        recovery_times . append ( window_events )

    if not recovery_times :
      return np . ones ( n )

    mean_recovery = np . mean ( recovery_times )

    return 1.0 / mean_recovery

  def compute_lar_signal ( self , bid_sizes_5levels ,
                           ask_sizes_5levels ,
                           n_ticks =3) :
    bid_depth = bid_sizes_5levels [: , : n_ticks ]. sum( axis =1)
    ask_depth = ask_sizes_5levels [: , : n_ticks ]. sum( axis =1)
    total = bid_depth + ask_depth
    return ( ask_depth - bid_depth ) / np . where ( total > 0 ,
                                                  total , 1)

def interpret_lambda_regime ( lambda_series , percentile_window =250) :
  current = lambda_series [ -1]
  historical = lambda_series [ - percentile_window :]
  historical = historical [ np . isfinite ( historical ) ]

  p75 = np . percentile ( historical , 75)
  p90 = np . percentile ( historical , 90)

  if current < p75 :
    return 'normal' , 1.0
  elif current < p90 :
    return 'stressed' , 0.6
  else :
    return 'crisis' , 0.3

