# -*- coding: utf-8 -*-
"""Volatility Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.ndimage import gaussian_filter1d

class IntraVolSignals :
  def compute_realized_variance ( self , log_returns , method ='standard' ) :
    if method == 'standard' :
      return np .sum( log_returns **2)
    elif method == 'tsrv' :
      return self . _two_scale_rv ( log_returns )
    elif method == 'rk' :
      return self . _realized_kernel ( log_returns )

  def _two_scale_rv ( self , r , n_fast = None ) :
    n = len( r )
    if n_fast is None :
      n_fast = max(int( np . sqrt ( n ) ) , 5)

    rv_fast = np .sum( r **2)

    r_slow = r [:: n_fast ]
    rv_slow = np .sum( r_slow **2)

    n_slow = len( r_slow )
    tsrv = ( n_slow / ( n_slow - n_fast ) ) * rv_slow - \
           ( n_fast / ( n_slow - n_fast ) ) * rv_fast
    return max( tsrv , 0.0)

  def _realized_kernel ( self , r , bandwidth_const =0.5) :
    n = len( r )
    H = max (1 , int( bandwidth_const * ( n ** 0.6) ) )

    def parzen ( x ) :
      ax = abs( x )
      if ax <= 0.5:
        return 1 - 6* ax **2 + 6* ax **3
      elif ax <= 1.0:
        return 2*(1 - ax ) **3
      return 0.0

    rk = np .sum( r **2)
    for h in range (1 , H +1) :
      gamma_h = np .sum( r [ h :] * r [: - h ])
      k_h = parzen ( h / ( H +1) )
      rk += 2 * k_h * gamma_h
    return max( rk , 0.0)

  def estimate_diurnal_schedule ( self , intraday_returns_df ,
                                  bar_minutes =5 , smooth_sigma =3):
    df = intraday_returns_df . copy ()
    df ['time_of_day'] = df . index . hour * 60 + df . index . minute

    schedule = df . groupby ('time_of_day') ['return']. apply (
        lambda x : np . sqrt ( np . mean ( x **2) )
    )
    schedule = schedule / schedule . mean ()

    schedule_smooth = gaussian_filter1d ( schedule . values ,
                                        sigma = smooth_sigma )

    return pd . Series ( schedule_smooth , index = schedule . index )

  def compute_har_features ( self , rv_daily , horizons =[1 , 5 , 22]) :
    T = len( rv_daily )
    X = np . full (( T , len( horizons ) ) , np . nan )

    for j , h in enumerate ( horizons ) :
      for t in range (h -1 , T ) :
        X [t , j ] = np . mean ( rv_daily [t - h +1: t +1])

    return X

  def compute_realized_skewness ( self , log_returns ):
    n = len( log_returns )
    rv = np .sum( log_returns **2)
    if rv <= 0 or n < 3:
      return 0.0
    m3 = np .sum( log_returns **3)
    return ( n / (( n -1) *( n -2) ) ) * m3 / ( rv ** 1.5)

  def vol_regime_signal ( self , sigma_series , lookback =100 ,
                          threshold_sigmas =2.0):
    mu = pd . Series ( sigma_series ) . rolling ( lookback ) . mean () . values
    sig = pd . Series ( sigma_series ) . rolling ( lookback ) . std () . values

    return ( sigma_series > mu + threshold_sigmas * sig ) . astype (int )

  def compute_vol_ratio ( self , log_returns , fast_window =12 ,
                          slow_window =60):
    returns_sq = log_returns ** 2
    rv_fast = pd . Series ( returns_sq ).rolling(fast_window).mean().values
    rv_slow = pd . Series ( returns_sq ).rolling(slow_window).mean().values

    return np.where(rv_slow > 0, rv_fast / rv_slow, 1.0)

