# -*- coding: utf-8 -*-
"""Mean Reversion Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from statsmodels.tsa.stattools import coint, adfuller
from scipy.optimize import minimize

class MeanReversionSignals:
  def estimate_ou_params(self, prices, dt):
    X = np.log(prices) if prices.min() > 0 else prices
    x_t = X[:-1]
    x_tp1 = X[1:]

    A = np.column_stack([np.ones(len(x_t)), x_t])
    coeffs, residuals, _, _ = np.linalg.lstsq(A, x_tp1, rcond=None)

    a_hat, b_hat = coeffs

    kappa = -np.log(b_hat) / dt
    theta = a_hat / (1 - b_hat)
    eps = x_tp1 - a_hat - b_hat * x_t
    sigma_sq = np.var(eps) * 2 * kappa / (1 - np.exp(-2 * kappa * dt))

    sigma = np.sqrt(max(sigma_sq, 1e-10))
    half_life = np.log(2) / kappa

    return {
        'kappa': kappa,
        'theta': theta,
        'sigma': sigma,
        'half_life': half_life / dt,
    }

  def ou_signal(self, prices, dt, window=200):
    X = np.log(prices) if prices.min() > 0 else prices
    n = len(X)
    signal = np.full(n, np.nan)

    for t in range(window, n):
      params = self.estimate_ou_params(
          np.exp(X[t - window : t]) if prices.min() > 0 else X[t - window : t],
          dt
      )
      theta = params['theta']
      sigma = params['sigma']
      kappa = params['kappa']
      signal[t] = -(X[t] - theta) * kappa / (sigma + 1e-10)

    return signal

  def compute_vwap_signal(self, prices, volumes, window_bars=None):
    pv = prices * volumes

    if window_bars is None:
      vwap = np.cumsum(pv) / (np.cumsum(volumes) + 1e-8)
    else:
      vwap = pd.Series(pv).rolling(window_bars).sum().values / \
             (pd.Series(volumes).rolling(window_bars).sum().values + 1e-8)

    deviation = prices - vwap
    sigma_dev = pd.Series(deviation).rolling(
        min(window_bars or 100, 100)).std().values
    return -deviation / (sigma_dev + 1e-10)


  def pairs_signal(self, log_prices_x, log_prices_y,
                   estimation_window=500, z_entry=2.0, z_exit=0.5):
    n = len(log_prices_x)
    signal = np.zeros(n)
    spread_z = np.full(n, np.nan)
    beta_arr = np.full(n, np.nan)

    for t in range(estimation_window, n):
      X = log_prices_x[t - estimation_window : t]
      Y = log_prices_y[t - estimation_window : t]

      A = np.column_stack([np.ones(estimation_window), X])
      coeffs, _, _, _ = np.linalg.lstsq(A, Y, rcond=None)
      beta_hat = coeffs[1]

      spread = Y - beta_hat * X
      mu_s = spread.mean()
      sig_s = spread.std() + 1e-10

      Z_current = log_prices_y[t] - beta_hat * log_prices_x[t]

      z_t = (Z_current - mu_s) / sig_s

      spread_z[t] = z_t
      beta_arr[t] = beta_hat

      if z_t < -z_entry:
        signal[t] = 1
      elif z_t > z_entry:
        signal[t] = -1
      elif abs(z_t) < z_exit:
        signal[t] = 0
      else:
        signal[t] = signal[t-1]

    return signal, spread_z, beta_arr

  def test_mean_reversion(self, prices, max_lag=20):
    log_p = np.log(prices)
    result = adfuller(log_p, maxlag=max_lag, regression='c')

    adf_stat, p_value = result[0], result[1]
    is_mean_reverting = p_value < 0.05

    params = self.estimate_ou_params(prices, dt=1.0)
    return {
        'adf_stat': adf_stat,
        'p_value': p_value,
        'is_mean_reverting': is_mean_reverting,
        'half_life_bars': params['half_life'],
    }

