# -*- coding: utf-8 -*-
"""Momentum Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd

class IntraMomentumSignals:
  def ewma_crossover(self, prices, fast_hl_bars, slow_hl_bars):
    fast_alpha = 1 - np.exp(-np.log(2) / fast_hl_bars)
    slow_alpha = 1 - np.exp(-np.log(2) / slow_hl_bars)

    ewma_fast = pd.Series(prices).ewm(alpha=fast_alpha).mean().values
    ewma_slow = pd.Series(prices).ewm(alpha=slow_alpha).mean().values

    raw = ewma_fast - ewma_slow

    sigma = pd.Series(raw).rolling(252).std().values
    return raw / (sigma + 1e-10)

  def return_momentum(self, prices, horizons=[5, 15, 60, 240],
                      vol_norm=True, window_vol=100):
    log_p = np.log(prices)
    signals = {}
    for h in horizons:
      ret = np.full(len(prices), np.nan)
      ret[h:] = log_p[h:] - log_p[:-h]

      if vol_norm:
        vol = pd.Series(ret).rolling(window_vol).std().values
        signals[f'mom_{h}'] = ret / (vol + 1e-10)
      else:
        signals[f'mom_{h}'] = ret

    return pd.DataFrame(signals)

  def price_acceleration(self, prices, dt=1.0, smooth=3):
    log_p = np.log(prices)
    r = np.diff(log_p, prepend=log_p[0])
    acc = np.diff(r, prepend=r[0]) / dt

    if smooth > 1:
      acc = pd.Series(acc).rolling(smooth).mean().values

    sigma = pd.Series(acc).rolling(100).std().values
    return acc / (sigma + 1e-10)

  def cumulative_delta(self, buy_vols, sell_vols,
                       windows_bars=[10, 50, 200]):
    delta = buy_vols - sell_vols
    signals = {}

    for w in windows_bars:
      cd = pd.Series(delta).rolling(w).sum().values
      sigma_cd = pd.Series(cd).rolling(w * 5).std().values
      signals[f'cd_{w}'] = cd / (sigma_cd + 1e-10)

    return pd.DataFrame(signals)

  def open_momentum_signal(self, prices, session_open_idx,
                           open_window_bars=6):
    n = len(prices)
    signal = np.zeros(n)

    for open_i in session_open_idx:
      if open_i + open_window_bars >= n:
        break
      r_open = np.log(prices[open_i + open_window_bars] /
                      prices[open_i])

      close_start = max(open_i + open_window_bars,
                        n - open_window_bars - 1)
      signal[close_start:] = np.sign(r_open)

    return signal

  def vpt_signal(self, prices, volumes, window=50):
    log_ret = np.diff(np.log(prices), prepend=np.log(prices[0]))

    vpt = np.cumsum(volumes * log_ret)

    sigma_vpt = pd.Series(vpt).rolling(window).std().values
    z_vpt = vpt / (sigma_vpt + 1e-10)

    price_dir = np.sign(pd.Series(prices).rolling(window).mean().values
                       - pd.Series(prices).rolling(window * 2).mean().values)

    vpt_dir = np.sign(pd.Series(vpt).rolling(window).mean().values
                     - pd.Series(vpt).rolling(window * 2).mean().values)

    divergence = price_dir * vpt_dir

    return pd.DataFrame({
        'vpt': vpt,
        'vpt_z': z_vpt,
        'divergence': divergence,
    })

  def macd_signal(self, prices, fast_span=12, slow_span=26,
                  signal_span=9):
    log_r = pd.Series(np.diff(np.log(prices), prepend=np.log(prices[0])))

    ema_fast = log_r.ewm(span=fast_span, adjust=False).mean().values
    ema_slow = log_r.ewm(span=slow_span, adjust=False).mean().values
    macd = ema_fast - ema_slow
    signal_line = pd.Series(macd).ewm(span=signal_span,
                                     adjust=False).mean().values
    histogram = macd - signal_line

    sigma_h = pd.Series(histogram).rolling(100).std().values

    return pd.DataFrame({
        'macd': macd,
        'signal': signal_line,
        'histogram': histogram,
        'hist_z': histogram / (sigma_h + 1e-10),
    })

