# -*- coding: utf-8 -*-
"""Multi-Signal Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.linear_model import Ridge , RidgeCV
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings ('ignore')

class MultiSignalCombiner :
  def __init__ ( self , risk_aversion =1.0 , tc_linear =0.0005 ,
                 tc_quad =0.002) :
    self . gamma = risk_aversion
    self . lam = tc_linear
    self . eta = tc_quad

  def compute_ics ( self , signal_matrix , forward_returns ,
                   normalize = True ) :
    K = signal_matrix . shape [1]
    ic_vec = np . zeros ( K )

    for k in range ( K ) :
      z = signal_matrix [: , k ]
      mask = np . isfinite ( z ) & np . isfinite ( forward_returns )
      if mask .sum () < 50:
        continue
      ic_vec [ k ] = np . corrcoef ( z [ mask ] , forward_returns [ mask

] ) [0 , 1]

    mask_all = np .all( np . isfinite ( signal_matrix ) , axis =1) & \
               np . isfinite ( forward_returns )
    S = signal_matrix [ mask_all ]
    if normalize :
      S = ( S - S . mean (0) ) / ( S . std (0) + 1e-10)
    sig_cov = np . cov ( S . T )

    return ic_vec , sig_cov

  def optimal_linear_weights ( self , ic_vec , sig_cov ,
                               regularize_alpha =1e-4) :
    K = len( ic_vec )
    reg_cov = sig_cov + regularize_alpha * np . eye ( K )

    w = np . linalg . solve ( reg_cov , ic_vec )

    norm = np . sqrt ( np . dot (w , np . dot ( sig_cov , w ) ) )
    if norm > 0:
      w = w / norm

    return w

  def gram_schmidt_orthogonalize ( self , signal_matrix ) :
    T , K = signal_matrix . shape
    Z = signal_matrix . copy () . astype ( float )
    ortho = np . zeros_like ( Z )

    for k in range ( K ) :
      v = Z [: , k ]. copy ()
      for j in range ( k ) :
        u = ortho [: , j ]
        v_u = np . nansum ( v * u ) / ( np . nansum ( u **2) + 1e-10)

        v = v - v_u * u
      norm_v = np . sqrt ( np . nansum ( v **2) )
      ortho [: , k ] = v / ( norm_v + 1e-10)

    return ortho

  def pca_combination ( self , signal_matrix , n_components =3) :
    mask = np .all( np . isfinite ( signal_matrix ) , axis =1)
    S = signal_matrix [ mask ]

    scaler = StandardScaler ()
    S_std = scaler . fit_transform ( S )

    pca = PCA ( n_components = n_components )
    pca . fit ( S_std )

    S_full = scaler . transform (
        np . where ( np . isfinite ( signal_matrix ) , signal_matrix ,
                   np . nanmean ( signal_matrix , axis =0) ) )
    pc_scores = pca . transform ( S_full )

    explained = pca . explained_variance_ratio_
    print ( f" Variance explained by { n_components } PCs: "
           f" { explained .sum () :.1%} ")
    return pc_scores , pca , scaler

  def regime_conditional_combination ( self , signal_matrix ,
                                      forward_returns ,
                                      regime_indicators ) :
    unique_regimes = np . unique ( regime_indicators )
    regime_weights = {}
    for r in unique_regimes :
      mask = regime_indicators == r
      if mask .sum () < 100:
        print ( f" Regime {r}: too few samples ({ mask .sum ()}), skipping ")

        continue

      S_r = signal_matrix [ mask ]
      y_r = forward_returns [ mask ]

      ic_r , cov_r = self . compute_ics ( S_r , y_r )
      w_r = self . optimal_linear_weights ( ic_r , cov_r )
      regime_weights [ r ] = w_r

      combined_ic = np . dot ( w_r , ic_r ) / (
          np . sqrt ( np . dot ( w_r , np . dot ( cov_r , w_r ) ) ) + 1e-10)
      print ( f" Regime {r}: n={ mask .sum ()} , combined IC ={combined_ic :.4f}")

    return regime_weights

  def apply_regime_conditional ( self , signal_matrix ,
                                 regime_indicators ,
                                 regime_weights ) :
    T , K = signal_matrix . shape
    combined = np . zeros ( T )

    for t in range ( T ) :
      r = regime_indicators [ t ]
      if r in regime_weights :
        combined [ t ] = np . dot ( regime_weights [ r ] ,
                                  signal_matrix [ t ])

    return combined

  def tc_aware_position_sizing ( self , raw_signal , sigma_hat ,
                                 prev_positions = None ) :
    T = len( raw_signal )

    q_aim = raw_signal / ( self . gamma * sigma_hat **2 + 1e-10)
    rho = 1.0 / np . sqrt (1 + 2 * self . eta * self . gamma * sigma_hat **2)

    rho = np . clip ( rho , 0.01 , 0.99)

    q = np . zeros ( T )
    if prev_positions is not None :
      q [0] = prev_positions

    for t in range (1 , T ) :
      q [ t ] = (1 - rho [ t ]) * q [t -1] + rho [ t ] * q_aim [ t ]

    trades = np . diff (q , prepend = q [0])
    tc_cost = self . lam * np .abs( trades ) + self . eta * trades **2

    return q , tc_cost

  def ml_signal_combination ( self , signal_matrix ,
                              forward_returns ,
                              train_frac =0.7) :
    T = len( forward_returns )
    split = int( T * train_frac )

    X_train = signal_matrix [: split ]
    y_train = forward_returns [: split ]
    X_test = signal_matrix [ split :]
    y_test = forward_returns [ split :]

    mask_train = np .all( np . isfinite ( X_train ) , axis =1) & np .isfinite ( y_train )

    mask_test = np .all( np . isfinite ( X_test ) , axis =1) & np .isfinite ( y_test )

    scaler = StandardScaler ()
    X_tr = scaler . fit_transform ( X_train [ mask_train ])

    model = RidgeCV ( alphas = np . logspace ( -4 , 2 , 20) , cv =5)
    model . fit ( X_tr , y_train [ mask_train ])

    X_te = scaler . transform ( X_test [ mask_test ])
    pred = model . predict ( X_te )

    oos_ic = np . corrcoef ( pred , y_test [ mask_test ]) [0 , 1]
    print ( f"OOS IC ( Ridge ): { oos_ic :.4f} , alpha ={ model . alpha_:.4f}")
    return model , scaler , oos_ic


def build_gbt_signal_model ( signal_matrix , forward_returns ,
                             n_estimators =300 , max_depth =4) :
  try:
    import lightgbm as lgb
  except ImportError :
    print (" lightgbm not installed . pip install lightgbm ")
    return None

  T = len( forward_returns )
  split = int( T * 0.7)

  X_train , y_train = signal_matrix [: split ] , forward_returns [: split ]

  X_test , y_test = signal_matrix [ split :] , forward_returns [ split :]


  mask_tr = np .all( np . isfinite ( X_train ) , axis =1) & np . isfinite (
y_train )

  mask_te = np .all( np . isfinite ( X_test ) , axis =1) & np . isfinite (
y_test )

  model = lgb . LGBMRegressor (
      n_estimators = n_estimators , max_depth = max_depth ,
      learning_rate =0.05 , min_child_samples =50 ,
      reg_alpha =0.1 , reg_lambda =1.0 , random_state =42
  )
  model . fit ( X_train [ mask_tr ] , y_train [ mask_tr ] ,
              eval_set =[( X_test [ mask_te ] , y_test [ mask_te ]) ] ,
              callbacks =[ lgb . early_stopping (30) , lgb . log_evaluation (100) ])


  pred = model . predict ( X_test [ mask_te ])
  oos_ic = np . corrcoef ( pred , y_test [ mask_te ]) [0 , 1]
  print ( f"GBT OOS IC: { oos_ic :.4f}")

  return model , oos_ic

