# -*- coding: utf-8 -*-
"""Alpha Evaluation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy import stats

class AlphaEvaluator:
  def compute_ic(self, signal, forward_returns, method='pearson'):
    mask = np.isfinite(signal) & np.isfinite(forward_returns)
    z = signal[mask]
    r = forward_returns[mask]
    T = len(z)
    if T < 30:
      return {'ic':np.nan, 'se_nw':np.nan, 't_stat':np.nan}

    if method == 'pearson':
      ic = np.corrcoef(z , r)[0 ,1]
      e = z * r - ic
    elif method == 'spearman':
      ic , _ = stats . spearmanr (z , r )
      e = (stats.rankdata(z) - (T+1)/2) * (stats.rankdata(r) - (T+1)/2)
      e = e / ( T * np . std ( e ) + 1e-10) - ic

    L = max (1 , int (4 * ( T / 100) ** (2/9) ) )

    var_nw = np.var(e)

    for l in range(1 , L+1):
      gamma_l = np.mean(e[l:] * e[: - l ])
      var_nw += 2 * (1 - l /( L +1)) * gamma_l
      se_nw = np.sqrt(max( var_nw, 0) / T )
      t_stat = ic / (se_nw + 1e-10)

      return {'ic' : ic, 'se_nw': se_nw, 't_stat': t_stat, 'p_value': 2 * (1 - stats.norm.cdf(abs(t_stat))) ,'n_obs' : T,}

  def ic_decay_curve ( self , signal , returns , max_horizon =50):
    log_r = np . log ( returns / returns . shift (1) ) . values if isinstance ( returns , pd . Series ) else returns

    ic_curve = []
    for k in range (1 , max_horizon + 1) :
      fwd_ret = np . roll ( log_r , -k )
      fwd_ret [ - k :] = np . nan
      result = self . compute_ic ( signal , fwd_ret )
      ic_curve . append ({ 'horizon': k , ** result })

    df = pd . DataFrame ( ic_curve )
    valid = df . dropna ( subset =['ic'])
    if len( valid ) > 5:
      from scipy . optimize import curve_fit
      try:
        popt , _ = curve_fit (lambda k , ic0 , tau : ic0 * np . exp ( - k / tau ), valid ['horizon']. values ,valid ['ic']. values ,p0 =[ valid ['ic']. iloc [0] , 10] , maxfev =1000)
        df ['ic_fitted'] = popt[0] * np.exp(-df['horizon'] / popt[1])
        print ( f"IC decay : IC (0) ={ popt [0]:.4f} , half - life={ popt [1]* np.log (2) :.1f} bars ")

      except Exception :
        pass

    return df

  def walk_forward_analysis ( self , signal , forward_returns , n_blocks =10 , min_block_frac =0.6) :
    T = len( signal )
    block_size = T // n_blocks

    oos_results = []
    for m in range (1 , n_blocks ) :
      test_start = m * block_size
      test_end = min (( m +1) * block_size , T )

      sig_oos = signal [ test_start : test_end ]
      ret_oos = forward_returns [ test_start : test_end ]

      result = self . compute_ic ( sig_oos , ret_oos )
      oos_results . append ({
      'block' : m ,
      'start_idx' : test_start ,
      'end_idx' : test_end ,
      ** result
      })

    df = pd . DataFrame ( oos_results ) . dropna ( subset =['ic'])

    mean_ic = df ['ic']. mean ()
    pct_pos = ( df ['ic'] > 0) . mean ()
    icir = mean_ic / ( df ['ic']. std () + 1e-10)

    print ( f"\n- - - Walk - Forward Results ---")
    print ( f" Mean OOS IC : { mean_ic :.4f}")
    print ( f"% Positive IC : { pct_pos :.1%} ")
    print ( f"IC IR : { icir :.2f}")
    print ( f"Min IC : {df['ic']. min () :.4f}")
    print ( f"Max IC : {df['ic']. max () :.4f}")

    return df , {'mean_ic' : mean_ic , 'pct_pos' : pct_pos , 'icir': icir}

  def compute_signal_pnl ( self , signal , returns , sigma_target=0.01 ,
                         tc_bps =0.5 , holding_bars =10):
    sig_std = np . nanstd ( signal )
    pos = ( signal / ( sig_std + 1e-10) ) * sigma_target

    pos_held = pd . Series ( pos ) . rolling ( holding_bars ) . mean () . values

    raw_pnl = pos_held * returns
    trades = np . diff ( pos_held , prepend =0)
    tc = np .abs( trades ) * tc_bps * 1e-4

    net_pnl = raw_pnl - tc

    cum_net = np . nancumsum ( net_pnl )

    sharpe = np . nanmean ( net_pnl ) / ( np . nanstd ( net_pnl ) + 1e-10) * np . sqrt (252 * 78)

    print ( f" Annualized Sharpe (net): { sharpe :.2f}")

    return pd . DataFrame ({
    'raw_pnl' : raw_pnl ,
    'tc_cost' : tc ,
    'net_pnl' : net_pnl ,
    'cum_pnl' : cum_net ,
    })

  def deflated_sharpe_ratio ( self , sr_hat , n_trials , t_obs , sr_bench =1.0) :
    import scipy . stats as ss
    sr_max = ss . norm . ppf (1 - 1/ n_trials )

    var_sr = (1 + 0.5 * sr_hat **2) / ( t_obs - 1)

    dsr = ss . norm . cdf (
    ( sr_hat - sr_max ) / ( np . sqrt ( var_sr ) + 1e-10)
    )
    return dsr

