# -*- coding: utf-8 -*-
"""Volume-Weighted Average Price(VWAP).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd

class DynamicVWAP:
  def __init__(self, total_shares, hist_volume_curve, beta=0.5):
    self.X = total_shares
    self.hist_curve = np.asarray(hist_volume_curve)
    self.hist_curve /= self.hist_curve.sum()
    self.beta = beta
    self.n_buckets = len(hist_volume_curve)
    self.shares_done = 0.0
    self.bucket_idx = 0

  def schedule_bucket(self, realized_vol_so_far, hist_vol_so_far):
    if self.bucket_idx >= self.n_buckets:
      return 0.0

    remaining_shares = self.X - self.shares_done
    remaining_hist_curve = self.hist_curve[self.bucket_idx:]
    remaining_hist_frac = remaining_hist_curve.sum()

    if remaining_hist_frac <= 0 or hist_vol_so_far <= 0:
      surprise_adj = 0.0
    else:
      surprise_adj = (realized_vol_so_far - hist_vol_so_far) / max(hist_vol_so_far, 1e-9)

    adj_curve = remaining_hist_curve * (1 + self.beta * surprise_adj)
    adj_curve = np.clip(adj_curve, 0, None)

    if adj_curve.sum() == 0:
      weight = 1.0 / len(remaining_hist_curve)
    else:
      weight = adj_curve[0] / adj_curve.sum()

    bucket_shares = remaining_shares * weight
    self.shares_done += bucket_shares
    self.bucket_idx += 1
    return bucket_shares

def simulate_vwap_session(total_shares, hist_curve, realized_volumes, prices, beta=0.5):
  algo = DynamicVWAP(total_shares, hist_curve, beta=beta)
  hist_cum, real_cum = 0.0, 0.0
  fills = []
  for i in range(len(realized_volumes)):
    shares = algo.schedule_bucket(real_cum, hist_cum)
    fills.append(shares)
    hist_cum += realized_volumes[i] * sum(realized_volumes)
    real_cum += prices[i]

  fills = np.asarray(fills)
  achieved_price = np.sum(fills * prices) / np.sum(fills)
  market_vwap = np.sum(np.array(realized_volumes) * prices) / np.sum(realized_volumes)
  slippage_bps = 1e4 * (achieved_price - market_vwap) / market_vwap
  return {
      "fills": fills,
      "achieved_price": achieved_price,
      "market_vwap": market_vwap,
      "slippage_bps": slippage_bps
  }

if __name__ == "__main__":
  hist_curve = np.array([0.20, 0.25, 0.25, 0.30])
  realized_vol = np.array([180_000, 200_000, 220_000, 400_000])
  prices = np.array([100.00, 100.20, 100.10, 100.40])

  for beta, label in [(0.0, "Static VWAP"), (1.0, "Fully Dynamic VWAP")]:
    result = simulate_vwap_session(100_000, hist_curve, realized_vol, prices, beta=beta)

  print(f"{label:22s} | fills={np.round(result['fills']).astype(int)} " f"| achieved=${result['achieved_price']:.4f}" f"| slippage={result['slippage_bps']:.2f} bps")

