# -*- coding: utf-8 -*-
"""Time-Weighted Average Price(TWAP).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def randomized_twap_schedule(total_shares, horizon_seconds, n_slices, size_jitter=0.3, time_jitter_frac=0.25, seed=None):
  rng = np.random.default_rng(seed)
  base_interval = horizon_seconds / n_slices
  nominal_size = total_shares / n_slices

  raw_sizes = nominal_size * (1 + rng.uniform(-size_jitter, size_jitter, n_slices))
  sizes = raw_sizes * (total_shares / raw_sizes.sum())

  nominal_times = np.arange(1, n_slices + 1) * base_interval
  jitter = rng.uniform(-time_jitter_frac, time_jitter_frac, n_slices) * base_interval
  times = np.clip(nominal_times + jitter, 0, horizon_seconds)
  times.sort()

  return times, sizes

if __name__ == "__main__":
  times, sizes = randomized_twap_schedule(total_shares=50_000, horizon_seconds=1800, n_slices=20, seed=12)
  for t, s in zip(times, sizes):
    print(f"t={t:7.1f}s slice_size={s:8.1f} shares")
    print(f"Total scheduled: {sizes.sum():.1f} (target: 50000)")

