# -*- coding: utf-8 -*-
"""Percentage of Volume(POV).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

class POVExecutor:
  def __init__(self, total_shares, target_rate, adaptive=False, kappa_vol=2.0, kappa_spread=1.5):
    self.X_remaining = total_shares
    self.rho_target_total = target_rate

    self.rho = self.rho_target_total / (1 - self.rho_target_total)
    self.adaptive = adaptive
    self.kappa_vol = kappa_vol
    self.kappa_spread = kappa_spread
    self.shares_done = 0.0

  def step(self, other_market_volume, realized_vol_zscores=0.0, spread_zscores=0.0):
    if self.X_remaining <= 0:
      return 0.0

    rho_eff = self.rho
    if self.adaptive:
      throttle = np.exp(-self.kappa_vol * max(realized_vol_zscores, 0) - self.kappa_spread * max(spread_zscores, 0))
      rho_eff = self.rho * throttle

    target = rho_eff * other_market_volume
    shares = min(target, self.X_remaining)
    self.shares_done += shares
    self.X_remaining -= shares
    return shares

def simulate_pov(total_shares, other_volumes, vol_zscores=None, spread_zscores=None, target_rate=0.15, adaptive=False):
  n = len(other_volumes)
  vol_zscores = vol_zscores or [0.0] * n
  spread_zscores = spread_zscores or [0.0] * n

  algo = POVExecutor(total_shares, target_rate, adaptive)
  fills, periods_used = [], 0
  for i in range(n):
    if algo.X_remaining <= 0:
      break
    f = algo.step(other_volumes[i], vol_zscores[i], spread_zscores[i])
    fills.append(f)
    periods_used += 1

  realized_total_participation = (sum(fills) / (sum(fills) + sum(other_volumes[:periods_used])
  ) if periods_used > 0 else 0.0
                                  )
  return {
      "fils": np.array(fills),
      "periods_used": periods_used,
      "shares_remaining": algo.X_remaining,
      "realized_participation": realized_total_participation,
  }

if __name__ == "__main__":
  other_vols = [5000, 6000, 4500, 7000, 8000, 9000, 12000, 15000, 18000, 22000] * 3
  result = simulate_pov(total_shares=50_000, other_volumes=other_vols, target_rate=0.15, adaptive=False)
  print(f"Periods to complete: {result['periods_used']}")
  print(f"Realized participation: {result['realized_participation']:.4f} "
  f"(target: 0.15)")

