# -*- coding: utf-8 -*-
"""Arrival Price and the Almgren-Chriss Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

def ac_optimal_trajectory(X, T, n_steps, sigma, eta_star, lam):
  kappa = np.sqrt(lam * sigma**2 / eta_star)
  t = np.linspace(0, T, n_steps + 1)
  if kappa * T < 1e-8:
    x = X * (1 - t / T)
  else:
    x = X * np.sinh(kappa * (T - t)) / np.sinh(kappa * T)
  return t, x, kappa

def ac_expected_cost_variance(X, T, n_steps, sigma, eta_star, gamma, lam):
  t, x, kappa = ac_optimal_trajectory(X, T, n_steps, sigma, eta_star, lam)
  tau = T / n_steps
  n = -np.diff(x)
  perm_cost = 0.5 * gamma * X**2
  temp_cost = eta_star * np.sum(n**2) / tau
  expected_cost = perm_cost + temp_cost
  variance = sigma**2 * tau * np.sum(x[1:]**2)
  return expected_cost, variance, kappa

def monte_carlo_validate(X, T, n_steps, sigma, eta_star, gamma, lam, n_sims=20000, seed=12):
  rng = np.random.default_rng(seed)
  t, x, kappa = ac_optimal_trajectory(X, T, n_steps, sigma, eta_star, lam)
  tau = T / n_steps
  n = -np.diff(x)
  S0 = 100.0

  costs = np.zeros(n_sims)
  for s in range(n_sims):
    xi = rng.standard_normal(n_steps)
    S = S0 + np.cumsum(sigma * np.sqrt(tau) * xi - gamma * n)
    S_prev = np.concatenate(([S0], S[:-1]))
    exec_price = S_prev - eta_star * (n / tau)
    revenue = np.sum(n * exec_price)
    costs[s] = S0 * X - revenue
  return costs.mean(), costs.var()

if __name__ == "__main__":
  X, T, n_steps = 1_000_000, 1.0, 50
  sigma, eta_star, gamma = 0.3, 2.5e-6, 2.5e-7

  print(f"{'lambda':>10}{'kappa*T:>10'} {'E[IS] ($)':>14} {'sqrt(Var) ($):>16'}")
  for lam in [0, 1e-7, 1e-6, 1e-5, 1e-4]:
    ec, var, kappa = ac_expected_cost_variance(X, T, n_steps, sigma, eta_star, gamma, lam=1e-6)
    print(f"{lam:10.1e} {kappa*T:10.3f} {ec:14,.0f} {np.sqrt(var):16,.0f}")

  mc_mean, mc_var = monte_carlo_validate(X, T, n_steps, sigma, eta_star, gamma, lam=1e-6, n_sims=20000)
  ec, var, kappa = ac_expected_cost_variance(X, T, n_steps, sigma, eta_star, gamma, lam=1e-6)
  print(f"\nValidation @ lambda=1e-6: analytic E[IS]={ec:,.0f} vs MC={mc_mean:,.0f}; "
  f"analytic sqrt(Var)={np.sqrt(var):,.0f} vs MC={np.sqrt(mc_var):,.0f}")

