# -*- coding: utf-8 -*-
"""Adaptive Execution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def ac_remaining_trajectory(x_now, t_now, T, sigma_hat, eta_star, lam, n_future):
  horizon_left = T - t_now
  if horizon_left <= 1e-9:
    return np.array ([0.0]) , np.array([0.0])
  kappa = np.sqrt (lam * sigma_hat **2 / eta_star)
  t_grid = np.linspace (t_now , T , n_future + 1)
  if kappa * horizon_left <1e-8:
    x_path = x_now * (1 - (t_grid - t_now) / horizon_left )
  else:
    x_path = x_now * np.sinh(kappa * (T - t_grid)) / np.sinh(kappa * horizon_left )
    return t_grid , x_path

class AdaptiveAlmgrenChriss:
  def __init__(self, X, T, eta_star, lam, n_rebalances, ewma_halflife_periods=5):
    self.X_remaining = X
    self.T = T
    self.eta_star = eta_star
    self.lam = lam
    self.n_rebalances = n_rebalances
    self.dt = T / n_rebalances
    self.alpha = 1 - 0.5 ** (1/ewma_halflife_periods)
    self.sigma_ewma = None

  def update_vol(self, period_return):
    if self.sigma_ewma is None:
      self.sigma_ewma = abs(period_return) * np.sqrt(np.pi/2)
    else:
      self.sigma_ewma = (np.sqrt(self.alpha * period_return **2 + (1 - self.alpha) * self.sigma_ewma **2))

  def next_trade (self, t_now):
    sigma_hat = self.sigma_ewma if self.sigma_ewma else 1e-6
    _ , path = ac_remaining_trajectory(self.X_remaining, t_now, self.T , sigma_hat, self.eta_star, self.lam , n_future=2)
    target_next = path[1] if len(path) > 1 else 0.0
    trade_size = self.X_remaining - target_next
    self.X_remaining = target_next
    return trade_size

if __name__ == " __main__ ":
  rng = np.random.default_rng(7)
  n_periods = 20
  algo = AdaptiveAlmgrenChriss(X=1_000_000 ,T=1.0 , eta_star=2.5e-6 , lam =1e-6 , n_rebalances=n_periods)
  period_returns = rng.normal(0,0.002,n_periods)
  period_returns[10]=0.025
  for i in range(n_periods):
    algo.update_vol(period_returns[i])
    t_now = i * algo.dt
    trade = algo.next_trade(t_now)
    print(f" period {i:2d} sigma_hat ={algo.sigma_ewma:.5f} "
    f" trade ={trade:9,.0f} remaining ={algo.X_remaining:10,.0f}")

