# -*- coding: utf-8 -*-
"""Dynamic Scheduling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def solve_execution_dp(X, T, N, sigma, lam, impact_fn, n_inventory_grid=101, n_action_grid=51):
  tau = T / N
  inv_grid = np.linspace(0 , X , n_inventory_grid)
  V = np.full ((N + 1 , n_inventory_grid ) , np.inf)
  V [N , 0] = 0.0

  policy = np.zeros((N , n_inventory_grid) )

  for k in range (N - 1, -1 , -1) :
    for i , x in enumerate (inv_grid) :
      if x == 0:
        V [k , i] = 0.0
        policy [k , i] = 0.0
        continue
      actions = np.linspace(0, x,n_action_grid)
      best_cost = np.inf
      best_n = 0.0
      for n in actions:
        remaining = x - n
        v_next = np.interp(remaining, inv_grid, V[k + 1, :])
        impact_cost = n * impact_fn (n / tau ) if tau > 0 else 0.0
        risk_cost = lam * sigma **2 * tau * remaining **2
        total = impact_cost + risk_cost + v_next
        if total < best_cost:
          best_cost , best_n = total , n
      V[k , i] = best_cost
      policy[k , i] = best_n

  return V , policy , inv_grid

def simulate_dp_policy (X , T , N , policy , inv_grid):
  tau = T / N
  x = X
  trajectory = [x]
  for k in range (N):
    n = np.interp (x , inv_grid , policy[k , :])
    x = max(x - n , 0.0)
    trajectory.append (x)
  return np.array(trajectory)

if __name__ == "__main__" :
  X, T, N = 100_000, 1.0, 20
  sigma, lam = 0.3, 1e-6

  eta_sqrt = 0.08
  sqrt_impact = lambda rate: eta_sqrt * np.sqrt(max(rate, 0.0))
  eta_lin = 2.5e-6
  linear_impact = lambda rate : eta_lin * rate

  for name , impact_fn in [("Square-root impact ", sqrt_impact) , ("Linear impact ", linear_impact )]:
    V , policy , inv_grid = solve_execution_dp(X, T, N, sigma, lam, impact_fn, n_inventory_grid=41, n_action_grid=41)
    traj = simulate_dp_policy(X , T , N , policy , inv_grid)
    print(f"\n{name}: inventory trajectory (every 4th step)")
    print(np.round(traj[::4],0))

