# -*- coding: utf-8 -*-
"""Execution Alpha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np

def simulate_ofi_signal(n_steps,persistence=0.3, noise_std=1.0, seed=12):
  rng = np.random.default_rng(seed)
  ofi = np.zeros(n_steps)
  for t in range(1 , n_steps):
    ofi [t] = persistence * ofi [t - 1] + rng.normal(0, noise_std )
  return ofi

def simulate_price_from_ofi (ofi, beta=0.02, extra_noise_std=0.5,seed=12):
  rng = np.random.default_rng(seed)
  dP = beta * ofi + rng.normal(0, extra_noise_std, len(ofi))
  return np.cumsum(dP)

def backtest_signal_tilted_execution (X, n_steps, ofi, prices, latency_steps, mu=2.0 , eta_star=0.05 , lam =1e-4, sigma =1.0):
  kappa = np.sqrt(lam * sigma **2 / eta_star)
  T = n_steps
  t_grid = np.arange(n_steps + 1)
  if kappa * T < 1e-8:
    x_passive = X * (1 - t_grid / T )
  else :
    x_passive = X * np.sinh(kappa * (T - t_grid) ) / np.sinh(kappa * T )
  n_passive = - np.diff(x_passive)
  tilt = np.zeros(n_steps)
  for t in range (n_steps):
    obs_idx = t - latency_steps
    if obs_idx >= 0:
      tilt [t] = mu * ofi [obs_idx]
  tilt -= tilt.mean ()
  n_signal = n_passive + tilt
  n_signal = np.clip(n_signal, 0, None)
  n_signal *= n_passive .sum () / n_signal . sum ()

  def realized_cost(n_path):
    fill_prices = prices[:len(n_path)] - eta_star * n_path
    revenue = np.sum(n_path * fill_prices)
    return prices [0] * X - revenue

  cost_passive = realized_cost ( n_passive )
  cost_signal = realized_cost ( n_signal )
  return cost_passive , cost_signal

if __name__ == "__main__":
  n_steps = 200
  ofi = simulate_ofi_signal ( n_steps + 1 , persistence =0.35 , noise_std =1.0 , seed =3)
  prices = 100 + simulate_price_from_ofi ( ofi , beta =0.015 , extra_noise_std =0.4 , seed =4)
  print ( f"{' latency ( steps ) ': >16} {' cost_passive ': >14} {'cost_signal ': >14} {' alpha captured ': >16}")
  for latency in [0 , 1 , 3 , 10]:
    cp , cs = backtest_signal_tilted_execution (X =500_000 , n_steps = n_steps , ofi = ofi , prices = prices ,latency_steps = latency , mu =3.0 , eta_star =0.03 , lam =2e-4 , sigma =0.8)
    print ( f"{ latency :16d} {cp :14,.0f} {cs :14,.0f} {cp - cs :16,.0f}")

