# -*- coding: utf-8 -*-
"""Transaction Cost Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from scipy import stats

def compute_tca_decomposition(side, S0, fills_price, fills_qty, S_first_fill, avg_spread, S_T, X_total, market_return=0.0, beta=1.0):
  X_filled = fills_qty.sum()
  S_bar = np.sum(fills_price * fills_qty) / X_filled

  raw_is_bps = 1e4 * side * (S_bar - S0) / S0

  S0_adj = S0 * (1 + beta * market_return)
  impact_bps = 1e4 * side * (S_bar - S0_adj) / S0

  timing_bps = 1e4 * side * (S_first_fill - S0) / S0
  spread_bps = 1e4 * 0.5 * avg_spread / S0

  unfilled = X_total - X_filled
  opp_cost_bps = 1e4 * side * (unfilled / X_total) * (S_T - S0) / S0

  return {
      "raw_implementation_shortfall_bps": raw_is_bps,
      "market_adjusted_impact_bps": impact_bps,
      "timing_delay_cost_bps": timing_bps,
      "spread_cost_bps": spread_bps,
      "opportunity_cost_bps": opp_cost_bps,
      "fill_rate": X_filled / X_total
  }

def required_sample_size(std_bps, detect_delta_bps, alpha_sig=0.05, power=0.8):
  z_alpha = stats.norm.ppf(1 - alpha_sig / 2)
  z_power = stats.norm.ppf(power)
  n = 2 * (z_alpha + z_power) ** 2 * std_bps ** 2 / detect_delta_bps ** 2
  return int(np.ceil(n))

def compare_algorithms(is_bps_algo_a, is_bps_algo_b):
  t_stat, p_value = stats.ttest_ind(is_bps_algo_a , is_bps_algo_b, equal_var=False)
  mean_diff = np.mean(is_bps_algo_a) - np.mean(is_bps_algo_b)
  return {"mean_diff_bps": mean_diff, "t_stat": t_stat, "p_value":p_value }

if __name__ == "__main__":
  fills_price = np.array([100.05, 100.08, 100.12, 100.12, 100.15])
  fills_qty = np.array([200000, 25000, 30000, 15000, 10000])

  report = compute_tca_decomposition(side=1, S0=100.00, fills_price=fills_price, fills_qty=fills_qty, S_first_fill=100.05 , avg_spread=0.02 , S_T=100.20 , X_total=105000, market_return=0.0008, beta=1.1)
  print(" --- Post - Trade TCA Report ---")
  for k , v in report.items():
    print(f"{k:35s}: {v:.4f}")

  n_req = required_sample_size(std_bps =30 , detect_delta_bps=3)
  print (f"\ nTrades needed to detect a 3bp difference (s =30 bp):{n_req}")
  rng = np.random.default_rng(0)
  algo_a = rng.normal(8.0, 30, 200)
  algo_b = rng.normal(10.5, 30, 200)
  comp = compare_algorithms(algo_a, algo_b)
  print (f"\ nAlgo comparison (n =200 each:{comp}")

