# -*- coding: utf-8 -*-
"""Inventory Penalties.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

A = 5.0
k = 1.5
delta_a = 0.01
delta_b = 0.01
sigma = 0.02
T = 300
dt = 0.01
N = int(T/dt)
n_paths = 5

lambda_a = A * np.exp(-k*delta_a)
lambda_b = A * np.exp(-k*delta_b)

print(f"Akk fill rate: {lambda_a:.3f} fills/sec")
print(f"Bid fill rate: {lambda_b:.3f} fills/sec")
print(f"Expected Std(q_T): {np.sqrt((lambda_a + lambda_b)*T):.2f}")

fig, axes = plt.subplots(3, 1, figsize=(14, 10))

for path in range(n_paths):
  np.random.seed(path)

  q = np.zeros(N + 1)

  S = np.zeros(N + 1)
  X = np.zeros(N + 1)
  S[0] = 100.0

  for i in range(N):
    S[i+1] = S[i] + sigma * np.sqrt(dt) * np.random.rand()

    fill_ask = np.random.rand() < lambda_a * dt
    fill_bid = np.random.rand() < lambda_b * dt

    ask_price = S[i] + delta_a
    bid_price = S[i] - delta_b

    if fill_ask:
      X[i+1] = X[i] + ask_price
      q[i+1] = q[i] - 1

    elif fill_bid:
      X[i+1] = X[i] - bid_price
      q[i+1] = q[i] + 1

    else:
      X[i+1] = X[i]
      q[i+1] = q[i]

  W = X + q * S
  t = np.linspace(0, T, N+1)
  axes[0].plot(t, S, alpha=0.6, lw=0.8)
  axes[1].plot(t, W, alpha=0.8, lw=0.8)
  axes[2].plot(t, q, alpha=0.8, lw=0.8)

axes[0].set_ylabel('Mid-Price $S_t$')
axes[0].set_title('Market Maker Inventory Dynamics Simulation')

axes[1].set_ylabel('Inventory $q_t$')
axes[1].axhline(0, color='red', lw=1.5, linestyle='--', label='q=0')
axes[1].legend()

axes[2].set_ylabel('MtM Wealth $W_t$')
axes[2].set_xlabel('Time (seconds)$t$')

for ax in axes:
  ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('Inventory_dynamics.pdf', dpi=150, bbox_inches='tight')
plt.show()

import pandas as pd
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

gamma = 0.1
sigma = 0.02
T = 3600
S0 = 100.0

def reservation_price(S, q, t, T, gamma, sigma):
  return S - q * gamma * sigma**2 * (T - t)

q_range = np.linspace(-50, 50, 100)
t_range = np.linspace(0, T * 0.99, 100)
Q, Tau = np.meshgrid(q_range, t_range)
R = reservation_price(S0, Q, Tau, T, gamma, sigma)
skew = R - S0

fig = plt.figure(figsize=(15, 5))

ax1 = fig.add_subplot(131, projection='3d')
surf = ax1.plot_surface(Q, Tau, skew, cmap='RdBu_r', alpha=0.8)
ax1.set_xlabel('Inventory $q$')
ax1.set_ylabel('Time (hours)')
ax1.set_zlabel('$r_t - S_t$')
ax1.set_title("Reservation Price Skew")

ax2 = fig.add_subplot(132)
q_vals = np.linspace(-50, 50, 200)
gamma_val = 0.01
tau = 1800

phi_quad = 0.5 * gamma_val * sigma**2 * q_vals**2 * tau
phi_abs = gamma_val * sigma * np.sqrt(tau) * np.abs(q_vals)
phi_quartic = gamma_val**2 * q_vals**4 / 4

ax2.plot(q_vals, phi_quad, 'b-',lw=2, label='Quadratic')
ax2.plot(q_vals, phi_abs, 'r--', lw=2, label='Absolute Value')
ax2.plot(q_vals, phi_quartic * 100, 'g-', lw=2, label='Quartic(x100)')
ax2.set_xlabel('Inventory $q$')
ax2.set_ylabel('Penalty')
ax2.set_title("Penalty Functions")
ax2.legend()
ax2.grid(True, alpha=0.3)

ax3 = fig.add_subplot(133)
for t_frac in [0.1, 0.3, 0.5, 0.7, 0.9]:
  t = t_frac * T
  r = reservation_price(S0, q_vals, t, T, gamma, sigma)
  ax3.plot(q_vals, r - S0, label=f't={t_frac*100:.0f}%', lw=2)

ax3.axhline(0, color='black', lw=1, linestyle='--')
ax3.set_xlabel('Inventory $q$')
ax3.set_ylabel('$r_t - S_t$')
ax3.set_title("Reservation Prices")
ax3.legend(fontsize=8)
ax3.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("Inventory_penalties.pdf", dpi=150, bbox_inches='tight')
plt.show()