# -*- coding: utf-8 -*-
"""Adverse Selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.stats import norm

def bulk_volume_classify(trades: pd.DataFrame, sigma_window: int = 50) -> pd.DataFrame:
  trades = trades.copy()
  trades['price_change'] = trades['price'].diff()
  sigma = trades['price_change'].rolling(sigma_window).std()
  z = (trades['price_change'] / sigma).fillna(0.0)
  trades['buy_frac'] = norm.cdf(z)
  return trades

def compute_vpin(trades: pd.DataFrame, bucket_volume: float, n_buckets_window: int = 50) -> pd.Series:
  trades = trades.copy()
  trades['buy_volume'] = trades['volume'] * trades['buy_frac']
  trades['sell_volume'] = trades['volume'] * (1 - trades["buy_frac"])
  trades['cum_buy_volume'] = trades['buy_volume'].cumsum()
  bucket_stats = trades.groupby("bucket_id").agg(buy_vol=("buy_volume", "sum"), sell_vol=("sell_volume", "sum"))
  bucket_stats['imbalance'] = (bucket_stats['buy_vol'] - bucket_stats['sell_vol']).abs()

  vpin = bucket_stats['imbalance'].rolling(n_buckets_window).sum() / (n_buckets_window * bucket_volume)
  return vpin

np.random.seed(12)
n_ticks = 50_000
price = 100 + np.cumsum(np.random.normal(0, 0.01, n_ticks))
volume = np.random.lognormal(mean=4, sigma=1.0, size=n_ticks)
trades = pd.DataFrame({"price": price, "volume": volume})

trades_classified = bulk_volume_classify(trades, sigma_window=50)
avg_daily_volume = trades["volume"].sum()
bucket_vol = avg_daily_volume / 1000
trades_classified['bucket_id'] = (trades_classified['volume'].cumsum() / bucket_vol).astype(int)
vpin_series = compute_vpin(trades_classified, bucket_volume=bucket_vol, n_buckets_window=50)
print(vpin_series.describe())

