# -*- coding: utf-8 -*-
"""Quote Placement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from dataclasses import dataclass

@dataclass
class QuoteParams:
  gamma: float
  sigma: float
  T_minus_t: float
  beta_imbalance: float
  tick_size: float
  base_half_spread_bid: float
  base_half_spread_ask: float

def micro_price(best_bid: float, best_ask: float, bid_depth: float, ask_depth: float) -> float:
  total = bid_depth + ask_depth
  if total == 0:
    return 0.5 * (best_bid + best_ask)
  return (bid_depth / total) * best_ask + (ask_depth / total) * best_bid

def order_book_imbalance(bid_depth: float, ask_depth: float) -> float:
  total = bid_depth + ask_depth
  return 0.0 if total == 0 else (bid_depth - ask_depth) / total

def round_to_tick(price: float, tick: float, direction: str) -> float:
  if direction == "down":
    return np.floor(price/tick) * tick
  elif direction == "up":
    return np.ceil(price / tick) * tick
  raise ValueError("Direction must be 'down' or 'up'" )

def compute_quotes(mid_price: float, inventory: float, best_bid: float, best_ask: float, bid_depth: float, ask_depth: float, params: QuoteParams) -> dict:
  fair_value = micro_price(best_bid, best_ask, bid_depth, ask_depth)
  imbalance = order_book_imbalance(bid_depth, ask_depth)
  inventory_skew = -inventory * params.gamma * (params.sigma ** 2) * params.T_minus_t
  flow_skew = -params.beta_imbalance * imbalance

  reservation_price = fair_value + inventory_skew + flow_skew

  raw_bid = reservation_price - params.base_half_spread_bid
  raw_ask = reservation_price + params.base_half_spread_ask

  bid = round_to_tick(raw_bid, params.tick_size, "down")
  ask = round_to_tick(raw_ask, params.tick_size, "up")

  if bid >= ask:
    mid_safe = 0.5 * (bid + ask)
    bid = round_to_tick(mid_safe - params.tick_size / 2, params.tick_size, "down")
    ask = round_to_tick(mid_safe + params.tick_size / 2, params.tick_size, "up")

  return {'fair_value': fair_value, 'imbalance': imbalance, 'reservation_price': reservation_price, 'bid': bid, 'ask': ask, 'quoted_spread': ask - bid}

params = QuoteParams(gamma=0.01, sigma=0.3, T_minus_t=0.02, beta_imbalance=0.05, tick_size=0.01, base_half_spread_bid=0.02, base_half_spread_ask=0.02)
result_flat = compute_quotes(mid_price=100.0, inventory=0, best_bid=99.99, best_ask=100.01, bid_depth=500, ask_depth=500, params=params)
result_long = compute_quotes(mid_price=100.0, inventory=300, best_bid=99.99, best_ask=100.01, bid_depth=500, ask_depth=500, params=params)
print("Flat inventory:", result_flat)
print("Long 300 inventory:", result_long)

