# -*- coding: utf-8 -*-
"""LOB Simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlhF6oLBoVXbiIPjIelhK5TaO6nOWVLi
"""

import heapq
from collections import defaultdict, deque
from dataclasses import dataclass, field
from typing import Optional

import numpy as np

@dataclass
class Order:
  order_id: int
  side: str
  price: float
  quantity: int
  timestamp: float
  oreder_type: str = 'limit'

class LimitOrderBook:
  def __init__(self):
    self.bids = []
    self.asks = []

    self.bid_levels = defaultdict(deque)
    self.ask_levels = defaultdict(deque)

    self.orders = {}
    self.cancelled = set()

    self.trades = []
    self._order_counter = 0

  def _next_id(self):
    self._order_counter += 1
    return self._order_counter

  def best_bid(self) -> Optional[float]:
    while self.bids:
      neg_price, ts, oid = self.bids[0]
      if oid in self.cancelled or oid not in self.orders:
        heapq.heappop(self.bids)
        continue
      return -neg_price
    return None

  def best_ask(self) -> Optional[float]:
    while self.asks:
      price, ts, oid = self.asks[0]
      if oid in self.cancelled or oid not in self.orders:
        heapq.heappop(self.asks)
        continue
      return price
    return None

  def mid_price(self) -> Optional[float]:
    bb, ba = self.best_bid(), self.best_ask()
    if bb and ba:
      return (bb + ba) / 2.0
    return None

  def spread(self) -> Optional[float]:
    bb, ba = self.best_bid(), self.best_ask()
    if bb and ba:
      return (ba - bb)
    return None

  def add_limit_order(self, side: str, price: float, quantity: int, timestamp: float) -> int:
    oid = self._next_id()
    order = Order(oid, side, price, quantity, timestamp)
    self.orders[oid] = order
    if side == 'buy':
      heapq.heappush(self.bids, (-price, timestamp, oid))
      self.bid_levels[price].append((quantity, oid))
    else:
      heapq.heappush(self.asks, (price, timestamp, oid))
      self.ask_levels[price].append((quantity, oid))

    self._match()
    return oid

  def add_market_order(self, side: str, quantity: int, timestamp: float) -> int:
    remaining = quantity
    executed_trades = []

    if side == 'buy':
      while remaining > 0 and self.best_ask():
        ba = self.best_ask()
        level = self.ask_levels[ba]
        while remaining > 0 and level:
          qty, oid = level[0]
          if oid in self.cancelled:
            level.popleft()
            continue
          fill = min(remaining, qty)
          executed_trades.append({'price': ba, 'quantity': fill, 'timestamp': timestamp})
          remaining -= fill
          if fill == qty:
            level.popleft()
            del self.orders[oid]
          else:
            level[0] = (qty - fill, oid)
            self.orders[oid].quantity -= fill
        if not self.ask_levels[ba]:
          del self.ask_levels[ba]
           self.asks = [x for x in self.asks if x[0] != ba]
          heapq.heapify(self.asks)

    
    elif side == 'sell':
      while remaining > 0 and self.best_bid():
        bb = self.best_bid()
        level = self.bid_levels[bb]
        while remaining > 0 and level:
          qty, oid = level[0]
          if oid in self.cancelled:
            level.popleft()
            continue
          fill = min(remaining, qty)
          executed_trades.append({'price': bb, 'quantity': fill, 'timestamp': timestamp})
          remaining -= fill
          if fill == qty:
            level.popleft()
            del self.orders[oid]
          else:
            level[0] = (qty - fill, oid)
            self.orders[oid].quantity -= fill
        if not self.bid_levels[bb]:
          del self.bid_levels[bb]
          self.bids = [x for x in self.bids if x[0] != -bb]
          heapq.heapify(self.bids)

    self.trades.extend(executed_trades)
    return executed_trades

  def cancel_order(self, order_id: int) -> bool:
    if order_id in self.orders:
      self.cancelled.add(order_id)
      return True
    return False

  def _match(self):
    while self.best_bid() and self.best_ask():
      bb = self.best_bid()
      ba = self.best_ask()
      if bb >= ba:
        bid_level = self.bid_levels[bb]
        ask_level = self.ask_levels[ba]

        while bid_level and bid_level[0][1] in self.cancelled:
          bid_level.popleft()
        while ask_level and ask_level[0][1] in self.cancelled:
          ask_level.popleft()

        if not bid_level or not ask_level:
          break

        b_qty, b_oid = bid_level[0]
        a_qty, a_oid = ask_level[0]
        fill = min(b_qty, a_qty)
        trade_price = ba 

        self.trades.append({'price': trade_price, 'qty': fill, 'bid_oid': b_oid, 'ask_oid': a_oid})
        if fill == b_qty:
          bid_level.popleft()
          del self.orders[b_oid]
        else:
          bid_level[0] = (b_qty - fill, b_oid)
          self.orders[b_oid].quantity -= fill

        if fill == a_qty:
          ask_level.popleft()
          del self.orders[a_oid]
        else:
          ask_level[0] = (a_qty - fill, a_oid)
          self.orders[a_oid].quantity -= fill

        if not bid_level:
          del self.bid_levels[bb]
        if not ask_level:
          del self.ask_levels[ba]

      else:
        break

  def order_imbalance(self, levels: int = 5) -> float:
    bid_qty = sum(q for price_level_deque in sorted(self.bid_levels.items(), reverse=True)[:levels] for q, oid in price_level_deque[1] if oid not in self.cancelled)
    ask_qty = sum(q for price_level_deque in sorted(self.ask_levels.items())[:levels] for q, oid in price_level_deque[1] if oid not in self.cancelled)

    total = bid_qty + ask_qty
    return (bid_qty - ask_qty) / total if total > 0 else 0.0

  def __repr__(self):
    lines = ["=" * 40 , " LIMIT ORDER BOOK ", "=" * 40]
    for price in sorted(self.ask_levels.keys(), reverse=True)[:5]:
      qty = sum(q for q, oid in self.ask_levels[price] if oid not in self.cancelled)
      if qty > 0:
        lines.append(f"  ASK ${price:.2f} x {qty:>6}")

    spread_val = self.spread()
    mid_val = self.mid_price()

    if spread_val is not None:
        lines.append(f"  --- SPREAD: ${spread_val:.4f} ---")
    else:
        lines.append("  --- SPREAD: --- EMPTY ---")

    if mid_val is not None:
        lines.append(f"  --- MID PRICE: ${mid_val:.4f} ---")
    else:
        lines.append("  --- MID PRICE: --- EMPTY ---")

    for price in sorted(self.bid_levels.keys(), reverse=True)[:5]:
      qty = sum(q for q, oid in self.bid_levels[price] if oid not in self.cancelled)
      if qty > 0:
        lines.append(f"  BID ${price:.2f} x {qty:>6}")

    lines.append("=" * 40)
    return "\n".join(lines)

if __name__ == '__main__':
  lob = LimitOrderBook()

  lob.add_limit_order('sell', 100.02, 500, 1.0)
  lob.add_limit_order('sell', 100.01, 300, 2.0)
  lob.add_limit_order('buy', 100.00, 400, 3.0)
  lob.add_limit_order('sell', 99.99, 600, 4.0)

  print(lob)
  mid_val = lob.mid_price()
  print(f"Mid: ${mid_val:.4f}" if mid_val is not None else "Mid: N/A")
  oi_val = lob.order_imbalance()
  print(f"OI (5-level): {oi_val:.4f}")

  lob.add_limit_order('buy', 100.01, 200, 5.0)
  print("\nAfter aggresive buy limit at 100.01:")

  print(f"Trades: {lob.trades}")