# -*- coding: utf-8 -*-
"""Cost Components.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from dataclasses import dataclass, field
from typing import List, Optional

@dataclass
class Fill:
    quantity: float
    price: float
    timestamp: pd.Timestamp
    mid_at_fill: float

@dataclass
class Order:
    symbol: str
    side: int
    target_quantity: float
    decision_price: float
    decision_time: pd.Timestamp
    fills: List[Fill] = field(default_factory=list)
    commission: float = 0.0
    terminal_mid: Optional[float] = None

class TCACostDecomposer:
    def __init__(self, order: Order):
        self.order = order
        self._validate()

    def _validate(self):
        assert self.order.side in [1, -1], "Side must be +1(buy) or -1(sell)"
        assert self.order.target_quantity > 0

    @property
    def filled_quantity(self) -> float:
        return sum(f.quantity for f in self.order.fills)

    @property
    def unfilled_quantity(self) -> float:
        return self.order.target_quantity - self.filled_quantity

    @property
    def vwap_fill_price(self) -> float:
        if self.filled_quantity == 0:
            return self.order.decision_price
        total_notional = sum(f.quantity * f.price for f in self.order.fills)
        return total_notional / self.filled_quantity

    def slippage_bps(self) -> float:
        if self.filled_quantity == 0:
            return 0.0
        slip = self.order.side * (self.vwap_fill_price - self.order.decision_price)
        return (slip / self.order.decision_price) * 10000

    def market_impact_bps(self) -> float:
        if self.filled_quantity == 0:
            return 0.0
        impact_cost = sum(
            f.quantity * self.order.side * (f.price - f.mid_at_fill)
            for f in self.order.fills
        )
        return (impact_cost / (self.order.target_quantity * self.order.decision_price)) * 10000

    def spread_cost_bps(self) -> float:
        if self.filled_quantity == 0:
            return 0.0
        spread_cost = sum(
            f.quantity * self.order.side * (f.mid_at_fill - self.order.decision_price)
            for f in self.order.fills
        )
        return (spread_cost / (self.order.target_quantity * self.order.decision_price)) * 10000

    def opportunity_cost_bps(self) -> float:
        if self.order.terminal_mid is None:
            return 0.0
        unfilled = self.unfilled_quantity
        if unfilled <= 0:
            return 0.0
        opp_cost = unfilled * self.order.side * (
            self.order.terminal_mid - self.order.decision_price
        )
        return (opp_cost / (self.order.target_quantity * self.order.decision_price)) * 10000

    def commission_bps(self) -> float:
        return (self.order.commission / (self.order.target_quantity * self.order.decision_price)) * 10000

    def implementation_shortfall_bps(self) -> float:
        return (
            self.market_impact_bps() +
            self.spread_cost_bps() +
            self.opportunity_cost_bps() +
            self.commission_bps()
        )

    def decomposition_report(self) -> pd.DataFrame:
        components = {
            "Slippage (total)": self.slippage_bps(),
            "Market Impact": self.market_impact_bps(),
            "Spread Cost": self.spread_cost_bps(),
            "Opportunity Cost": self.opportunity_cost_bps(),
            "Commission": self.commission_bps(),
            "Implementation Shortfall": self.implementation_shortfall_bps(),
        }
        df = pd.DataFrame.from_dict(components, orient='index', columns=['bps'])
        df['%'] = df['bps'] / 100
        return df.round(4)

fills = [
    Fill(quantity=30000, price=50.05, timestamp=pd.Timestamp("2024-01-15 09:31"), mid_at_fill=50.02),
    Fill(quantity=40000, price=50.12, timestamp=pd.Timestamp("2024-01-15 09:45"), mid_at_fill=50.08),
    Fill(quantity=20000, price=50.18, timestamp=pd.Timestamp("2024-01-15 10:15"), mid_at_fill=50.15),
]

order = Order(
    symbol="XYZ",
    side=1,
    target_quantity=100000,
    decision_price=50.00,
    decision_time=pd.Timestamp("2024-01-15 09:30"),
    fills=fills,
    commission=180.0,
    terminal_mid=50.22
)

tca = TCACostDecomposer(order)
print(tca.decomposition_report())
print(f"\nFill Rate: {tca.filled_quantity / order.target_quantity:.1%}")
print(f"VWAP Fill: ${tca.vwap_fill_price:.4f}")

