# -*- coding: utf-8 -*-
"""Slippage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd

class RealisticSlippageModel:
    def __init__(
        self,
        spread_bps: float = 2.0,
        impact_coeff: float = 0.1,
        commission_bps: float = 0.5,
        slippage_vol_multiplier: float = 0.0
    ):
        self.spread_bps = spread_bps
        self.impact_coeff = impact_coeff
        self.commission_bps = commission_bps
        self.slippage_vol_mult = slippage_vol_multiplier

    def compute_fill_price(
        self,
        decision_mid: float,
        side: int,
        order_qty: float,
        daily_volume: float,
        daily_vol: float,
        rng: np.random.Generator = None
    ) -> dict:
        if rng is None:
            rng = np.random.default_rng()

        spread_cost = self.spread_bps / 10000

        participation_rate = order_qty / daily_volume
        impact_frac = self.impact_coeff * daily_vol * np.sqrt(participation_rate)

        noise = self.slippage_vol_mult * daily_vol * rng.standard_normal()

        total_slippage_frac = spread_cost + impact_frac + noise
        fill_price = decision_mid * (1 + side * total_slippage_frac)

        return {
            'fill_price': fill_price,
            'spread_cost_bps': spread_cost * 10000,
            'impact_cost_bps': impact_frac * 10000,
            'noise_bps': noise * 10000,
            'total_slippage_bps': total_slippage_frac * 10000,
            'commission_bps': self.commission_bps,
            'total_cost_bps': (total_slippage_frac * 10000) + self.commission_bps
        }

    def batch_slippage(self, orders_df: pd.DataFrame) -> pd.DataFrame:
        results = []
        rng = np.random.default_rng(42)

        for _, row in orders_df.iterrows():
            result = self.compute_fill_price(
                decision_mid=row['mid'],
                side=row['side'],
                order_qty=row['qty'],
                daily_volume=row['adv'],
                daily_vol=row['daily_vol'],
                rng=rng
            )
            results.append(result)

        return pd.DataFrame(results)


model = RealisticSlippageModel(
    spread_bps=2.0,
    impact_coeff=0.1,
    commission_bps=0.5
)

orders = pd.DataFrame({
    'symbol': ['AAPL', 'TSLA', 'SPY', 'IWM'],
    'mid': [185.0, 220.0, 450.0, 200.0],
    'side': [1, -1, 1, -1],
    'qty': [50000, 22000, 100000, 80000],
    'adv': [70e6, 30e6, 400e6, 100e6],
    'daily_vol': [0.012, 0.025, 0.007, 0.009],
})

results = model.batch_slippage(orders)
print(pd.concat([orders[['symbol', 'side', 'qty']], results], axis=1).to_string())

import matplotlib.pyplot as plt
prates = np.linspace(0.001, 0.10, 100)
daily_vol = 0.015
spread = 2.0
impacts = [model.impact_coeff * daily_vol * np.sqrt(p) * 10000 + spread for p in prates]

print("\nParticipation Rate vs Total Slippage (bps):")
for p, imp in zip(prates[::10], impacts[::10]):
    print(f"{p:5.1%} -> {imp:.2f} bps")

