# -*- coding: utf-8 -*-
"""Market Impact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy import stats

def estimate_kyle_lambda(trades: pd.DataFrame, quote_mid: pd.Series, lag_quotes: bool = True) -> dict:
  trades = trades.copy()
  trades['mid_before'] = quote_mid.reindex(trades['timestamp'], method='pad').values
  trades['mid_after'] = quote_mid.reindex(trades['timestamp'] + pd.Timedelta('5min'), method='pad').values

  trades['delta_mid'] = trades['mid_after'] - trades['mid_before']

  trades = trades.dropna(subset=['delta_mid', 'quantity'])

  x = trades['quantity'].values
  y = trades['delta_mid'].values

  mid_avg = trades['mid_before'].mean()
  y_norm = y / mid_avg * 10_000
  x_norm = x / trades['quantity'].abs().mean()

  slope, intercept, r, p_val, se = stats.linregress(x_norm, y_norm)

  return {
      'lambda_bps_per_unit': slope,
      'lambda_raw': slope * mid_avg / 10_000,
      'r_squared': r**2,
      'p_value': p_val,
      't_statistic': slope/se,
      'n_trades': len(trades),
      'interpretation': (f"A 1 unit of avg-normalized signed flow moves the mod by "
      f"{slope:.3f} bps. Kyle lambda ($/share) = {slope*mid_avg/10_000:.6f}")
  }

np.random.seed(12)
n = 10_000
true_lambda = 0.0002

V = 100.0
sigma_V = 0.01
sigma_u = 5000
informed_order = (V - 100) / (2 * true_lambda)
noise = np.random.normal(0, sigma_u, n)
total_flow = informed_order + noise

delta_mid = true_lambda * total_flow + np.random.normal(0, 0.01, n)
mid = 100 + np.cumsum(delta_mid)

trades_df = pd.DataFrame({'timestamp': pd.date_range('2024-01-15 09:30', periods=n, freq='3s'), 'quantity': total_flow, 'price': mid + np.sign(total_flow) * 0.01})

mid_series = pd.Series(mid, index=pd.date_range('2024-01-15 09:30', periods=n, freq='3s'))

result = estimate_kyle_lambda(trades_df, mid_series)
for k, v in result.items():
  if k != 'interpretation':
    print(f"{k:30s}: {v}")
print(f"\n {result['interpretation']}")

