# -*- coding: utf-8 -*-
"""Opportunity Costs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.optimize import minimize_scalar

def signal_decay_model(alpha_0, tau_alpha, decay_type='exponential'):
    if decay_type == 'exponential':
        return lambda t: alpha_0 * np.exp(-t / tau_alpha)
    elif decay_type == 'linear':
        return lambda t: alpha_0 * np.maximum(0.0, 1.0 - t / tau_alpha)
    elif decay_type == 'power':
        return lambda t: alpha_0 / (1.0 + t / tau_alpha) ** 1.5
    else:
        raise ValueError("Unknown decay type")

def impact_cost_model(c, sigma, q_over_v, T, delta=0.5):
    return c * sigma * np.sqrt(q_over_v) * (T ** (-delta)) * 10000

def net_alpha(T, alpha_0, tau_alpha, c, sigma, q_over_v, delta=0.5, decay_type='exponential'):
    alpha_fn = signal_decay_model(alpha_0, tau_alpha, decay_type)
    alpha_at_T = alpha_fn(T)
    cost_at_T = impact_cost_model(c, sigma, q_over_v, T, delta)
    return alpha_at_T - cost_at_T

def find_optimal_horizon(alpha_0, tau_alpha, c, sigma, q_over_v, delta=0.5, decay_type='exponential', T_range=(0.1, 20.0)):
    result = minimize_scalar(
        lambda T: -net_alpha(T, alpha_0, tau_alpha, c, sigma, q_over_v, delta, decay_type),
        bounds=T_range,
        method='bounded'
    )
    T_opt = result.x
    net_opt = net_alpha(T_opt, alpha_0, tau_alpha, c, sigma, q_over_v, delta, decay_type)
    return {
        'T_optimal': T_opt,
        'net_alpha_bps': net_opt,
        'impact_bps': impact_cost_model(c, sigma, q_over_v, T_opt, delta),
        'alpha_at_Topt': signal_decay_model(alpha_0, tau_alpha, decay_type)(T_opt)
    }

print("=" * 65)
print(f"{'Signal Half-life': >20} | {'T* (days)': >10} | {'Net Alpha': >10} | {'Impact': >10}")
print("=" * 65)

for tau in [0.25, 0.5, 1.0, 2.0, 5.0, 10.0]:
    res = find_optimal_horizon(
        alpha_0=50.0,
        tau_alpha=tau,
        c=0.25,
        sigma=0.015,
        q_over_v=0.05
    )
    print(f"{tau: >18.2f}d | {res['T_optimal']: >10.3f} | {res['net_alpha_bps']: >8.1f} bps | {res['impact_bps']: >8.1f} bps")

print("\n\nOpportunity Cost from Partial Fill:")
print("-" * 50)
Q_star = 100000
Q_filled = 75000
M0 = 100.0
MT = 101.50
D = 1

phi = Q_filled / Q_star
OC1 = D * (1 - phi) * (MT - M0) / M0 * 10000
print(f"Fill rate: {phi:.1%}")
print(f"Price move: {(MT - M0) / M0 * 10000:.1f} bps")
print(f"Opportunity Cost: {OC1:.2f} bps")
print(f"(Missed {Q_star - Q_filled:,} shares of a {(MT - M0) / M0 * 100.0:.1f}% move)")

