# -*- coding: utf-8 -*-
"""Execution Quality Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from typing import Dict, List, Optional
from dataclasses import dataclass

@dataclass
class ExecutionMetrics:
    symbol: str
    order_id: str
    side: int
    target_qty: float
    filled_qty: float
    avg_fill_price: float
    arrival_mid: float
    vwap_benchmark: float
    close_price: float
    terminal_mid: float
    commission: float
    fill_timestamps: List[float]

    @property
    def fill_rate(self) -> float:
        return self.filled_qty / self.target_qty

    @property
    def is_bps(self) -> float:
        slippage = self.side * (self.avg_fill_price - self.arrival_mid)
        opp = self.side * (1 - self.fill_rate) * (self.terminal_mid - self.arrival_mid)
        comm = self.commission / (self.target_qty * self.arrival_mid)
        return (slippage / self.arrival_mid + opp / self.arrival_mid + comm) * 10000

    @property
    def vwap_slippage_bps(self) -> float:
        return self.side * (self.avg_fill_price - self.vwap_benchmark) / self.vwap_benchmark * 10000

    @property
    def close_slippage_bps(self) -> float:
        return self.side * (self.avg_fill_price - self.close_price) / self.close_price * 10000

    @property
    def arrival_to_fill_seconds(self) -> float:
        if not self.fill_timestamps:
            return np.nan
        return np.mean(self.fill_timestamps)

    @property
    def post_trade_drift_bps(self) -> float:
        return self.side * (self.terminal_mid - self.avg_fill_price) / self.avg_fill_price * 10000

    def full_report(self) -> pd.Series:
        return pd.Series({
            'Symbol': self.symbol,
            'Side': 'BUY' if self.side == 1 else 'SELL',
            'Fill Rate': f"{self.fill_rate:.1%}",
            'IS (bps)': f"{self.is_bps:.2f}",
            'VWAP Slip (bps)': f"{self.vwap_slippage_bps:.2f}",
            'Close Slip (bps)': f"{self.close_slippage_bps:.2f}",
            'Post-Trade Drift (bps)': f"{self.post_trade_drift_bps:.2f}",
            'Avg Time to Fill (s)': f"{self.arrival_to_fill_seconds:.1f}",
            'Commission (bps)': f"{self.commission / (self.target_qty * self.arrival_mid) * 10000:.2f}"
        })


class ExecutionQualityDashboard:
    def __init__(self):
        self.orders: List[ExecutionMetrics] = []

    def add_order(self, order: ExecutionMetrics):
        self.orders.append(order)

    def _metrics_df(self) -> pd.DataFrame:
        records = []
        for o in self.orders:
            records.append({
                'symbol': o.symbol,
                'side': o.side,
                'fill_rate': o.fill_rate,
                'is_bps': o.is_bps,
                'vwap_bps': o.vwap_slippage_bps,
                'close_bps': o.close_slippage_bps,
                'post_drift': o.post_trade_drift_bps,
                'notional': o.target_qty * o.arrival_mid,
            })
        return pd.DataFrame(records)

    def aggregate_stats(self) -> pd.DataFrame:
        df = self._metrics_df()
        w = df['notional'] / df['notional'].sum()

        return pd.DataFrame({
            'Metric': ['IS (bps)', 'VWAP Slippage (bps)', 'Close Slippage (bps)', 'Post-Trade Drift (bps)', 'Fill Rate'],
            'VW Mean': [
                (df['is_bps'] * w).sum(),
                (df['vwap_bps'] * w).sum(),
                (df['close_bps'] * w).sum(),
                (df['post_drift'] * w).sum(),
                (df['fill_rate'] * w).sum(),
            ],
            'EW Mean': [df[c].mean() for c in ['is_bps', 'vwap_bps', 'close_bps', 'post_drift', 'fill_rate']],
            'Std Dev': [df[c].std() for c in ['is_bps', 'vwap_bps', 'close_bps', 'post_drift', 'fill_rate']],
            '25th pct': [df[c].quantile(0.25) for c in ['is_bps', 'vwap_bps', 'close_bps', 'post_drift', 'fill_rate']],
            '75th pct': [df[c].quantile(0.75) for c in ['is_bps', 'vwap_bps', 'close_bps', 'post_drift', 'fill_rate']],
        }).set_index('Metric').round(4)

    def information_coefficient(self) -> float:
        df = self._metrics_df()
        if len(df) < 5:
            return np.nan
        return df['is_bps'].corr(df['post_drift']) * -1

np.random.seed(12)
dashboard = ExecutionQualityDashboard()
symbols = ['AAPL', 'MSFT', 'AMZN', 'TSLA', 'NVDA']

for i in range(50):
    sym = symbols[i % 5]
    side = np.random.choice([1, -1])
    mid = np.random.uniform(50, 500)
    order = ExecutionMetrics(
        symbol=sym, order_id=f"ORD{i:04d}",
        side=side, target_qty=np.random.randint(10000, 200000),
        filled_qty=np.random.randint(8000, 200000),
        avg_fill_price=mid + side * np.random.uniform(0.02, 0.20),
        arrival_mid=mid, vwap_benchmark=mid * (1 + np.random.normal(0, 0.001)),
        close_price=mid * (1 + np.random.normal(0.002, 0.01)),
        terminal_mid=mid + side * np.random.normal(0.05, 0.15),
        commission=0.001 * np.random.randint(10000, 200000),
        fill_timestamps=list(np.random.uniform(10, 600, 5))
    )
    if order.filled_qty > order.target_qty:
        order.filled_qty = order.target_qty
    dashboard.add_order(order)

print("Aggregate Execution Quality Stats:")
print(dashboard.aggregate_stats().to_string())
print(f"\nExecution IC: {dashboard.information_coefficient():.4f}")

