# -*- coding: utf-8 -*-
"""Execution Quality Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from scipy import stats

class TCAAttributionModel:
    def __init__(self):
        self.model_fit = None
        self.attribution_df = None

    def five_way_decomposition(self,
                               orders: pd.DataFrame,
                               fills_db: dict) -> pd.DataFrame:
        results = []

        for _, row in orders.iterrows():
            oid = row['order_id']
            D = row['side']
            Q_star = row['target_qty']
            M0 = row['arrival_mid']
            MT = row['terminal_mid']
            s_eff = row['effective_spread']
            comm_val = row['commission']

            fills = fills_db.get(oid, [])
            Q_filled = sum(f[0] for f in fills)
            phi = Q_filled / Q_star if Q_star > 0 else 0

            if fills:
                P1 = fills[0][1]
                C1 = D * (P1 - M0) / M0 * 10000
            else:
                C1 = D * (MT - M0) / M0 * 10000

            C2 = phi * s_eff / (2 * M0) * 10000

            if fills:
                impact_val = sum(
                    q * D * (p - mid - s_eff / 2)
                    for q, p, mid in fills
                )
                C3 = impact_val / (Q_star * M0) * 10000
            else:
                C3 = 0.0

            C4 = D * (1 - phi) * (MT - M0) / M0 * 10000

            C5 = comm_val / (Q_star * M0) * 10000

            total_is = C1 + C2 + C3 + C4 + C5

            results.append({
                'order_id': oid,
                'symbol': row['symbol'],
                'delay_bps': C1,
                'spread_bps': C2,
                'impact_bps': C3,
                'opportunity_bps': C4,
                'commission_bps': C5,
                'total_IS_bps': total_is,
                'fill_rate': phi,
            })

        return pd.DataFrame(results)

    def cross_sectional_regression(self, trades: pd.DataFrame) -> dict:
        trades = trades.copy()
        trades['ln_IS'] = np.log(np.maximum(trades['is_bps'], 0.01))
        trades['ln_prate'] = np.log(trades['participation_rate'])
        trades['ln_vol'] = np.log(trades['daily_vol'])
        trades['ln_spread'] = np.log(trades['rel_spread'])
        trades['ln_price'] = np.log(trades['price'])

        formula = "ln_IS ~ ln_prate + ln_vol + ln_spread + urgency_score + ln_price"
        self.model_fit = smf.ols(formula, data=trades).fit()

        return {
            'params': self.model_fit.params.to_dict(),
            'rsquared': self.model_fit.rsquared,
            'aic': self.model_fit.aic,
            'pvalues': self.model_fit.pvalues.to_dict(),
            'model': self.model_fit,
            'summary': self.model_fit.summary()
        }

    def predict_is(self, participation_rate: float, daily_vol: float,
                   rel_spread: float, urgency: float, price: float) -> float:
        if self.model_fit is None:
            raise ValueError("Must fit model first with cross_sectional_regression()")

        X = pd.DataFrame({
            'ln_prate': [np.log(participation_rate)],
            'ln_vol': [np.log(daily_vol)],
            'ln_spread': [np.log(rel_spread)],
            'urgency_score': [urgency],
            'ln_price': [np.log(price)],
        })
        return np.exp(self.model_fit.predict(X)[0])

    def attribution_report(self, orders_decomp: pd.DataFrame) -> pd.DataFrame:
        summary = orders_decomp.groupby('symbol').agg({
            'delay_bps': ['mean', 'std'],
            'spread_bps': ['mean'],
            'impact_bps': ['mean', 'std'],
            'opportunity_bps': ['mean'],
            'commission_bps': ['mean'],
            'total_IS_bps': ['mean', 'std'],
            'order_id': 'count'
        }).round(3)
        summary.columns = ['_'.join(c) for c in summary.columns]
        return summary


np.random.seed(12)
N = 200

trades_df = pd.DataFrame({
    'is_bps': np.abs(
        0.5 + 15 * np.sqrt(np.random.uniform(0.01, 0.15, N)) *
        np.random.uniform(0.005, 0.025, N) / 0.015 +
        np.random.normal(0, 2, N)
    ),
    'participation_rate': np.random.uniform(0.01, 0.15, N),
    'daily_vol': np.random.uniform(0.005, 0.03, N),
    'rel_spread': np.random.uniform(0.0001, 0.005, N),
    'urgency_score': np.random.uniform(0, 1, N),
    'price': np.random.uniform(20, 500, N),
})

model = TCAAttributionModel()
result = model.cross_sectional_regression(trades_df)
print("Cross-Sectional Attribution Model:")
print(f"R-squared: {result['rsquared']:.4f}")
print("\nCoefficients (log-linear):")
for param, val in result['params'].items():
    pval = result['pvalues'][param]
    stars = '***' if pval < 0.001 else '**' if pval < 0.01 else '*' if pval < 0.05 else ''
    print(f"  {param:25s}: {val:+.4f} {stars}")

print("\nIS Prediction Examples:")
print(f"  Low impact (1% ADV, low vol): {model.predict_is(0.01, 0.008, 0.0005, 0.3, 100):.2f} bps")
print(f"  Med impact (5% ADV, med vol): {model.predict_is(0.05, 0.015, 0.001, 0.5, 100):.2f} bps")
print(f"  High impact (15% ADV, hi vol): {model.predict_is(0.15, 0.025, 0.002, 0.9, 50):.2f} bps")

