# -*- coding: utf-8 -*-
"""Venue Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from collections import defaultdict

class VenueAnalyzer:
    def __init__(self):
        self.venue_fills = defaultdict(list)

    def add_fill(self, venue: str, qty: float, price: float,
                 mid_at_fill: float, mid_5min_after: float,
                 side: int, qty_sent: float):
        self.venue_fills[venue].append({
            'qty': qty,
            'price': price,
            'mid_at_fill': mid_at_fill,
            'mid_5min_after': mid_5min_after,
            'side': side,
            'qty_sent': qty_sent,
            'eff_spread': 2 * side * (price - mid_at_fill),
            'adverse_sel': side * (mid_5min_after - mid_at_fill),
        })

    def venue_metrics(self) -> pd.DataFrame:
        rows = []
        for venue, fills in self.venue_fills.items():
            df = pd.DataFrame(fills)
            w = df['qty'] / df['qty'].sum()

            fill_rate = df['qty'].sum() / df['qty_sent'].sum()
            eff_spread = (df['eff_spread'] * w).sum()
            adverse_sel = (df['adverse_sel'] * w).sum()

            rows.append({
                'Venue': venue,
                'Fills': len(df),
                'Total Volume': df['qty'].sum(),
                'Fill Rate': fill_rate,
                'Eff Spread (price)': eff_spread,
                'Adverse Selection (price)': adverse_sel,
                'Realized Spread': eff_spread - adverse_sel * 2,
                'Quality Score': fill_rate * 100 - eff_spread * 10 - adverse_sel * 20
            })

        return pd.DataFrame(rows).sort_values('Quality Score', ascending=False)

    def compute_vpin(self, trades: pd.DataFrame, bucket_size: float) -> pd.DataFrame:
        trades = trades.copy()
        trades['buy_vol'] = np.where(trades['quantity'] > 0, trades['quantity'], 0)
        trades['sell_vol'] = np.where(trades['quantity'] < 0, -trades['quantity'], 0)
        trades['cumvol'] = trades['quantity'].abs().cumsum()

        vpins = []
        bucket_n = 0
        current_buy = 0.0
        current_sell = 0.0

        for idx, row in trades.iterrows():
            current_buy += row['buy_vol']
            current_sell += row['sell_vol']

            if trades.loc[idx, 'cumvol'] >= (bucket_n + 1) * bucket_size:
                imbalance = abs(current_buy - current_sell)
                total = current_buy + current_sell
                vpin = imbalance / total if total > 0 else 0
                vpins.append({
                    'bucket': bucket_n,
                    'vpin': vpin,
                    'buy_vol': current_buy,
                    'sell_vol': current_sell
                })
                bucket_n += 1
                current_buy = 0.0
                current_sell = 0.0

        return pd.DataFrame(vpins)

    def optimal_venue_mix(self, target_qty: float, min_fill_rate: float = 0.5) -> pd.DataFrame:
        metrics = self.venue_metrics()
        metrics = metrics[metrics['Fill Rate'] >= min_fill_rate]

        allocation = []
        remaining = target_qty

        for _, row in metrics.iterrows():
            capacity = row['Total Volume'] * 0.05
            alloc = min(remaining, capacity)
            if alloc <= 0:
                continue
            allocation.append({
                'Venue': row['Venue'],
                'Allocation': alloc,
                'Pct': alloc / target_qty,
                'Expected ES': row['Eff Spread (price)'],
                'Fill Rate': row['Fill Rate'],
            })
            remaining -= alloc
            if remaining <= 0:
                break

        return pd.DataFrame(allocation)


np.random.seed(12)
analyzer = VenueAnalyzer()
venues = {
    'NYSE': {'spread_mu': 0.02, 'spread_sd': 0.005, 'AS_mu': 0.005, 'fill_rate': 0.92},
    'Nasdaq': {'spread_mu': 0.015, 'spread_sd': 0.004, 'AS_mu': 0.004, 'fill_rate': 0.95},
    'IEX': {'spread_mu': 0.018, 'spread_sd': 0.005, 'AS_mu': 0.001, 'fill_rate': 0.78},
    'DarkPool_A': {'spread_mu': 0.001, 'spread_sd': 0.002, 'AS_mu': 0.012, 'fill_rate': 0.45},
    'DarkPool_B': {'spread_mu': 0.001, 'spread_sd': 0.001, 'AS_mu': 0.003, 'fill_rate': 0.55},
    'Wholesale_OTC': {'spread_mu': 0.008, 'spread_sd': 0.003, 'AS_mu': -0.001, 'fill_rate': 0.99},
}

for venue, params in venues.items():
    n_fills = np.random.randint(20, 100)
    for _ in range(n_fills):
        qty = np.random.randint(100, 5000)
        mid = 100.0
        eff_s = np.random.normal(params['spread_mu'], params['spread_sd'])
        AS = np.random.normal(params['AS_mu'], 0.002)
        fill = np.random.random() < params['fill_rate']
        if fill:
            analyzer.add_fill(
                venue=venue, qty=qty,
                price=mid + eff_s / 2, mid_at_fill=mid,
                mid_5min_after=mid + AS, side=1,
                qty_sent=qty / params['fill_rate']
            )

metrics = analyzer.venue_metrics()
print("Venue Analysis Results:")
print(metrics[['Venue', 'Fill Rate', 'Eff Spread (price)', 'Adverse Selection (price)', 'Quality Score']].to_string(index=False))

print("\nOptimal Venue Routing for 100,000 shares:")
routing = analyzer.optimal_venue_mix(100000)
print(routing.to_string(index=False))

n_trades = 5000
informed_fraction = 0.3
trade_flow = np.where(
    np.random.random(n_trades) < informed_fraction,
    np.random.choice([-1, 1]) * np.abs(np.random.normal(500, 100, n_trades)),
    np.random.normal(0, 300, n_trades)
)
trades_df = pd.DataFrame({'quantity': trade_flow, 'price': 100 + np.cumsum(trade_flow * 0.0001)})
vpin_results = analyzer.compute_vpin(trades_df, bucket_size=5000)
print(f"\nVPIN Analysis: Mean VPIN = {vpin_results['vpin'].mean():.4f}, Max = {vpin_results['vpin'].max():.4f}")
print("  (VPIN > 0.5 suggests high toxicity; threshold for flow toxicity alert)")

