# -*- coding: utf-8 -*-
"""Real-Time Monitoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Callable, Optional
from queue import Queue
import threading
import time

class RealTimeTCAMonitor:
    def __init__(self, order_id: str, symbol: str, side: int,
                 target_qty: float, arrival_mid: float,
                 expected_IS_bps: float, IS_std_bps: float,
                 warning_k: float = 2.0, critical_k: float = 3.0,
                 alert_callback: Optional[Callable] = None):
        self.order_id = order_id
        self.symbol = symbol
        self.side = side
        self.Q_star = target_qty
        self.M0 = arrival_mid
        self.expected_IS = expected_IS_bps
        self.IS_std = IS_std_bps
        self.warning_thresh = expected_IS_bps + warning_k * IS_std_bps
        self.critical_thresh = expected_IS_bps + critical_k * IS_std_bps

        self.fills = []
        self.Q_filled = 0.0
        self.current_mid = arrival_mid
        self.alerts_fired = []
        self.alert_callback = alert_callback or self._default_alert

        self.IS_history = []
        self.participation_history = []

    def _default_alert(self, alert_dict: dict):
        print(f"[ ALERT ] {alert_dict['level']:8s} | {alert_dict['message']}")

    def on_fill(self, qty: float, fill_price: float, timestamp: datetime):
        fill = {'qty': qty, 'price': fill_price, 'time': timestamp}
        self.fills.append(fill)
        self.Q_filled += qty

        IS = self._compute_running_IS()
        self.IS_history.append({'time': timestamp, 'IS_bps': IS, 'Q_filled': self.Q_filled})

        self._check_alerts(IS, timestamp)
        return IS

    def on_market_data(self, mid: float, timestamp: datetime):
        self.current_mid = mid

    def _compute_running_IS(self) -> float:
        if not self.fills:
            return 0.0

        fill_cost = sum(
            f['qty'] * self.side * (f['price'] - self.M0)
            for f in self.fills
        )

        Q_remaining = self.Q_star - self.Q_filled
        opp_cost = Q_remaining * self.side * (self.current_mid - self.M0)

        total_IS = (fill_cost + opp_cost) / (self.Q_star * self.M0) * 10000
        return total_IS

    def _check_alerts(self, IS: float, timestamp: datetime):
        if IS > self.critical_thresh:
            alert = {
                'level': 'CRITICAL',
                'IS_bps': IS,
                'threshold': self.critical_thresh,
                'time': timestamp,
                'message': (f"{self.symbol}: IS={IS:.1f} bps >> critical threshold {self.critical_thresh:.1f}bps. CONSIDER SUSPENDING EXECUTION."),
                'action': 'suspend'
            }
            self.alerts_fired.append(alert)
            self.alert_callback(alert)

        elif IS > self.warning_thresh:
            alert = {
                'level': 'WARNING',
                'IS_bps': IS,
                'threshold': self.warning_thresh,
                'time': timestamp,
                'message': f"{self.symbol}: IS={IS:.1f} bps > warning threshold {self.warning_thresh:.1f}bps."
            }
            self.alerts_fired.append(alert)
            self.alert_callback(alert)

    @property
    def fill_rate(self) -> float:
        return self.Q_filled / self.Q_star

    @property
    def running_IS(self) -> float:
        return self._compute_running_IS()

    def status_report(self) -> dict:
        IS = self._compute_running_IS()
        return {
            'order_id': self.order_id,
            'symbol': self.symbol,
            'fill_rate': f"{self.fill_rate:.1%}",
            'Q_filled': self.Q_filled,
            'Q_remaining': self.Q_star - self.Q_filled,
            'running_IS_bps': round(IS, 2),
            'expected_IS_bps': self.expected_IS,
            'IS_z_score': (IS - self.expected_IS) / self.IS_std if self.IS_std > 0 else 0,
            'alerts_count': len(self.alerts_fired),
            'current_mid': self.current_mid,
        }


class ExecutionDeskMonitor:
    def __init__(self):
        self.order_monitors = {}

    def add_order(self, monitor: RealTimeTCAMonitor):
        self.order_monitors[monitor.order_id] = monitor

    def desk_snapshot(self) -> pd.DataFrame:
        reports = [m.status_report() for m in self.order_monitors.values()]
        return pd.DataFrame(reports).set_index('order_id')

    def aggregate_IS_bps(self) -> float:
        total_notional = sum(
            m.Q_star * m.M0 for m in self.order_monitors.values()
        )
        weighted_IS = sum(
            m.Q_star * m.M0 * m.running_IS
            for m in self.order_monitors.values()
        )
        return weighted_IS / total_notional if total_notional > 0 else 0


# Simulation: Monitor 3 live orders
print("=== Real-Time TCA Monitor Simulation ===\n")

desk = ExecutionDeskMonitor()
t_base = datetime(2024, 1, 15, 9, 30)

monitors = {
    'AAPL': RealTimeTCAMonitor('ORD001', 'AAPL', 1, 100_000, 185.0, expected_IS_bps=12.0, IS_std_bps=4.0),
    'MSFT': RealTimeTCAMonitor('ORD002', 'MSFT', -1, 50_000, 380.0, expected_IS_bps=8.0, IS_std_bps=3.0),
    'NVDA': RealTimeTCAMonitor('ORD003', 'NVDA', 1, 30_000, 500.0, expected_IS_bps=18.0, IS_std_bps=6.0),
}

for m in monitors.values():
    desk.add_order(m)

np.random.seed(77)
for minute in range(1, 30):
    t = t_base + timedelta(minutes=minute)

    for sym, mon in monitors.items():
        if mon.fill_rate < 0.99:
            mid_change = np.random.normal(0.001, 0.05) * mon.side
            mon.on_market_data(mon.current_mid + mid_change, t)

            if np.random.random() < 0.6:
                qty = min(np.random.randint(500, 3000), int(mon.Q_star - mon.Q_filled))
                impact = 0.01 * np.random.exponential(1.0)
                fill_p = mon.current_mid + mon.side * (0.01 + impact)
                if qty > 0:
                    mon.on_fill(qty, fill_p, t)

print("\nFinal Desk Snapshot:")
snap = desk.desk_snapshot()
print(snap[['symbol', 'fill_rate', 'running_IS_bps', 'expected_IS_bps', 'IS_z_score', 'alerts_count']].to_string())
print(f"\nDesk Aggregate IS: {desk.aggregate_IS_bps():.2f} bps")

for sym, mon in monitors.items():
    print(f"\n{sym} Alerts: {len(mon.alerts_fired)}")
    for a in mon.alerts_fired[-2:]:
        print(f"  {a['time'].strftime('%H:%M')} [{a['level']}]: {a['message']}")

