# -*- coding: utf-8 -*-
"""Optimal Spreads.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def optiaml_spreads(gamma, sigma, T_minus_t, k):
  inv_risk = gamma * sigma ** 2 * T_minus_t
  adv_sel = (2/gamma) * np.log(1 + gamma/k)
  return inv_risk + adv_sel

def as_quotes(S, q, gamma, sigma, T_minus_t, k):
  r = S - q * gamma * sigma**2 * T_minus_t
  half_spread = optiaml_spreads(gamma, sigma, T_minus_t, k)
  return r + half_spread, r - half_spread

S, sigma, gamma, k = 100.0, 0.02, 0.1, 1.5
T_remaining = 30.0
q_range = np.arange(-20, 21)

asks, bids = zip(*[as_quotes(S, q, gamma, sigma, T_remaining, k) for q in q_range])

asks, bids = np.array(asks), np.array(bids)

plt.figure(figsize=(12, 5))
plt.plot(q_range, asks, 'r-o', markersize=3, label='Ask quote')
plt.plot(q_range, bids, 'b-o', markersize=3, label='Bid quote')
plt.axhline(S, color='k', linestyle='--', label='Mid-price')
plt.fill_between(q_range, bids, asks, alpha=0.15, color='green', label='Spread')
plt.xlabel("Inventory q")
plt.ylabel("Price ($)")
plt.title('As Optimal Quote vs Inventory')
plt.legend()
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.savefig("as_quote_vs_inventory.png", dpi=150)
plt.show()

