# -*- coding: utf-8 -*-
"""Reservation Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def reservation_price(S, q, gamma, sigma, T_minus_t):
  return S - q * gamma * sigma**2 * T_minus_t

S0, sigma, gamma = 100.0, 0.002, 0.1
T = 60
q_range = np.arange(-20, 21)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for t_remaining in [60, 45, 30, 15, 5]:
  r = reservation_price(S0, q_range, gamma, sigma, t_remaining)
  axes[0].plot(q_range, r, label=f"T-t={t_remaining} min")
axes[0].axhline(S0, color='k', linestyle='--', label='Mid - price S')
axes[0].set_xlabel('Inventory q')
axes[0].set_ylabel('Reservation Price r ($)')
axes[0].set_title('Reservation Price vs Inventory')
axes[0].legend(fontsize=8)
axes[0].grid(True, alpha=0.3)

for g in [0.01, 0.05, 0.1, 0.5]:
  r = reservation_price(S0, q_range, g, sigma, 30)
  axes[1].plot(q_range, r, label=f"gamma={g}")

axes[1].axhline(S0, color='k', linestyle='--')
axes[1].set_xlabel("Inventory q")
axes[1].set_title("Reservation Price vs Risk Aversion")
axes[1].legend(fontsize=8)
axes[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('reservation_price.png', dpi=150)
plt.show()

