# -*- coding: utf-8 -*-
"""Arrival Intensities and Order Flow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.stats import poisson

def neg_log_likelihood(params, deltas, fills, dt):
  log_A, k = params
  A = np.exp(log_A)
  lambdas = A * np.exp(-k * deltas)

  ll = np.sum(fills * np.log(lambdas * dt + 1e-12) - lambdas * dt)
  return -ll

def calibrate_intensity(deltas, fills, dt=1.0):
  x0 = [np.log(10), 1.0]
  bounds = [(-5, 10), (0.01, 100)]

  res = minimize(neg_log_likelihood, x0, args=(deltas, fills, dt), bounds=bounds, method='L-BFGS-B')
  A_hat = np.exp(res.x[0])
  k_hat = res.x[1]
  return A_hat, k_hat, res.fun

np.random.seed(12)
true_A, true_k = 8.0, 1.2
n_obs = 5000
deltas_obs = np.random.uniform(0, 3, n_obs)
lambdas_true = true_A * np.exp(-true_k * deltas_obs)
fills_obs = np.random.binomial(1, np.minimum(lambdas_true * 0.1, 1.0))

A_hat, k_hat, _ = calibrate_intensity(deltas_obs, fills_obs, dt=0.1)
print(f"True: A={true_A}, k={true_k:.2f}")
print(f"Estimated: A={A_hat:.2f}, k={k_hat:.2f}")

