# -*- coding: utf-8 -*-
"""Calibration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.stats import poisson
from collections import deque
from sklearn.linear_model import LinearRegression

def calibrate_intensity_regression(deltas, fill_counts, dt):
  fill_rates = fill_counts / dt
  fill_rates = np.maximum(fill_rates, 1e-8)
  log_rates = np.log(fill_rates)

  X = deltas.reshape(-1, 1)
  y = log_rates

  reg = LinearRegression().fit(X, y)
  log_A_hat = reg.intercept_
  k_hat = -reg.coef_[0]

  A_hat = np.exp(log_A_hat)
  return A_hat, k_hat, reg.score(X, y)

def bin_by_distance(deltas_raw, fills_raw, n_bins=20):
  """
  Bin fill observations by quote distance.
  Returns : bin_centers , fill_rates
  """
  delta_min, delta_max = deltas_raw.min(), deltas_raw.max()
  bins = np.linspace(delta_min, delta_max, n_bins + 1)
  bin_centers = 0.5 * (bins[:-1] + bins[1:])

  fill_rates = np.zeros(n_bins)
  for i in range(n_bins):
    mask = (deltas_raw >= bins[i]) & (deltas_raw < bins[i + 1])

    if mask.sum() > 0:
      fill_rates[i] = fills_raw[mask].mean()

  return bin_centers, fill_rates

class ASCalibrator:
  def __init__(self, halflife_sigma=10.0,  # minutes
               halflife_intensity=30.0, # minutes
               gamma=0.1,
               T=60.0): # session horizon in minutes
    self.gamma = gamma
    self.T = T

    # Exponential decay factors (per minute)
    self.alpha_s = np.exp(-np.log(2) / halflife_sigma)
    self.alpha_i = np.exp(-np.log(2) / halflife_intensity)

    # Running statistics for sigma (Welford online)
    self.S_prev = None
    self.ema_var = None  # exponential moving variance of dS

    # Running statistics for intensity
    self.fill_history = deque(maxlen=1000)
    self.A_hat = 10.0
    self.k_hat = 1.5

  def update_sigma(self, S_new, dt):
    """ Update volatility estimate with new mid-price observation. """
    if self.S_prev is not None:
      dS = S_new - self.S_prev
      if self.ema_var is None:
        self.ema_var = dS**2 / dt
      else:
        self.ema_var = (self.alpha_s * self.ema_var +
                        (1 - self.alpha_s) * dS**2 / dt)
    self.S_prev = S_new
    return np.sqrt(self.ema_var) if self.ema_var else None

  def update_intensity(self, delta, filled, dt):
    """ Update intensity estimate with fill observation."""
    self.fill_history.append((delta, filled, dt))

    if len(self.fill_history) >= 50:
      deltas = np.array([x[0] for x in self.fill_history])
      fills = np.array([x[1] for x in self.fill_history])
      rates = fills / dt

      # Simple log-linear regression
      valid = rates > 0
      if valid.sum() >= 10:
        log_rates = np.log(np.maximum(rates[valid], 1e-8))
        d_valid = deltas[valid]
        p = np.polyfit(d_valid, log_rates, 1) # degree -1 polynomial

        self.k_hat = max(-p[0], 0.01)
        self.A_hat = np.exp(p[1])

  def get_optimal_quotes(self, S, q, t):
    """ Return (ask, bid) under current parameter estimates. """
    if self.ema_var is None:
      return S + 0.5, S - 0.5 # fallback

    sigma = np.sqrt(self.ema_var)
    T_minus_t = max(self.T - t, 0.001)

    r = S - q * self.gamma * sigma**2 * T_minus_t
    half_spread = 0.5 * (self.gamma * sigma**2 * T_minus_t +
                         (2/self.gamma) * np.log(1 + self.gamma / self.k_hat))

    return r + half_spread, r - half_spread

