# -*- coding: utf-8 -*-
"""Dynamic Quotes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import time
import numpy as np
from enum import Enum
import numpy as np
import pandas as pd
import matplotlib . pyplot as plt

class QuoteUpdateReason(Enum):
  MID_PRICE_MOVE = "mid_price_move"
  FILL_EVENT = "fill_event"
  TIME_DECAY = "time_decay"
  RECALIBRATION = "recalibration"
  HARD_CONSTRAINT = "hard_constraint"

class DynamicASQuoter:
  def __init__(self, params, min_quote_life=0.01,
               max_quote_age=1.0):
    self.p = params
    self.min_quote_life = min_quote_life
    self.max_quote_age = max_quote_age

    self.current_ask = None
    self.current_bid = None
    self.last_quote_time = 0.0
    self.inventory = 0
    self.S = None
    self.session_start = time.time()

  def t_elapsed(self):
    return (time.time() - self.session_start) / 60.0

  def should_requote(self, reason, new_S=None):
    age = time.time() - self.last_quote_time

    if age < self.min_quote_life:
      return False
    if age > self.max_quote_age:
      return True
    if reason in [QuoteUpdateReason.FILL_EVENT,
                  QuoteUpdateReason.HARD_CONSTRAINT]:
      return True
    if reason == QuoteUpdateReason.MID_PRICE_MOVE and new_S is not None:
      return abs(new_S - self.S) >= 0.01
    return False

  def compute_and_send_quotes(self, reason):
    t = self.t_elapsed()
    T_minus_t = max(self.p['T'] - t, 0.001)

    r = self.S - self.inventory * self.p['gamma'] * \
        self.p['sigma']**2 * T_minus_t
    half_spread = 0.5 * (
        self.p['gamma'] * self.p['sigma']**2 * T_minus_t +
        (2/self.p['gamma']) * np.log(1 + self.p['gamma']/
                                     self.p['k'])
    )

    new_ask = r + half_spread
    new_bid = r - half_spread

    if new_ask != self.current_ask or new_bid != self.current_bid:
      self._cancel_quotes()
      self._send_quotes(new_ask, new_bid)
      self.current_ask = new_ask
      self.current_bid = new_bid
      self.last_quote_time = time.time()

    return new_ask, new_bid

  def on_market_data(self, new_S):
    old_S = self.S
    self.S = new_S
    if self.should_requote(QuoteUpdateReason.MID_PRICE_MOVE, new_S):
      self.compute_and_send_quotes(QuoteUpdateReason.MID_PRICE_MOVE)

  def on_fill(self, side, size=1):
    if side == 'bid':
      self.inventory += size
    else:
      self.inventory -= size
    self.compute_and_send_quotes(QuoteUpdateReason.FILL_EVENT)

  def _cancel_quotes(self):
    pass

  def _send_quotes(self, ask, bid):
    pass

def simulate_as_market_maker(S0 =100.0, sigma=0.02, gamma =0.1, k=1.5, A=10.0, T=60.0, dt=1/60.0, n_paths=200, q_max=20, seed=12):
  np.random.seed(seed)
  n_steps = int(T/dt)
  results = {'pnl ': [] , 'inventory ': [] , 'spread ': [] , 'ask ': [] , 'bid ': [] , 'mid ': []}
  all_final_pnl = []

  for path in range(n_paths):
    S = S0
    q = 0
    X = 0

    for step in range(n_steps):
      t = step * dt
      T_minus_t = max(T - t, dt)
      r = S - q * gamma * sigma **2 * T_minus_t
      half_spread = 0.5 * (gamma * sigma **2 * T_minus_t + (2/ gamma) * np.log (1 + gamma / k))
      ask = r + half_spread
      bid = r - half_spread
      delta_a = ask - S if q < q_max else np.inf
      delta_b = S - bid if q > - q_max else np.inf
      p_ask = (1 - np.exp (-A * np.exp(-k * delta_a ) * dt)) if delta_a < np.inf else 0
      p_bid = (1 - np.exp (-A * np.exp(-k * delta_b ) * dt)) if delta_b < np.inf else 0
      fill_ask = np.random.binomial (1 , p_ask)
      fill_bid = np.random.binomial (1 , p_bid)
      X += fill_ask * ask - fill_bid * bid
      q += fill_bid - fill_ask
      S += sigma * np.sqrt ( dt ) * np.random.randn ()

    W_T = X + q * S
    all_final_pnl.append ( W_T )
  return pd.Series( all_final_pnl )

pnl_series = simulate_as_market_maker ()

print (f" Mean P&L: ${pnl_series.mean():.4f}")
print (f"Std P&L: ${pnl_series.std():.4f}")
print (f" Sharpe : {pnl_series.mean()/ pnl_series.std():.2f}")
print (f"Win rate : {(pnl_series > 0).mean():.1%} ")

plt.figure(figsize =(10, 5))
plt.hist ( pnl_series , bins =30 , color ='blue', edgecolor ='white', alpha =0.8)
plt.axvline ( pnl_series . mean () , color ='red', linestyle ='--',
label = f'Mean = ${ pnl_series . mean () :.2f}')
plt.xlabel('Terminal P&L ($)')
plt.ylabel('Frequency ')
plt.title('AS Market Maker P&L Distribution (200 simulations )')
plt.legend()
plt.grid( True , alpha =0.3)
plt.tight_layout()
plt.savefig('as_pnl_dist.png', dpi =150)

