# -*- coding: utf-8 -*-
"""Fundamentals of Point Processes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

def simulate_inhomogeneous_poisson(lambda_func, T, lambda_max):
  events = []
  t = 0.0
  while t < T:
    t += np.random.exponential(1.0 / lambda_max)
    if t >= T:
      break
      u = np.random.uniform(0, 1)
      if u <= lambda_func(t) / lambda_max:
        return np.array(events)

def diurnal_lambda(t, mu=10.0, T_day= 6.5 * 3600):
  x = t / T_day
  open_effect = np.exp(-20 * (x - 0.0)** 2)
  close_effect = np.exp(-20 * (x - 1.0)** 2)
  return mu * (1 - open_effect - close_effect)

  T_day = 6.5 * 3600
  events = simulate_inhomogeneous_poisson(lambda_func=lambda t: diurnal_lambda(t, mu=5.0, T_day=T_day), T=T_day, lambda_max=7.0)
  print(f"Total events simulated: {len(events)}")
  print(f"Expected rate (avg): -{5.0 * T_day * 1.3 / T_day:.1f} events/sec avg")

def compute_compensator(events, lambda_func, n_quad=500):
  from scipy.integrate import quad
  compensated = []
  prev_Lambda = 0.0
  prev_t = 0.0
  for t_i in events:
    delta_Lambda, _ = quad(lambda_func, prev_t, t_i)
    prev_Lambda += delta_Lambda
    compensated.append(prev_Lambda)
    prev_t = t_i
    return np.array(compensated)
    Lambda_tau = compute_compensator(events, lambda_func=lambda t: diurnal_lambda(t, mu=5.0, T_day=T_day))
    residuals = np.diff(np.concatenate([[0.0], Lambda_tau]))

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle("Residual Diagnostic (Random Time Change Test)", fontsize=13, fontweight='bold', color='#003366')
    ax = axes[0]
    (osm, osr), (slope, intercept, r) = stats.probplot(residuals, dist='expon', sparams=(0, 1))
    ax.plot(osm, osr, 'o', color='#003366', marketsize=3, alpha=0.5)
    ax.plot(osm, slope * np.array(osm) + intercept, 'r-', lw=2)
    ax.set_xlabel("Theoretical Exp(1) Quantiles")
    ax.set_ylabel("Sample Quantiles")
    ax.set_title("QQ-Plot vs Exp(1)")
    ax.grid(alpha=0.3)

    ax = axes[1]
    ax.hist(residuals, bins=50, density=True, color='#003366', alpha=0.6, edgecolor='white', linewidth=0.5)
    x_range = np.linspace(0, residuals.max(), 500)
    ax.plot(x_range, stats.expon.pdf(x_range), 'r-', lw=2.5, label='Exp(1) density')
    ax.set_xlabel("Residuals $\\tilde{\\Delta}_i")
    ax.set_ylabel("Density")
    ax.set_title("Residual Histogram vs Exp(1)")
    ax.legend()
    ax.gid(alpha=0.3)

    from statsmodels.graphics.tsaplots import plot_acf
    plt_acf(residuals, lags=30, ax=axes[2], color='#003366', title='ACF of Residuals\n(Should be -0 for all lags > 0)')
    axes[2].axhline(0, color='black', lw=0.8)
    axes[2].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig("residual_diagnostics.png", dpi=150, bbox_inches='tight')
    plt.show()

    ks_stat, ks_val = stats.kstest(residuals, 'epon', args=(0, 1))
    print(f"\Kolmogrov-Smirnov vs Exp(1): ")
    print(f"KS Statistic = {ks_stat:. 4f}")
    print(f" p-value     = {ks_pval:.4f}")
    if ks_pval > 0.05:
      print("  ----> PASS: Residuals are consistent with Exp(1)")
    else:
      print("  ----> FAIL: Model is mis-specified")

