# -*- coding: utf-8 -*-
"""The Hawkes Process: Self-Exciting Dynamics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from dataclasses import dataclass
from typing import List , Tuple , Optional
import matplotlib . pyplot as plt


@dataclass
class HawkesParams :
  """ Parameters for exponential - kernel univariate Hawkes process ."""

  mu : float # Baseline intensity
  alpha : float # Jump size per event ( branching ratio = alpha )
  beta : float # Decay rate

  def __post_init__ ( self ) :
    if self . alpha >= 1.0:
      raise ValueError ( f"Branching ratio alpha ={self.alpha:.4f} >= 1: process will explode !")
    if self . mu <= 0 or self . beta <= 0:
      raise ValueError ("mu and beta must be positive ")

  @property
  def mean_intensity ( self ) -> float :
    """ Stationary mean intensity E[ lambda ] = mu / (1 - alpha )."""
    return self . mu / (1.0 - self . alpha )

  @property
  def branching_ratio ( self ) -> float :
    return self . alpha


class HawkesSimulator :
  """
  Simulate a univariate Hawkes process using Ogata's modified thinning
  algorithm . This is the standard production algorithm .

  Reference : Ogata (1981) , "On Lewis' simulation method for point processes " ,
  IEEE Transactions on Information Theory .
  """

  def __init__ ( self , params : HawkesParams , seed : Optional [int] = None ):
    self . params = params
    self .rng = np. random . default_rng ( seed )

  def intensity (self , t: float , events : np. ndarray ) -> float :
    """
    Compute lambda (t) given past events .

    lambda (t) = mu + alpha * beta * sum_ { tau_i < t} exp( - beta *(t - tau_i ))
    """
    mu , alpha , beta = self . params .mu , self . params .alpha , self . params . beta
    past = events [ events < t]
    return mu + alpha * beta * np.sum(np.exp( - beta * (t - past )))

  def simulate (self , T: float ) -> np. ndarray :
    """
    Ogata thinning algorithm for exact simulation of Hawkes process .

    Returns array of event times in [0 , T].
    """
    mu , alpha , beta = self . params .mu , self . params .alpha , self . params . beta

    events = []
    t = 0.0

    # Current upper bound on intensity
    lambda_bar = mu # starts at baseline (no events yet)

    while t < T:
      # Step 1: Draw next candidate time from homogeneous Poisson (lambda_bar )
      t += self .rng . exponential (1.0 / lambda_bar )

      if t >= T:
        break

      # Step 2: Compute true intensity at candidate time
      lambda_t = self . intensity (t, np. array ( events ) if events else np. array ([]) )

      # Step 3: Accept / reject
      u = self .rng . uniform (0 , 1)
      if u <= lambda_t / lambda_bar :
        events . append (t)
        # Update upper bound : jump by alpha * beta at new event
        lambda_bar = lambda_t + alpha * beta
      else :
        # Rejected : update upper bound to true value ( tighter bound )
        lambda_bar = lambda_t

    return np. array ( events )

  def simulate_path (self , T: float , dt: float = 0.001) -> Tuple [np. ndarray , np. ndarray ]:
    """
    Return ( time_grid , intensity_path ) for plotting .
    Events are simulated first , then intensity is evaluated on grid .
    """
    events = self . simulate (T)
    time_grid = np. arange (0 , T, dt)
    intensity_path = np. array ([
        self . intensity (t, events ) for t in time_grid
    ])
    return time_grid , intensity_path , events

# SIMULATION AND ANALYSIS


params = HawkesParams (mu =1.0 , alpha =0.6 , beta =2.0)
print (f"Branching ratio : {params.branching_ratio:.2f}")
print (f"Mean intensity : {params.mean_intensity:.2f} events / sec ")

simulator = HawkesSimulator (params , seed =42)
T = 50.0 # 50 seconds

time_grid , intensity_path , events = simulator . simulate_path (T , dt =0.005)


print (f"Events in [{0} , {T}]: {len(events)}")
print (f"Observed rate : {len(events)/T:.2f} events /sec ")
print (f"Theoretical rate : {params.mean_intensity:.2f} events / sec ")


# AUTOCORRELATION ANALYSIS


def compute_event_acf ( events : np. ndarray , max_lag : int = 20 ,
                      bin_size : float = 0.1) -> np. ndarray :
  """
  Compute autocorrelation function of the binned counting process .
  Bins events into intervals of size bin_size , then compute ACF .
  """
  from statsmodels .tsa. stattools import acf
  T_max = events [ -1] if len( events ) > 0 else 1.0
  bins = np. arange (0 , T_max + bin_size , bin_size )
  counts , _ = np. histogram (events , bins = bins )
  acf_values = acf (counts , nlags = max_lag , fft= True ) [1:] # exclude lag 0
  return acf_values


acf_values = compute_event_acf (events , max_lag =30)

fig , axes = plt . subplots (1 , 2 , figsize =(14 , 5))
fig . suptitle ("Hawkes Process Analysis" , fontweight ='bold' ,
               color ='#003366')
# Intensity path
ax = axes [0]
ax . fill_between ( time_grid , params . mu , intensity_path ,
                   alpha =0.3 , color ='#003366' , label ='Self - excitation ')
ax . plot ( time_grid , intensity_path , color ='#003366' , lw =1.0 ,
          label ='$\lambda (t)$')
ax . axhline ( params . mu , color ='gray' , ls ='--' , lw =1.5 , label = f'$\mu ={params.mu}$' )
ax . axhline ( params . mean_intensity , color ='#b40000' , ls ='-.' ,
               lw =1.5 ,
               label = f'$\bar{{\lambda}}$={params.mean_intensity:.1f}$' )
ax . scatter ( events , np. zeros_like ( events ) - 0.1 , s =5 , color ='#b40000' ,
             zorder =5 , label ='Events ')
ax . set_xlabel ("Time (s)") ; ax . set_ylabel ("$\lambda (t)$")
ax . set_title ("Intensity Path ") ; ax . legend ( fontsize =8) ; ax . grid ( alpha =0.3)

# ACF
ax = axes [1]
lags = np. arange (1 , len( acf_values ) +1)
ax . bar ( lags , acf_values , color =['#003366' if v > 0 else '#b40000' for v in acf_values ] ,
           alpha =0.7 , edgecolor ='white')
ci = 1.96 / np. sqrt (len( events ) )
ax . axhline ( ci , color ='gray' , ls ='--' , lw =1.2 , label = f'95% CI ({ci:.3f})' )
ax . axhline ( - ci , color ='gray' , ls ='--' , lw =1.2)
ax . axhline (0 , color ='black' , lw =0.8)
ax . set_xlabel ("Lag ") ; ax . set_ylabel ("ACF")
ax . set_title ("ACF of Binned Counting Process \n( Hawkes shows positive autocorrelation )")
ax . legend ( fontsize =9) ; ax . grid ( alpha =0.3)

plt . tight_layout ()
plt . savefig ("hawkes_analysis .png", dpi =150 , bbox_inches ='tight' )
plt . show ()

