# -*- coding: utf-8 -*-
"""Predicting Future Event Rates in Real Time.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from typing import Optional

class HawkesForecaster:
  def __init__(self, mu: float, alpha: float, beta: float):
    assert 0 < alpha < 1, f"alpha={alpha} violates stationarity"
    self.mu = mu
    self.alpha = alpha
    self.beta = beta

    self.R_current = 0.0
    self.t_last = 0.0
    self.n_events = 0.0

  def update(self, t_event: float) -> float:
    dt = t_event - self.t_last
    self.R_current += np.exp(-self.beta * dt)

    self.R_current += self.alpha * self.beta

    self.t_last = t_event
    self.n_events += 1

    return self.mu + self.R_current

  def intensity_at(self, t: float) -> float:
    dt = t - self.t_last
    R_t = self.R_current * np.exp(-self.beta * dt)
    return self.mu + R_t

  def forecast_count(self, t_now: float, horizon_sec: float) -> float:
    lam = self.intensity_at(t_now)
    h = horizon_sec
    mean_reversion_rate = self.beta * (1 - self.alpha)

    baseline_contribution = self.mu * h
    excitation_contribution = ((lam - self.mu) * (1 - np.exp(-mean_reversion_rate * h)) / mean_reversion_rate)
    return baseline_contribution + excitation_contribution

  def forecast_quantile(self, t_now: float, horizon_sec: float, q: float, n_sim: int = 10000) -> float:
    from scipy.stats import poisson

    lam_forecast = self.forecast_count(t_now, horizon_sec)
    return poisson.ppf(q, mu=lam_forecast)

    @property
    def current_intensity(self) -> float:
      return self.mu + self.R_current

    @property
    def mean_intensity(self) -> float:
      return self.mu / (1 - self.alpha)

true_params = dict(mu=2.0, alpha=0.7, beta=5.0)
forecaster = HawkesForecaster(**true_params)

np.random.seed(12)
T = 100.0
events = []
lam = true_params['mu']
t = 0.0

while t < T:
  t += np.random.exponential(1.0 / max(lam, 0.01))
  if t >= T:
    break

events.append(t)
lam = true_params['mu'] + true_params['alpha'] * true_params['beta'] * sum(np.exp(-true_params['beta'] * (t - ti)) for ti in events[:-1])
events = np.array(events)

horizons = [0.5, 1.0, 5.0]
forecast_history = {h: [] for h in horizons}
intensity_history = []
event_times_for_check = []

for i, tau, in enumerate(events):
  lam_after = forecaster.update(tau)
  intensity_history.append(lam_after)

for h in horizons:
  f = forecaster.forecast_count(tau, h)
  forecast_history[h].append((tau, f))

print("\nForecast Summary(last 10 events): ")
print(f"{'Event Time': >12} {'Intensity': >12} {'Forecast(0.5s)':>14} {'Forecast(1s)':>12} {'Forecast(5s)': >12}")
for i in range(max(0, len(events) - 10), len(events)):
  tau = events[i]
  lam = intensity_history[i]
  forecast_05 = forecast_history[0.5][-1][1]
  forecast_1 = forecast_history[1.0][-1][1]
  forecast_5 = forecast_history[5.0][-1][1]
  print(f"{tau: >12.3f} {lam: >12.4f} {forecast_05: >14.4f} {forecast_1: >12.4f} {forecast_5: >12.4f}")

