# -*- coding: utf-8 -*-
"""Linking Order Flow to Volatility.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from scipy.stats import norm

class HARRVHawkes:
    def __init__(self, use_hawkes_features: bool = True):
        self.use_hawkes_features = use_hawkes_features
        self.model = LinearRegression()
        self.feature_names = None
        self.is_fitted = False

    def _build_features(self, rv_series: pd.Series,
                        hawkes_intensity: pd.Series = None,
                        branching_ratio: pd.Series = None,
                        trade_counts: pd.Series = None) -> pd.DataFrame:
        log_rv = np.log(rv_series.clip(lower=1e-10))
        features = pd.DataFrame(index=rv_series.index)

        features['RV_d'] = log_rv.shift(1)
        features['RV_w'] = log_rv.shift(1).rolling(5).mean()
        features['RV_m'] = log_rv.shift(1).rolling(22).mean()

        if self.use_hawkes_features and hawkes_intensity is not None:
            features['log_lambda'] = np.log(hawkes_intensity.shift(1).clip(lower=1e-6))
        if branching_ratio is not None:
            features['n_star'] = branching_ratio.shift(1)
        if trade_counts is not None:
            features['log_N'] = np.log(trade_counts.shift(1).clip(lower=1))

        features['target'] = log_rv.shift(-1)

        features = features.dropna()
        self.feature_names = [c for c in features.columns if c != 'target']

        return features

    def fit(self, rv_series: pd.Series, **hawkes_kwargs) -> 'HARRVHawkes':
        features = self._build_features(rv_series, **hawkes_kwargs)
        X = features[self.feature_names].values
        y = features['target'].values

        self.model.fit(X, y)
        self.is_fitted = True

        print("HAR-RV - Hawkes Coefficient Estimates:")
        print(f"{'Feature': >20} {'Coefficient': >12}")
        print("-" * 35)
        for name, coef in zip(self.feature_names, self.model.coef_):
            print(f"{name: >20} {coef: >12.4f}")
        print(f"{'Intercept': >20} {self.model.intercept_: >12.4f}")
        return self

    def predict(self, rv_series: pd.Series, **hawkes_kwargs) -> pd.Series:
        assert self.is_fitted, "Model must be fitted first"
        features = self._build_features(rv_series, **hawkes_kwargs)
        X = features[self.feature_names].values
        log_rv_pred = self.model.predict(X)
        return pd.Series(np.exp(log_rv_pred), index=features.index)

    def r_squared(self, rv_series: pd.Series, **hawkes_kwargs) -> float:
        features = self._build_features(rv_series, **hawkes_kwargs)
        X = features[self.feature_names].values
        y = features['target'].values
        return self.model.score(X, y)

np.random.seed(12)
n_days = 500
rv = np.zeros(n_days)
rv[0] = 0.0001
omega, alpha_garch, beta_garch = 0.000002, 0.08, 0.90
for t in range(1, n_days):
    rv[t] = omega + alpha_garch * rv[t-1] * np.random.randn()**2 + beta_garch * rv[t-1]

rv_series = pd.Series(rv, name='RV')

base_intensity = 100 + 50 * np.sqrt(rv / rv.mean())
hawkes_intensity = pd.Series(
    base_intensity + 10 * np.random.randn(n_days), name='lambda')
n_star = pd.Series(0.6 + 0.15 * (rv / rv.mean() - 1) + 0.05 * np.random.randn(n_days),name='n_star').clip(0.01, 0.95)
trade_counts = pd.Series((hawkes_intensity * 390 + 1000 * np.random.randn(n_days)).clip(lower=100),name='N')

train_rv = rv_series.iloc[:400]
test_rv = rv_series.iloc[400:]

har_baseline = HARRVHawkes(use_hawkes_features=False)
print("=" * 50)
print(" BASELINE HAR-RV MODEL ")
print("=" * 50)
har_baseline.fit(train_rv)
r2_baseline = har_baseline.r_squared(train_rv)
print(f"\nIn-sample R^2: {r2_baseline:.4f}")

har_hawkes = HARRVHawkes(use_hawkes_features=True)
print("\n" + "=" * 50)
print("HAR-RV - HAWKES MODEL ")
print("=" * 50)
har_hawkes.fit(train_rv, hawkes_intensity=hawkes_intensity.iloc[:400], branching_ratio=n_star.iloc[:400],trade_counts=trade_counts.iloc[:400])
r2_hawkes = har_hawkes.r_squared(train_rv, hawkes_intensity=hawkes_intensity.iloc[:400], branching_ratio=n_star.iloc[:400], trade_counts=trade_counts.iloc[:400])
print(f"\nIn-sample R^2: {r2_hawkes:.4f}")
print(f"R^2 improvement from Hawkes features: {r2_hawkes - r2_baseline:+.4f}")

