# -*- coding: utf-8 -*-
"""Comparing Models of Market activity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
from scipy.optimize import minimize
from scipy import stats
import warnings

class HawkesMLE:
    def __init__(self, n_restarts: int = 5):
        self.n_restarts = n_restarts
        self.params_ = None
        self.loglik_ = None
        self.se_ = None
        self.converged_ = False

    def _loglik_and_grad(self, theta_raw: np.ndarray, events: np.ndarray, T: float):
        log_mu, logit_alpha, log_beta = theta_raw
        mu = np.exp(log_mu)
        alpha = 1.0 / (1.0 + np.exp(-logit_alpha))
        beta = np.exp(log_beta)

        n = len(events)
        if n == 0:
            return 0.0, np.zeros(3)

        ll = 0.0
        A = 0.0
        R = 0.0

        dR_dmu, dR_dalpha, dR_dbeta = 0.0, 0.0, 0.0
        dll_dmu, dll_dalpha, dll_dbeta = 0.0, 0.0, 0.0

        prev_tau = 0.0

        for i in range(n):
            tau_i = events[i]
            dt = tau_i - prev_tau

            e_decay = np.exp(-beta * dt)
            R = e_decay * (R + 1.0)

            lam_i = mu + alpha * beta * R

            if lam_i <= 0:
                return -1e15, np.zeros(3)

            ll += np.log(lam_i)

            A += 1.0 - np.exp(-beta * (T - tau_i))

            prev_tau = tau_i

        ll -= mu * T + alpha * A

        return ll

    def loglik(self, mu: float, alpha: float, beta: float, events: np.ndarray, T: float) -> float:
        n = len(events)
        if n == 0:
            return 0.0

        if alpha >= 1.0 or mu <= 0 or beta <= 0:
            return -np.inf

        ll = 0.0
        R = 0.0
        A = 0.0

        prev_tau = 0.0
        for i in range(n):
            tau_i = events[i]
            dt = tau_i - prev_tau
            R = np.exp(-beta * dt) * (R + 1.0)
            lam_i = mu + alpha * beta * R

            if lam_i <= 1e-300:
                return -np.inf

            ll += np.log(lam_i)
            A += 1.0 - np.exp(-beta * (T - tau_i))
            prev_tau = tau_i

        ll -= mu * T + alpha * A
        return ll

    def fit(self, events: np.ndarray, T: float) -> 'HawkesMLE':
        events = np.sort(events)
        n = len(events)

        if n < 10:
            warnings.warn(f"Only {n} events; MLE may be unreliable")

        best_ll = -np.inf
        best_x = None

        mu_mm = n / T / 2
        beta_mm = 5.0 / (np.mean(np.diff(events)) if n > 1 else 1.0)

        for restart in range(self.n_restarts):
            if restart == 0:
                x0 = np.array([mu_mm, 0.4, beta_mm])
            else:
                x0 = np.array([
                    mu_mm * np.exp(0.5 * np.random.randn()),
                    0.1 + 0.6 * np.random.rand(),
                    beta_mm * np.exp(0.5 * np.random.randn())
                ])

            def neg_ll(x):
                mu_, alpha_, beta_ = x
                if mu_ <= 0 or alpha_ <= 0 or alpha_ >= 1 or beta_ <= 0:
                    return 1e15
                return -self.loglik(mu_, alpha_, beta_, events, T)

            result = minimize(
                neg_ll, x0,
                method='L-BFGS-B',
                bounds=[(1e-6, None), (1e-6, 0.9999), (1e-4, None)],
                options={'maxiter': 2000, 'ftol': 1e-12, 'gtol': 1e-8}
            )

            if result.success or result.fun < -best_ll:
                ll_val = -result.fun
                if ll_val > best_ll:
                    best_ll = ll_val
                    best_x = result.x

        if best_x is None:
            raise RuntimeError("Optimisation failed for all restarts")

        mu_hat, alpha_hat, beta_hat = best_x
        self.params_ = {'mu': mu_hat, 'alpha': alpha_hat, 'beta': beta_hat}
        self.loglik_ = best_ll
        self.converged_ = True

        self.aic_ = -2 * best_ll + 2 * 3
        self.bic_ = -2 * best_ll + np.log(n) * 3

        return self

    def residuals(self, events: np.ndarray) -> np.ndarray:
        assert self.converged_, "Must fit before computing residuals"
        mu = self.params_['mu']
        alpha = self.params_['alpha']
        beta = self.params_['beta']

        n = len(events)
        residuals = np.zeros(n)
        R = 0.0

        for i in range(n):
            tau_i = events[i]
            if i == 0:
                dt = tau_i
                residuals[i] = mu * dt
            else:
                dt = tau_i - events[i-1]
                residuals[i] = mu * dt + alpha * R * (1.0 - np.exp(-beta * dt))

            R = np.exp(-beta * dt) * (R + 1.0)

        return residuals

    def goodness_of_fit(self, events: np.ndarray, verbose: bool = True) -> dict:
        resids = self.residuals(events)

        ks_stat, ks_pval = stats.kstest(resids, 'expon', args=(0, 1))

        from statsmodels.stats.diagnostic import acorr_ljungbox
        lb_resid = acorr_ljungbox(resids, lags=[10, 20], return_df=True)
        lb_sq = acorr_ljungbox(resids**2, lags=[10, 20], return_df=True)

        results = {
            'ks_stat': ks_stat,
            'ks_pval': ks_pval,
            'ks_pass': ks_pval > 0.05,
            'lb_pval_lag10': lb_resid['lb_pvalue'].iloc[0],
            'lb_pval_lag20': lb_resid['lb_pvalue'].iloc[1],
            'lb2_pval_lag10': lb_sq['lb_pvalue'].iloc[0],
            'lb2_pval_lag20': lb_sq['lb_pvalue'].iloc[1],
            'resid_mean': np.mean(resids),
            'resid_std': np.std(resids),
            'n_events': len(events)
        }

        if verbose:
            print("\n" + "=" * 55)
            print(" HAWKES PROCESS GOODNESS-OF-FIT REPORT ")
            print("=" * 55)
            print(f" Fitted params : mu ={self.params_['mu']:.4f} , "
                  f" alpha ={self.params_['alpha']:.4f} , "
                  f" beta ={self.params_['beta']:.4f}")
            print(f" Mean intensity : {self.params_['mu'] / (1 - self.params_['alpha']):.4f}")
            print(f" Log-likelihood : {self.loglik_:.2f}")
            print(f" AIC : {self.aic_:.2f} | BIC: {self.bic_:.2f}")
            print(f"\n KS Test vs Exp (1): stat ={ks_stat:.4f} , "
                  f"p={ks_pval:.4f} [{'PASS' if ks_pval > 0.05 else 'FAIL'}]")
            print(f" Ljung-Box (resid): lag10 p={results['lb_pval_lag10']:.4f} "
                  f" lag20 p={results['lb_pval_lag20']:.4f}")
            print(f" Ljung-Box (resid^2): lag10 p={results['lb2_pval_lag10']:.4f} "
                  f" lag20 p={results['lb2_pval_lag20']:.4f}")
            print(f"\n Residual mean : {results['resid_mean']:.4f} (expect 1.0) ")
            print(f" Residual std: {results['resid_std']:.4f} (expect 1.0) ")
            print("=" * 55)
        return results

    def summary(self) -> str:
        assert self.converged_
        mu, alpha, beta = (self.params_['mu'],
                           self.params_['alpha'],
                           self.params_['beta'])
        return (f" Hawkes (mu ={mu:.4f}, alpha ={alpha:.4f}, beta ={beta:.4f})\n"
                f" Mean intensity : {mu / (1 - alpha):.4f}\n"
                f" Branching ratio : {alpha:.4f}\n"
                f" Log-likelihood : {self.loglik_:.4f}\n"
                f" AIC : {self.aic_:.4f} , BIC: {self.bic_:.4f}")

class HawkesParams:
    def __init__(self, mu, alpha, beta):
        self.mu = mu
        self.alpha = alpha
        self.beta = beta

class HawkesSimulator:
    def __init__(self, params, seed=42):
        self.params = params
        self.seed = seed

    def simulate(self, T=500.0):
        np.random.seed(self.seed)
        mu, alpha, beta = self.params.mu, self.params.alpha, self.params.beta

        events = []
        t = 0.0

        while t < T:
            if len(events) == 0:
                lambda_max = mu
            else:
                history_term = np.sum(np.exp(-beta * (t - np.array(events))))
                lambda_max = mu + alpha * beta * (history_term + 1.0)

            U = np.random.exponential(1.0 / lambda_max)
            t += U
            if t >= T:
                break

            history_term = np.sum(np.exp(-beta * (t - np.array(events))))
            lambda_t = mu + alpha * beta * history_term

            D = np.random.uniform(0.0, 1.0)
            if D <= (lambda_t / lambda_max):
                events.append(t)

        return np.array(events)

np.random.seed(12)

TRUE_PARAMS = {'mu': 1.5, 'alpha': 0.65, 'beta': 4.0}

hawkes_params = HawkesParams(**TRUE_PARAMS)
sim = HawkesSimulator(hawkes_params, seed=99)
T = 500.0
true_events = sim.simulate(T)
print(f"Simulated {len(true_events)} events in [0, {T}]")

estimator = HawkesMLE(n_restarts=5)
estimator.fit(true_events, T)

print("\nParameter Recovery:")
print(f"{'Param': >8} {'True': >10} {'Estimated': >12} {'Error': >8}")
for k in ['mu', 'alpha', 'beta']:
    true_val = TRUE_PARAMS[k]
    est_val = estimator.params_[k]
    print(f"{k: >8} {true_val: >10.4f} {est_val: >12.4f} "
          f"{abs(est_val - true_val) / true_val * 100: >7.2f}%")

gof = estimator.goodness_of_fit(true_events, verbose=True)

