# -*- coding: utf-8 -*-
"""Production Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from collections import deque
from numba import njit
from typing import Optional

class ProductionOBIModel:
  def __init__(self, n_features: int = 5, forgetting_factor: float = 0.9998, max_position: float = 1e6, gamma_risk: float = 1e-7):
    self.n = n_features
    self.rho = forgetting_factor
    self.max_pos = max_position
    self.gamma = gamma_risk

    self.beta = np.zeros(n_features)
    self.P = np.eye(n_features) * 100.0

    self.position = 0.0
    self.cash = 0.0
    self.pnl_hist = []
    self.signal_hist = deque(maxlen=10000)

  def update_rls(self, x: np.ndarray, y: float) -> None:
    rho = self.rho
    Px = self.P @ x
    denom = rho + x @ Px
    K = Px / denom
    self.P = (self.P - np.outer(K, x @ self.P)) / rho
    pred_err = y - x @ self.beta
    self.beta += K * pred_err

  def predict(self, x: np.ndarray) -> float:
    return float(x @ self.beta)

  @staticmethod
  def build_feature_vector(obi: float, di5: float, ofi: float, mp_dev: float, realized_vol: float) -> np.ndarray:
    return np.array([obi, di5, mp_dev, realized_vol])

  def compute_position(self, alpha: float, price_vol: float, signal_vol: float) -> float:
    if signal_vol < 1e-10:
      return 0.0
    raw_pos = alpha / (self.gamma * price_vol ** 2)
    pos = np.clip(raw_pos, -self.max_pos, self.max_pos)
    return float(pos)

  def compute_transaction_cost(self, trade_qty: float, spread: float, price_vol: float, commission_per_share: float=0.003) -> float:
    half_spread = 0.5 * spread * abs(trade_qty)
    impact = 1e-5 * abs(trade_qty) ** 1.5 * price_vol
    commission = commission_per_share * abs(trade_qty)
    return half_spread + impact + commission

  def step(self, market_data: dict) -> dict:
    bid = market_data['bid']
    ask = market_data['ask']
    bq = market_data['bid_qty']
    aq = market_data['ask_qty']
    spread = ask - bid
    mid = 0.5 * (bid - ask)
    total = bq + aq + 1e-10
    obi = (bq - aq) / total
    mp = bid * (aq/total) + ask * (bq/total)
    mp_dev = (mp - mid) / max(spread/2, 1e-8)
    di5 = market_data.get('di5', obi)
    ofi = market_data.get('ofi_10s', 0.0)
    rvol = market_data.get('realized_vol', spread)

    x = self.build_feature_vector(obi, di5, ofi, mp_dev, rvol)
    alpha = self.predict(x)
    desired_pos = self.compute_position(alpha, rvol, 1.0)
    trade_qty = desired_pos - self.position
    tc = self.compute_transaction_cost(trade_qty, spread, rvol, mid)

    self.position = desired_pos
    self.signal_hist.append(alpha)

    return {'alpha': alpha, 'obi': obi, 'microprice': mp, 'desired_pos': desired_pos, 'tc_estimate': tc, 'mid': mid, 'spread': spread}

  def update_model(self, x: np.ndarray, realized_return: float) :
    self.update_rls(x, realized_return)

  def attribution_report(self, trades_df: pd.DataFrame) -> dict:
    if len(trades_df) == 0:
      return {}

    trades_df = trades_df.copy()
    trades_df['pnl_gross'] = (trades_df['qty'] * trades_df['price'].diff().shift(-1))
    total_gross = trades_df['pnl_gross'].sum()
    total_tc = trades_df['tc'].sum()
    net_pnl = total_gross - total_tc
    tc_ratio = total_tc / max(abs(total_gross), 1e-8)
    return {'gross_pnl': total_gross, 'total_tc': total_tc, 'net_pnl': net_pnl, 'tc_drag_pct': tc_ratio * 100, 'n_trades': len(trades_df), 'avg_alpha': trades_df['alpha'].mean()}

class ModelPerformanceMonitor:
  def __init__(self, window: int = 1000, ic_threshold: float = 0.02):
    self.window = window
    self.threshold = ic_threshold
    self.alpha_buffer = deque(maxlen=window)
    self.return_buffer = deque(maxlen=window)
    self.ic_history = []

  def update(self, alpha: float, realized_return: float):
    self.alpha_buffer.append(alpha)
    self.return_buffer.append(realized_return)
    if len(self.alpha_buffer) == self.window:
      self._compute_ic()

  def _compute_ic(self):
    from scipy.stats import spearmanr
    ic, _ = spearmanr(list(self.alpha_buffer), list(self.return_buffer))
    self.ic_history.append(ic)
    if len(self.ic_history) > 5:
      recent_ic = np.mean(self.ic_history[-5:])
      if abs(recent_ic) < self.threshold:
        print(f"[ALERT] IC degraded: {recent_ic:.4f} < {self.threshold}")

  def get_live_ic(self) -> Optional[float]:
    if len(self.ic_history) == 0:
      return None
    return self.ic_history[-1]

