# -*- coding: utf-8 -*-
"""Imbalance Metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from numba import njit

@njit
def compute_obi(bid_qty: float, ask_qty: float) -> float:
  total = bid_qty + ask_qty
  if total == 0.0:
    return 0.0
  return (bid_qty - ask_qty) / total

@njit
def compute_obi_log(bid_qty: float, ask_qty: float, eps: float = 1e-6) -> float:
  return np.log((bid_qty + eps) / (ask_qty + eps))

@njit
def compute_obi_vw(bid_qty: float, ask_qty: float) -> float:
  denom = max(bid_qty, ask_qty)
  if denom == 0.0:
    return 0.0
  return (bid_qty - ask_qty) / denom

def batch_compute_obi(lob_snapshots: pd.DataFrame) -> pd.DataFrame:
  df = lob_snapshots.copy()
  bq = df['bid_qty_1'].values
  aq = df['ask_qty_1'].values

  df['obi'] = (bq - aq) / (bq + aq + 1e-10)
  df['obi_log'] = np.log((bq + 1e-6) / (aq + 1e-6))
  df['obi_vw'] = (bq - aq) / np.maximum(bq, aq + 1e-10)

  for col in ['obi', 'obi_log', 'obi_vw']:
    lo, hi = np.percentile(df[col], [1, 99])
    df[col + '_w'] = df[col].clip(lo, hi)

  return df

from statsmodels.tsa.stattools import adfuller

def test_obi_stationarity(obi_series: pd.Series, verbose: bool=True):
  result = adfuller(obi_series.dropna(), autolog='AIC')
  if verbose:
    print(f"ADF Statistic: {result[0]:.4f}")
    print(f"p-value: {result[1]:.6f}")
    print(f"Critical Values: {result[4]}")
  return result[1] < 0.05

