# -*- coding: utf-8 -*-
"""Queue Imbalance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np
from scipy.stats import pearsonr

class QueueImbalanceModel:
  def __init__(self, lambda_b: float, lambda_a: float, mu_b: float, mu_a: float, theta: float = 0.0):
    self.lam_b = lambda_b
    self.lam_a = lambda_a
    self.mu_b = mu_b
    self.mu_a = mu_a
    self.theta = theta

  def up_move_probability(self, q_bid: int, q_ask: int) -> float:
    if q_bid == 0 and q_ask == 0:
      return 0.5
    if self.theta == 0.0:
      total = q_bid + q_ask
      if self.mu_b == self.mu_a:
        return q_ask / total
      else:
        rho = self.mu_b / self.mu_a
        if abs(rho - 1.0) < 1e-10:
          return q_ask / total
        return (1 - rho ** q_ask) / (1 - rho ** total)
    else:
      return self._mc_up_prob(q_bid, q_ask, n_sim=5000)

    def _mc_up_prob(self, q0_bid: int, q0_ask: int, n_sim: int = 5000) -> float:
      up_count = 0
      for _ in range(n_sim):
        qb, qa = q0_bid, q0_ask
        while qb > 0 and qa > 0:
          rate_up_ask = self.lam_a
          rate_dn_ask = self.mu_a + self.theta * qa
          rate_up_bid = self.lam_b
          rate_dn_bid = self.mu_b + self.theta * qb
          total_rate = rate_up_ask + rate_dn_ask + rate_up_bid + rate_dn_bid

          u = np.random.uniform() * total_rate
          if u < rate_up_ask:
            qa += 1
          elif u < rate_up_ask + rate_dn_ask:
            qa = max(0, qa - 1)
          elif u < rate_up_ask + rate_dn_ask + rate_up_bid:
            qb += 1
          else:
            qb = max(0, qb - 1)

        if qa == 0:
          up_count += 1
      return up_count / n_sim

      def compute_qi(self, q_bid: float, q_ask: float) -> float:
        total = q_bid + q_ask
        return (q_bid - q_ask) / total if total > 0 else 0.0

      def ewma_qi(self, qi_series: np.ndarray, kappa: float) -> np.ndarray:
        n = len(qi_series)
        ewma = np.zeros(n)
        ewma[0] = qi_series[0]
        for i in range(1, n):
          ewma[i] = kappa * qi_series[i] + (1 - kappa) * ewma[i-1]
        return ewma

  def validate_qi_predictability(df: pd.DataFrame, horizons_ms: list) -> pd.DataFrame:
    results = []
    qi = (df['bid_qty_1'] - df['ask_qty_1']) / (df['bid_qty_1'] + df['ask_qty_1'] + 1e-10)

    for h in horizons_ms:
      n_steps = max(1, int(h / df['timestamp'].diff().median()))
      fwd_ret = df['mid_price'].shift(-n_steps) - df['mid_price']
      mask = fwd_ret.notna()
      r , p = pearsonr(qi[mask], fwd_ret[mask])
      results.append({'horizon_ms': h, 'pearson_r': round(r, 4), 'r_squared': round(r**2, 4), 'p_value': round(p, 6)})
    return pd.DataFrame(results)

