# -*- coding: utf-8 -*-
"""Queue Imbalance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge
from scipy.optimize import minimize

class DepthImbalanceAnalyzer:
  def __init__(self, K: int =10):
    self.K = K
    self.optimal_Weights = None

  def compute_cumulative_di(self, lob: pd.DataFrame, K: int = None) -> pd.Series:
    K = K or self.K
    bid_depth = sum(lob[f'bid_qty_{k}'] for k in range(1, K+1))
    ask_depth = sum(lob[f'ask_qty_{k}'] for k in range(1, K+1))
    total = bid_depth + ask_depth
    return (bid_depth - ask_depth) / total.replace(0, np.nan)

  def compute_Weighted_di(self, lob: pd.DataFrame, weights: np.ndarray = None, scheme: str = 'exponential', rho: float = 0.5) -> pd.Series:
    K = self.K
    if weights is None:
      if scheme == 'uniform':
        weights = np.ones(K)
      elif scheme == 'linear':
        weights = np.array([K + 1 - k for k in range(1, K+1)], dtype=float)
      elif scheme == 'exponential':
        weights = np.exp(-rho* np.arange(K))
      elif scheme == 'inverse':
        weights = 1.0 / np.arange(1, K+1)
      elif scheme == 'optimal':
        weights = self.optimal_weights
        if weights is None:
          raise ValueError("Call fit_optimal_weights first")

    numerator = np.zeros(len(lob))
    denominator = np.zeros(len(lob))
    for k in range(1, K+1):
      bq = lob[f'bid_qty_{k}'].values
      aq = lob[f'ask_qty_{k}'].values
      numerator += weights[k-1] * (bq - aq)
      denominator += weights[k-1] * (bq + aq)

    di = numerator / np.where(denominator > 0, denominator, np.nan)
    return pd.Series(di, index=lob.index)

  def compute_slope_imbalance(self, lob: pd.DataFrame) -> pd.Series:
    K = self.K
    k_vals = np.arange(1, K+1, dtype=float)
    bid_slopes = np.zeros(len(lob))
    ask_slopes = np.zeros(len(lob))

    for i, row in enumerate(lob.itertuples(index=False)):
      bvol = np.array([getattr(row, f'bid_qty_{k}') for k in range(1, K+1)], dtype=float)
      avol = np.array([getattr(row, f'ask_qty_{k}') for k in range(1, K+1)], dtype=floatt)
      A = np.vstack([k_vals, np.ones(K)]).T
      bid_slopes[i] = np.linalg.lstsq(A, bvol, rcond=None)[0][0]
      ask_slopes[i] = np.linalg.lstsq(A, avol, rcond=None)[0][0]

    return pd.Series(bid_slopes - ask_slopes, index=lob.index)

  def fit_optimal_weights(self, lob_train: pd.DataFrame, fwd_returns: pd.Series) -> np.ndarray:
    K = self.K
    X = np.zeros((len(lob_train), K))
    for k in range(1, K+1):
      bq = lob_train[f'bid_qty_{k}'].values
      aq = lob_train[f'ask_qty_{k}'].values
      total = bq + aq
      X[:, K-1] = np.where(total > 0, (bq - aq) / total, 0)

    y = fwd_returns.values
    mask = -np.isnan(y)
    model = Ridge(alpha=1.0, positive=True)
    model.fit(X[mask], y[mask])
    self.optimal_weights = model.coef_
    return self.optimal_weights

  def depth_profile_imbalance(self, lob_row: pd.Series) -> dict:
    result = {}
    K = self.K
    cum_bid = 0.0
    cum_ask = 0.0
    for k in range(1, K+1):
      bq = lob_row.get(f'bid_qty_{k}', 0.0)
      aq = lob_row.get(f'ask_qty_{k}', 0.0)
      cum_bid += bq
      cum_ask += aq
      total = bq + aq
      result[f'di_marginal_{k}'] = (bq-aq) / total if total > 0 else 0

      total_cum = cum_bid + cum_ask
      result[f'di_cumulative_{k}'] = (cum_bid - cum_ask) / total_cum if total_cum > 0 else 0

    return result

