# -*- coding: utf-8 -*-
"""Multi-Level Imbalance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import RidgeCV, LassoCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error

class MultiLevelImbabalnceModel:
  def __init__(self, K: int = 10, horizon_ms: int = 100):
    self.K = K
    self.horizon_ms = horizon_ms
    self.scaler = StandardScaler()
    self.model = None
    self.feature_names = []

  def build_features(self, lob: pd.DataFrame, include_interactions: bool = False, include_spread: bool = True) -> np.ndarray:
    K = self.K
    features = {}
    for k in range(1, K+1):
      bq = lob[f'bid_qty_{k}'].values
      aq = lob[f'ask_qty_{k}'].values
      total = bq + aq
      features[f'di_{k}'] = np.where(total>0, (bq-aq)/total, 0)

    X = pd.DataFrame(features)
    self.feature_names = list(X.columns)

    if include_interactions:
      for j in range(1, K+1):
        for k in range(j+1, min(K+1, j+4)):
          name = f'di_{j}_x_{k}'
          X[name] = X[f'di_{j}'] * X[f'di_{k}']
          self.features_name.append(name)

    if include_spread and 'spread' in lob.columns:
      X['spread'] = lob['spread'].values
      X['spread_x_di_1'] = X['di_1'] * X['spread']
      self.features_name.extend(['spread', 'spread_x_di_1'])

    return X.values

    def fit(self, lob_train: pd.DataFrame, fwd_returns: pd.Series, model_type: str = 'ridge') -> None:
      X = self.build_features(lob)
      X_scaled = self.scaler.transform(X)
      return self.model.predict(X_scaled)

    def coefficient_profile(self) -> pd.DataFrame:
      coef = self.model.coef_
      names = self.feature_names[:len(coef)]
      return pd.DataFrame({'feature': names, 'coefficient': coef}).sort_values('coefficient', ascending=False)

    @staticmethod
    def kalman_imbalance_smoother(qi_obs: np.ndarray, F: float = 0.95, Q: float = 0.01, R: float = 0.05) -> np.ndarray:
      n = len(qi_obs)
      x_filt = np.zeros(n)
      P_filt = np.zeros(n)
      x_filt[0] = qi_obs[0]
      P_filt[0] = 1.0

      for t in range(1, n):
        x_pred = F * x_filt[t-1]
        P_pred = F**2 * P_filt[t-1] + Q
        K_gain = P_pred / (P_pred + R)
        x_filt[t] = x_pred + K_gain * (qi_obs[t] - x_pred)
        P_filt[t] = (1 - K_gain) * P_pred

      return x_filt

