# -*- coding: utf-8 -*-
"""Predictive Power of Imbalance Signals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from scipy import stats
from statsmodels.regression.linear_model import OLS
from statsmodels.tsa.stattools import grangercausalitytests
from sklearn.metrics import r2_score
import warnings

class PredictivePowerAnalyzer:
  @staticmethod
  def compute_r2_across_horizons(signal: pd.Series, mid_prices: pd.Series, horizons_ms: list, freq_ms: float = 1.0) -> pd.DataFrame:
    results = []
    n = len(signal)
    train_size = int(0.7 * n)

    for h in horizons_ms:
      steps = max(1, int(h / freq_ms))
      fwd_ret = mid_prices.shift(-steps) - mid_prices
      mask = fwd_ret.notna()

      X_train = signal[:train_size][mask[:train_size]].values.reshape(-1, 1)
      y_train = fwd_ret[:train_size][mask[:train_size]].values
      X_test = signal[train_size:][mask[train_size:]].values.reshape(-1, 1)
      y_test = fwd_ret[train_size:][mask[train_size:]].values

      beta = np.polyfit(X_train.flatten(), y_train, 1)
      y_pred = np.polyval(beta, X_test.flatten())

      r2 = r2_score(y_test, y_pred)
      dir_acc = np.mean(np.sign(y_pred) == np.sign(y_test))

      r_corr, p_val = stats.pearsonr(X_test.flatten(), y_test)

      results.append({
          'horizon_ms': h,
          'r2_oos': r2,
          'dir_acc': dir_acc,
          'pearson_r': r_corr,
          'p_value': p_val,
          'n_obs': len(y_test)
      })
      return pd.DataFrame

    @staticmethod
    def diebold_mariano_test(err_a: np.ndarray, err_b: np.ndarray, loss: str = 'squared') -> dict:
      if loss == 'squared':
        d = err_a**2 - err_b**2
      elif loss == 'absolute':
        d = np.abs(err_a) - np.abs(err_b)
      else:
        raise ValueError("Loss function must be 'squared' or 'absolute'.")
        d_bar = np.mean(d)
        T = len(d)
        lag = int(np.ceil(T**(1/3)))
        cov = np.cov(d) / T
        for j in range(1, lag+1):
          w = 1 - j / (lag + 1)
          gamma_j = np.mean((d[j:] - d_bar) * (d[:-j] - d_bar))
          cov += 2 * w * gamma_j / T

        dm_stat = d_bar / np.sqrt(max(cov, 1e-15))
        p_value = 2 * (1 - stats.norm.cdf(abs(dm_stat)))

        return {'dm_stat': dm_stat, 'p_value': p_value, 'mean_diff': d_bar, 'model_a_better': d_bar < 0}

    @staticmethod
    def compute_information_ratio(signal: np.ndarray, returns: np.ndarray, cost_per_trade: float = 0.0, annualize: float = 252 * 6.5 * 3600) -> dict:
      positions = np.sign(signal[:-1])
      pnl = positions * returns[1:] - np.abs(positions) * cost_per_trade
      mean_pnl = np.mean(pnl)
      std_pnl = np.std(pnl)
      n = len(pnl)
      ir = mean_pnl / (std_pnl + 1e-10) * np.sqrt(annualize / n)
      return {'mean_pnl': mean_pnl, 'std_pnl': std_pnl, 'ir': ir, 'hit_rate': np.mean(pnl > 0)}

