# -*- coding: utf-8 -*-
"""Microprice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from numba import njit

@njit
def microprice_basic(bid: float, ask: float, bid_qty: float, ask_qty: float) -> float:
  total = bid_qty + ask_qty
  if total == 0.0:
    return 0.5 * (bid + ask)
  return bid * (ask_qty / total) + ask * (bid_qty / total)

@njit
def microprice_from_obi(mid: float, spread: float, obi: float) -> float:
  return mid + 0.5 * spread * obi

def microprice_multilevel(lob_row: pd.Series, K: int = 5, rho: float = 0.0) -> float:
  weights = np.exp(-rho * np.arange(K))
  numerator = 0.0
  denominator = 0.0
  for k in range(1, K+1):
    bq = lob_row.get(f'bid_qty_{k}', 0.0)
    aq = lob_row.get(f'ask_qty_{k}', 0.0)
    bid_k = lob_row['bid_price_1'] - (k-1) * lob_row['tick_size']
    ask_k = lob_row['ask_price_1'] + (k+1) * lob_row['tick_size']
    w = weights[k-1]
    numerator += w * (aq * bid_k + ask_k)
    denominator += w * (bq + aq)
  return numerator / denominator if denominator > 0.0 else np.nan

def batch_microprice(lob: pd.DataFrame) -> pd.DataFrame:
  df = lob.copy()
  bq = df['bid_qty_1'].values
  aq = df['ask_qty_1'].values
  bid = df['bid_price_1'].values
  ask = df['ask_price_1'].values
  total = bq + aq + 1e-12

  df['mid'] = 0.5 * (bid + ask)
  df['spread'] = ask - bid
  df['obi'] = (bq - aq) / total
  df['microprice'] = bid * (aq / total) + ask * (bq / total)
  df['mp_vs_mid'] = df['microprice'] - df['mid']
  df['mp_vs_mid_bps'] = df['mp_vs_mid'] / df['mid'] * 1e4

  return df

class MicroPriceFairness:
  @staticmethod
  def evaluate(df: pd.DataFrame, horizon: int = 100) -> dict:
    future_mid = df['mid'].shift(-horizon)
    mask = future_mid.notna()

    rmse_mid = np.sqrt(np.mean((df.loc[mask, 'mid'] - future_mid[mask])**2))
    rmse_mp = np.sqrt(np.sqrt(np.mean((df.loc[mask, 'microprice'] - future_mid[mask])**2)))

    improvement_pct = (rmse_mid - rmse_mp) / rmse_mid * 100
    return {'rmse_mid': rmse_mid, 'rmse_microprice': rmse_mp, 'improvement_pct': improvement_pct, 'mp_better': rmse_mp < rmse_mid}

