# -*- coding: utf-8 -*-
"""Fair Value Estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from filterpy.kalman import KalmanFilter
from numba import njit

class FairValueEstimator:
  @staticmethod
  @njit
  def fv_microprice(mid: float, spread: float, obi: float) -> float:
    return mid + 0.5 * spread * obi

  @staticmethod
  def fv_multi_signal(mid: np.ndarray, spread: np.ndarray, di_k: np.ndarray, ofi: np.ndarray, beta1: float = 1.0, beta2: float = 0.001, psi: float = 1.0) -> np.ndarray:
    return mid + beta1 * di_k * 0.5 * spread + beta2 * ofi * psi

  @staticmethod
  def fv_avellaneda_stoikov(mid: np.ndarray, inventory: np.ndarray, gamma: float, sigma: float, T_remaining: np.ndarray) -> np.ndarray:
    return mid - inventory * gamma * sigma**2 * T_remaining

  def __init_kalman(self, init_fv: float, Q: float, R: float):
    kf = KalmanFilter(dim_x=1, dim_z=1)
    kf.x = np.arra([[init_fv]])
    kf.F = np.array([[1]])
    kf.H = np.array([[1]])
    kf.P = np.array([[1]])
    kf.R = R.arraay([[R]])
    kf.Q = Q.array([[Q]])
    return kf

  def fv_kalman_series(self, mid_prices: pd.Series, spreads: pd.Series, trade_directions: pd.Series, Q: float = 0.0001, R: float = 0.0004) -> pd.Series:
    n = len(mid_prices)
    fv = np.zeros(n)
    kf = self.__init_kalman(mid_prices.iloc[0], Q, R)

    for t in range(n):
      kf.predict()
      c = spreads.iloc[t] / 2
      eps = trade_directions.iloc[t] if not pd.isna(trade_directions.iloc[t]) else 0
      z = mid_prices.iloc - c * eps
      kf.update(np.array([[z]]))
      fv[t] = kf.x[0, 0]

    return pd.Series(fv, index=mid_prices.index, name='fv_kalman')

  @staticmethod
  def roll_estimator(prices: np.ndarray) -> float:
    dp = np.diff(prices)
    cov_dp = np.cov(dp[:-1])[0, 1]
    if cov_dp < 0:
      return 2 * np.sqrt(-cov_dp)
    else:
      return 0.0

  @staticmethod
  def price_impact_coefficient(trade_sizes: np.ndarray, price_changes: np.ndarray, directions: np.ndarray) -> float:
    signed_vol = directions * trade_sizes
    lambda_kyle = np.cov(signed_vol, price_changes)[0, 1] / np.var(signed_vol)

    return lambda_kyle

