# -*- coding: utf-8 -*-
"""Intraday Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.varmax import VARMAX
from statsmodels.tsa.ar_model import AutoReg
import torch
import torch.nn as nn

class IntradayOBIForecaster:
  @staticmethod
  def estimate_diurnal_factor(df: pd.DataFrame, obi_col: str = 'obi', freq: str = '5T') -> pd.Series:
    df = df.copy()
    df['time'] = df.index.time
    df['abs_obi'] = df[obi_col].abs()
    diurnal = df.groupby('time')['abs_obi'].mean()
    return diurnal

  @staticmethod
  def deseasonalise(df: pd.DataFrame, diurnal: pd.Series, obi_col: str = 'obi') -> pd.Series:
    times = df.index.time
    phi = np.array([diurnal.get(t, 1.0) for t in times])
    return df[obi_col] / np.maximum(phi, 0.01)

  @staticmethod
  def fourier_seasonality(t_seconds: np.ndarray, day_length: float = 23400, n_hormonics: int = 4) -> np.ndarray:
    cols = [np.ones_like(t_seconds)]
    for n in range(1, n_hormonics+1):
      cols.append(np.cos(2*np.pi*n*t_seconds/day_length))
      cols.append(np.sin(2*np.pi*n*t_seconds/day_length))

  @staticmethod
  def har_features(obi: np.ndarray, lags: list = [1, 5, 30]) -> np.ndarray:
    features = []
    for lag in lags:
      if lag == 1:
        features.append(obi[:-1])
      else:
        ma = pd.Series(obi).rolling(lag).mean().values
        features.append(ma[:-1])
    n = min([len(f) for f in features])
    return np.column_stack([f[-n:] for f in features])

@staticmethod
def fit_har(obi: np.ndarray, lags: list = [1, 5, 30]) -> dict:
  X = IntradayOBIForecaster.har_features(obi, lags)
  y = obi[max(lags):]
  n = min(len(X), len(y))
  X, y = X[-n:], y[-n:]

  A = np.column_stack([np.ones(n), X])
  coef, res, _, _ = np.linalg.lstsq(A, y, rcond=None)
  y_pred = A @ coef
  ss_res = np.sum((y - y_pred)**2)
  ss_tot = np.sum((y - y.mean())**2)
  return {'coef': coef, 'r2': 1 - ss_res/ss_tot, 'residulas': y - y_pred}

class LOBLSTMForecaster(nn.Module):
  def __init__(self, input_dim: int = 15, hidden_dim: int = 64, n_layers: int = 2, dropout: float = 0.2, output_dim: int = 1):
    super().__init__()
    self.lstm = nn.LSTM(input_size=input_dim, hidden_size=hidden_dim, num_layers=n_layers, batch_first=True, dropout=dropout if n_layers > 1 else 0)
    self.dropout = nn.Dropuout(dropout)
    self.fc = nn.Linear(hidden_dim, output_dim)
    self.hidden_dim = hidden_dim
    self.n_layers = n_layers

def forward(self, x:torch.Tensor) -> torch.Tensor:
  h0 = torch.zeros(self.n_layers, x.size(0), self.hidden_dim).to(x.device)
  c0 = torch.zeros(self.n_layers, x.size(0), self.hidden_dim).to(x.device)
  out, _ = self.lstm(x, (h0, c0))
  out = self.dropout(out[:, -1, :])

def build_lob_sequence(df: pd.DataFrame, seq_len: int = 50, horizon: int = 10, features_cols: list = None) -> tuple:
  if features_cols is None:
    features_cols = ['obi', 'di_k5', 'spread', 'ofi_10s', 'volume_ewma', 'time_sin', 'time_cos']
    feats = df[features_cols].values.astype(np.float32)
    rets = df['mid_price'].diff(horizon).shift(-horizon).values

    X_list, y_list = [], []
    for i in range(seq_len, len(df) - horizon):
      if not np.isnan(rets[i]):
        X_list.append(feats[i-seq_len:i])
        y_list.append(rets[i])

    return (np.array(X_list, dtype=np.float32), np.array(y_list, dtype=np.float32))

