# -*- coding: utf-8 -*-
"""Signal Construction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mal1QEiLBf8M3tLlHQs26mjIF1csnRL7
"""

import numpy as np
import pandas as pd
from numba import njit
from scipy.stats import spearmanr

class SignalConstructionPipeline:
  def __init__(self, roll_window: int = 1000, ewma_lambda: float = 0.1, zscore_clip: float = 3.0):
    self.roll_window = roll_window
    self.ewma_lambda = ewma_lambda
    self.zscore_clip = zscore_clip

  def validate_lob(self, df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    crossed = df['bid_price_1'] >= df['ask_price_1']
    if crossed.any():
      print(f"Removed {crossed.sum()} crossed market entries")
      df = df[-crossed]

    df = df[df['ask_price_1'] > df['bid_price_1']]
    df = df[(df['bid_qty_1'] > 0) & (df['ask_qty_1'] > 0)]

    for col in ['bid_qty_1', 'ask_qty_1']:
      p99 = df[col].quantile(0.99)
      df[col] = df[col].clip(upper=p99)

  def compute_raw_signals(self, df: pd.DataFrame) -> pd.DataFrame:
    bq = df['bid_qty_1'].values
    aq = df['ask_qty_1'].values
    total = bq + aq + 1e-10
    df['obi'] = (bq - aq) / total
    df['obi_log'] = np.log(bq+ 1e-6) / (aq + 1e-6)
    df['mid'] = 0.5 * (df['bid_price_1'] + df['ask_price_1'])
    df['spread'] = df['ask_price_1'] - df['bid_price_1']
    df['microprice'] = df['bid_price_1']*(aq/total) + df['ask_price_1']*(bq/total)
    return df

  def remove_sesonality(self, df: pd.DataFrame, obi_col: str = 'obi') -> pd.DataFrame:
    if not isinstance(df.index, pd.DatetimeIndex):
      return df
    df = df.copy()
    df['_time_min'] = (df.index.hour * 60 + df.index.minute)
    diurnal = df.groupby('_time_min')[obi_col].transform(lambda x: x.abs().mean())
    df['obi_deseason'] = df[obi_col] / diurnal.clip(lower=0.001)
    df.drop('_time_min', axis=1, inplace=True)
    return df

  def normalise(self, df: pd.DataFrame, obi_col: str = 'obi') -> pd.DataFrame:
    df = df.copy()
    w = self.roll_window
    roll = df[obi_col].rolling(w, min_periods=w//2)
    mu = roll.mean()
    sig = roll.std()
    zscore = (df[obi_col] - mu) / sig.clip(lower=1e-8)
    df['obi_zscore'] = zscore.clip(-self.zscore_clip, self.zscore_clip)
    return df

  def smooth(self, df: pd.DataFrame, signal_col: str = 'obi_zscore') -> pd.DataFrame:
    df = df.copy()
    lam = self.ewma_lambda
    df['signal_ewma'] = df[signal_col].ewm(alpha=lam).mean()
    return df

  def combine_signals(self, df: pd.DataFrame, signal_cols: list, weights: np.ndarray = None) -> pd.Series:
    if weights is None:
      weights = np.ones(len(signal_cols)) / len(signal_cols)
    weights = weights / weights.sum()

    combined = sum(w * df[col] for w, col in zip(weights, signal_cols))
    return combined

  def compute_ic(self, signal: pd.Series, fwd_return: pd.Series, rolling_window: int = 500) -> dict:
    mask = fwd_return.notna() & signal.notna()
    ic_full = spearmanr(signal[mask], fwd_return[mask])[0]

    ic_rolling = pd.Series(index=signal.index, dtype=float)
    for i in range(rolling_window, len(signal)):
      s1 = slice(i-rolling_window, i)
      mask_r = fwd_return.iloc[s1].notna()
      if mask_r.sum() > 10:
        ic_rolling.iloc[i] = spearmanr(signal.iloc[s1][mask_r], fwd_return.iloc[s1][mask_r])[0]
    icir = ic_rolling.mean() / ic_rolling.std()
    return {'ic': ic_full, 'ic_mean': ic_rolling.mean(), 'ic_std': ic_rolling.std(), 'icir': icir}

  def full_pipeline(self, df: pd.DataFrame, fwd_horizons: int = 100) -> pd.DataFrame:
    df = self.validate_lob(df)
    df = self.compute_raw_signals(df)
    df = self.remove_seasonality(df)
    df = self.normalize(df)
    df = self.smooth(df)
    df['fwd_return'] = df['mid'].shift(-fwd_horizons) - df['mid']
    return df

